- blazor/datagrid/cell.md
Blazor datagrid documentation cells topics revamp.
> BLAZ-840138-Blazor datagrid documentation cells topics revamp.

- blazor-toc.html
- blazor/datagrid/column-chooser.md
- blazor/datagrid/column-headers.md
- blazor/datagrid/column-menu.md
- blazor/datagrid/column-rendering.md
- blazor/datagrid/column-reorder.md
- blazor/datagrid/column-resizing.md
- blazor/datagrid/column-template.md
- blazor/datagrid/columns.md
- blazor/datagrid/foreignKey-column.md
> BLAZ-840659-Column revamp

- blazor/document-editor/how-to/insert-text-in-current-position.md
Modified a code snippet related to serialization.
> bug(854008):Modified an code snippet related to serialization

- blazor/datagrid/how-to/server-side-using-cli.md
- blazor/datagrid/how-to/using-dictionary-values-in-grid-datasource.md
- blazor/datagrid/searching.md
- blazor/gantt-chart/event-markers.md
- blazor/pdfviewer/annotation/import-export-annotation.md
- blazor/pdfviewer/opening-pdf-file.md
Hello,
I have worked on the links with redirects.
Regards,
Beryl
> SEO-175653-Links-With-Redirects-Blazor1

- blazor/visual-studio-code-integration/create-project.md
- blazor/visual-studio-integration/template-studio.md
I have Modified the UG Content
> EXT-1775 - I have modified the UG

- blazor/visual-studio-code-integration/create-project.md
- blazor/visual-studio-integration/template-studio.md
I have Modified the UG Content
> EXT-177167

- blazor-toc.html
- blazor/getting-started/blazor-web-app.md
Updated the common getting started.
> Updated the common getting started.

- blazor/getting-started/blazor-web-app.md
Updated the common getting started in Blazor UG suitable for .NET 8 web app.
> Updated the common getting started in Blazor UG suitable for .NET 8 web app.

- blazor/datagrid/how-to/display-custom-tool-tip-in-grid-cell.md
> 849678-Display-Custom-Tooltip-grid

- blazor/rich-text-editor/tools/built-in-tools.md
Hello,
I have worked on the missing image alt text.
Regards,
Beryl.
> SEO-176113-Image-Alt-Text-Blazor

- blazor-toc.html
> Navigation link updated.

- blazor/gantt-chart/frozen-columns.md
When the default frozen line is set, it does not change
Previous frozen column css classes are removed in the frozen revamp changes from grid side. So, this issue occurs.
So, I created the ticket to the grid team regarding this issue. And got solution from them and updated the solution to the gantt chart.
E2E Link: https://github.com/essential-studio/blazor-gantt-playwright-tests/blob/development/tests/Documentation/Scrolling.spec.ts
Is …
> Bug(858022):When the default frozen line is set, it does not change

- blazor/common/how-to/version-compatibility.md
Root:
Need to update .Net 8 support details in version compatibility page
Solution:
.Net 8 support details in version compatibility page has been updated
> documentation(859385): Need to update .Net 8 support details in version compatibility page

- blazor/datagrid/column-headers.md
- blazor/datagrid/column-template.md
> 859376-Column-revamp-code-correction

- blazor/common/extend-and-customize-components.md
- blazor/common/html-attributes.md
- blazor/common/input-validation.md
- blazor/context-menu/style-and-appearance.md
- blazor/datagrid/aggregates.md
- blazor/datagrid/cell.md
- blazor/datagrid/clipboard.md
- blazor/datagrid/column-validation.md
- blazor/datagrid/columns.md
- blazor/datagrid/context-menu.md
- blazor/datagrid/custom-binding.md
- blazor/datagrid/data-annotation.md
Hello,
I have worked on the links with redirects.
Regards,
Beryl
> SEO-176113-Links-With-Redirects-Blazor

- blazor/rich-text-editor/accessibility.md
- blazor/rich-text-editor/keyboard-support.md
Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions
I have ensured all the actions in the documentation and missing the audio and video shortcuts
No
No
I have updated the audio and video keyboard shortcuts in the Rich Text Editor component documentation.
Yes
No
No
No
 
/label ~bug
> bug(860373): Need to update the Keyboard shortcuts in the Rich Text Editor Documentation after ensuring all the actions - Development

- blazor/pivot-table/editing.md
- blazor/pivot-table/events.md
Need to provide UG for the "EditCompleted" event in Blazor.
> Documentation(BLAZ-856434) : To Include UG for EditCompleted event

- blazor-toc.html
- blazor/pdfviewer-2/getting-started/getting-started-webapp.md
Update the Blazor PDF Viewer (Next Gen) Component to Blazor Web App.
> Update the Blazor PDF Viewer (Next Gen) Component to Blazor Web App.

- blazor/gantt-chart/templates.md
- blazor/treegrid/templates.md
Hi @Aishwarya-Ganesan 
Fixed page not found issue links in blazor documentation pages. Please check and merge it.
Thanks,
Mallika
> SEO-178147: Page Not Found -  Blazor Coverage

- blazor/gantt-chart/events.md
Need to add new events in the gantt chart
Added the new events in the gantt chart UG documentation
Tag label `update-guideline-coreteam` or `update-guideline-productteam`.
If yes, provide the breaking commit details / MR here.
Automation details - Mark `Is Automated` field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the bug is automated.
Do the code changes cause any memory leak and performance issues? (Test only if you suspect that your code may cause problem)
> documentation(860949): GanttChart Events

- blazor-toc.html
- blazor/common/localization.md
- blazor/pdfviewer-2/getting-started/getting-started-webapp.md
Localization category updated suitable for Blazor Web App.
> Localization category updated suitable for Blazor Web App.

- blazor/pdfviewer-2/getting-started/web-app-application.md
Documentation for the mobile annotation support and the Dot Net 8 support.
* Kameshwaran Rajendran
> Feature(ES-848388): Mobile AnnotationToolbar Support

- blazor/appearance/themes.md
**Root:**
Need to provide details for overriding CSS variables of Material3 theme.
**Solution:**
The details for overriding CSS variables of Material3 theme has been provided.
> documentation(855625): Need to provide details for overriding CSS variables of Material3 theme.

- blazor/diagram/layout/radial-tree.md
Hi @Keerthivasan-Ramamoorthy sir, I have completed the UG documentation for radial tree layout support. Kindly review it.
> ES-849418-Updated content review concerns

- blazor-toc.html
Included documentation for DataForm component
> bug(BLAZ-860592): Included documentation for DataForm component

- blazor/pivot-table/pdf-export.md
Need to add UG for Table and Chart export in same PDF document.
> 862455: Added the UG for Table and Chart export in same PDF document.

- blazor/datagrid/virtualization.md
Update the UG documentation for row virtualization.
> 861794: Need to update the UG documentation for frozen, touch interaction and virtualization

- blazor-toc.html
> 857760: Gantt UG build failure

- blazor-toc.html
Resolved the toc issue for overview for DocumentEditor.
> Resolved the toc issue for overview for DocumentEditor.

- blazor/pdfviewer-2/getting-started/web-app.md
Documentation changes for web app sample with according to pdf viewer.
* Kameshwaran Rajendran
> 863141: WebAppDevelopment

- blazor/pdfviewer-2/getting-started/web-app.md
Documentation changes for web app sample with according to pdf viewer.
* Kameshwaran Rajendran
> 863141: PdfViewerWebApp

- blazor-toc.html
- blazor/document-editor/how-to/enable-ruler-in-document-editor.md
Ruler implementation documentation in Blazor
> feature(861767): Blazor Ruler Documentation

- blazor/pivot-table/pivot-chart.md
Need to update UG documentation for pivot chart.
> 826606: Updated the UG documentation for pivot chart.

- blazor/pdfviewer-2/toolbar-customization.md
- blazor/pdfviewer/toolbar-customization.md
Need to add the toolbar items inside the <PdfViewerToolbarSetting> instead of adding inside the SfPdfViewer has tToolbarSetting
> 863141: Toolbar item should be plpaced inside the PdfViewerToolbarSettings

- blazor-toc.html
- blazor/datagrid/performance.md
> documentation(blaz-0101): performance tips doc

- blazor/datagrid/getting-started.md
- blazor/getting-started/blazor-webassembly-visual-studio.md
- Added preview samples for data grid getting started and overall getting started.
> 861817: Added preview samples for getting started and datagrid.

- blazor/gantt-chart/managing-tasks.md
- blazor/gantt-chart/predecessor-validation.md
- blazor/gantt-chart/sorting.md
Changed events in Gantt Chart UG
> documentation(862436): Changed events in Gantt Chart UG

- blazor/scheduler/appointments.md
Update the restriction details about IsSlotAvailableAsync method in blazor platform
NA
NA
> ES-640354: Update the restriction details about IsSlotAvailableAsync method in blazor platform

- blazor/button/how-to/html-attribute-support.md
UG(862075): Blazor Button UG changes committed
> UG(862075): Blazor Button UG changes committed

- blazor-toc.html
- blazor/common/best-practices.md
Root:
Need to add the best-practices section to enhance the rendering performance.
Solution:
The best-practices section to enhance the rendering performance of Syncfusion Blazor app has been added.
> documentation(855627): Need to add the best-practices section to enhance the rendering performance 

- blazor-toc.html
- blazor/gantt-chart/columns.md
- blazor/gantt-chart/criticalpath.md
- blazor/gantt-chart/editing-tasks.md
- blazor/gantt-chart/resource-multi-taskbar.md
- blazor/gantt-chart/resource-view.md
- blazor/gantt-chart/row-selection.md
- blazor/gantt-chart/rows.md
- blazor/gantt-chart/state-management.md
- blazor/gantt-chart/style-and-appearance.md
- blazor/gantt-chart/taskbar.md
- blazor/gantt-chart/templates.md
- blazor/gantt-chart/touch-interaction.md
- blazor/gantt-chart/work.md
- blazor/gantt-chart/zooming.md
> 857760 : ug changes modified

- blazor/dialog/how-to/close-dialog-while-click-on-outside-of-dialog.md
Documentation(864428): Dialog issue corrected
> Documentation(864428): Dialog issue corrected 

- blazor/dialog/how-to/close-dialog-while-click-on-outside-of-dialog.md
Documentation(864428): Dialog issue corrected
> Documentation(864428): Dialog issue corrected

- blazor/datagrid/scrolling.md
To modify the CSS for changing the default frozen line color.
> To modify the CSS for changing the default frozen line color.

- blazor-toc.html
Improved the UG documentation for DataForm component
> 865176: Improved the UG documentation for DataForm component

- blazor/datagrid/events.md
- blazor/datagrid/sorting.md
Sorting-revamp-documentation(839494)
> Sorting-revamp-documentation(839494)

- blazor-toc.html
- blazor/introduction.md
Hi @sarathkumarvenkatesan ,
Updated the diagram navigation link in introduction page of the blazor documentation.
Regards,
Suganthi K.
> 849390: Update the documentation for diagram

- blazor/dialog/how-to/close-dialog-while-click-on-outside-of-dialog.md
Resolved conflict due to dialog component
> 865176: Resolve conflict due to dialog component

- blazor/rich-text-editor/inline-mode.md
- blazor/splitter/resizing.md
- blazor/treemap/data-binding.md
Have changed Page with Redirect links.
Regards,
Yvone.
> SEO-178567 Blazor Page with Redirect UG

- blazor/rich-text-editor/how-to/blazor-web-assembly.md
- blazor/smith-chart/smith-chart-series.md
Have changed Page with Redirect UG.
Regards,
Yvone.
> SEO-178903 Blazor page with redirect links

- blazor/data/adaptors.md
- blazor/datagrid/data-binding.md
- blazor/datagrid/how-to/grid-customization.md
Hello,
I have worked on links with redirects.
Kind regards,
Beryl.
> SEO-178943-Links-With-Redirects-Blazor

- blazor-toc.html
- blazor/query-builder/how-to/gets-filtered-records.md
- blazor/query-builder/import-export.md
Adding the gets filtered data source from query builder sample.
> 862368: Adding the gets filtered data source from query builder sample.

- blazor/dropdown-tree/data-binding.md
- blazor/dropdown-tree/filtering.md
Added the missing topics in Databinding
> 831195: Added the Databinding expando topics.

- blazor/data-form/events.md
Resolved build failure in Blazor UG docs
> 865176: Resolved build failure in Blazor UG docs

- blazor/datagrid/foreignKey-column.md
Documentation(866253)Foreign-key-with-remote-data
> Documentation(866253)Foreign-key-with-remote-data

- blazor/autocomplete/value-binding.md
- blazor/dropdown-list/code-snippet/value-binding/primitive-type-int.razor
- blazor/dropdown-list/value-binding.md
AutoComplete Value Binding formatting issues resolved.
> 865176: AutoComplete Value Binding formatting issues resolved.

- blazor/common/cdn-fallback.md
- blazor/common/content-security-policy.md
cdn-fallback.md and content-security-policy.md updated suitable for Blazor Web App.
> cdn-fallback.md and content-security-policy.md updated.

- blazor/appearance/themes.md
- blazor/common/cdn-fallback.md
- blazor/common/content-security-policy.md
- blazor/common/localization.md
> 864124: stylesheet heading updated.

- blazor/dropdown-tree/accessibility.md
- blazor/dropdown-tree/checkbox.md
- blazor/dropdown-tree/filtering.md
- blazor/dropdown-tree/selection.md
- blazor/dropdown-tree/sorting.md
- blazor/dropdown-tree/templates.md
Hi @Gowri-V-L 
Kindly review the PR below.
Regards 
Dickson J
> SEO-174657-Blazor-Dropdown-Tree

- blazor/dropdown-tree/data-binding.md
- blazor/dropdown-tree/filtering.md
Added the missing topics in Databinding
> 831195: Added the Entity framework sample.

- blazor/datagrid/columns.md
Documentation Gridcolumn Date formatting
> Documentation Gridcolumn Date formatting

- blazor-toc.html
Added title for blazor media query subtopics.
> documentation(855861): Added title for blazor media query.

- blazor/appearance/themes.md
> 864124: Need to resolve the Alignment issue.

- blazor/file-upload/how-to/how-to-prevent-to-upload-or-remove-upload-file.md
Addressed the documentation correction in uploader component
> Bug(BLAZ-869848) : Addressed the documentation correction in uploader component

- blazor/datagrid/templates.md
- blazor/pivot-table/events.md
Hi @Aishwarya-Ganesan , 
I have changed redirection links, please review.
Regards,
Scholar.
> SEO-179789-Blazor-Page-With-Redirect

- blazor/diagram/print.md
- blazor/gantt-chart/selection.md
- blazor/in-place-editor/configuration.md
- blazor/timepicker/events.md
Please review the changes.
Thanks.
Regards,
Edith.
> SEO-179251-blazor-page-with-redirects

- blazor/accumulation-chart/getting-started-with-web-app.md
- blazor/datagrid/how-to/tool-bar-with-drop-down-list.md
- blazor/diagram/print.md
- blazor/gantt-chart/selection.md
- blazor/timepicker/events.md
Hi @MallikaRK 
Kindly review my PR below
Regards, 
Dickson J
> SEO-174654-Blazor-UG-Page-With-Redirect

- blazor/data/custom-binding.md
- blazor/diagram-classic/howTo/blazor-web-assembly-diagram.md
Hi @MallikaRK
Kindly review my PR below
Regards,
Dickson J
> SEO-174654-Blazor-UG-Page

- blazor/datepicker/events.md
- blazor/input-mask/mask-configuration.md
- blazor/treegrid/sorting.md
Hi @MallikaRK,
Worked on blazor page with redirect.
Regards,
Sharly A.
> SEO-179773-Blazor-docs-changes

- blazor/calendar/events.md
- blazor/chart/events.md
Hi @MallikaRK,
Worked on blazor page with redirect.
Regards,
Sharly A.
> SEO-179773-Blazor-events-changes

- blazor/datagrid/data-binding.md
UG Documentaion for the DataTable binding support
> 855462: UG Documentaion for the DataTable binding support

- blazor/datagrid/row-drag-and-drop.md
Updated the limitation for row drag and drop with grouping feature.
> 851375: Added documentation for row drag and drop with grouping feature.

- blazor/getting-started/blazor-web-app.md
- Need to Resolve the build failure.
> 867132: Update blazor-web-app.md

- blazor/gantt-chart/split-task.md
SplitTask support in Gantt Chart.
Attached is the task.
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/840531
[Provide task link.](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/840288)
Feature matrix document updated against this feature and committed in this [common location] [(https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . ](https://syncfusion.sharepoint.com/:x:/r/sites/Blazor/Shared%20Documents/Components/Gantt%20Chart/Feature%20Matrix-Blazor-Gantt%20Chart.xlsx?d=wee3af9dbb4414f98b96369632d87837e&csf=1&web=1&e=NSep3J)
Provide the details about the areas or …
> 865035: Gantt

- blazor/gantt-chart/split-task.md
SplitTask support in Gantt Chart.
Attached is the task.
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/840531
[Provide task link.](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/840288)
Feature matrix document updated against this feature and committed in this [common location] [(https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . ](https://syncfusion.sharepoint.com/:x:/r/sites/Blazor/Shared%20Documents/Components/Gantt%20Chart/Feature%20Matrix-Blazor-Gantt%20Chart.xlsx?d=wee3af9dbb4414f98b96369632d87837e&csf=1&web=1&e=NSep3J)
Provide the details about the areas or …
> 865032: SplitTask

- blazor/gantt-chart/split-task.md
SplitTask support in Gantt Chart.
Attached is the task.
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/840531
[Provide task link.](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/840288)
Feature matrix document updated against this feature and committed in this [common location] [(https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . ](https://syncfusion.sharepoint.com/:x:/r/sites/Blazor/Shared%20Documents/Components/Gantt%20Chart/Feature%20Matrix-Blazor-Gantt%20Chart.xlsx?d=wee3af9dbb4414f98b96369632d87837e&csf=1&web=1&e=NSep3J)
Provide the details about the areas or …
> 865035: Segment

- blazor/scheduler/cell-customization.md
**Description**:
Added the topic for weekend cell customization in Scheduler
**Areas affected and ensured**:
Cell Customizations
**Test cases**:
NA
**Test bed sample location**:
NA
**Additional checklist**:
> Documentation(ES-379228): Added the topic for weekend cell customization in Scheduler

- blazor/color-picker/localization.md
Please review the changes made
Thanks.
Regards,
Edith.
> SEO-179251-blazor-page-with-redirect

- blazor/Release-Notes/20.1.47.md
- blazor/treegrid/data-binding.md
Hi @MallikaRK,
Worked on page with redirect for blazor.
Regards
Sharly A.
> SEO-179773-Blazor-docs-int

- blazor/common/how-to/upgrade-syncfusion-components-to-latest-version.md
I have updated the HTTP issues, please review on the same.
Regards,
Jeffrey
> Updated HTTP issues

- blazor/gantt-chart/accessibility.md
Accessibility UG content need to modified
Accessibility UG content for Gantt Chart is out dated 
Updated Accessibility UG content for Gantt Chart with proper content and links
Post the output …
> 871865: Changed Gantt Accessibility UG

- blazor/datagrid/accessibility.md
Updated the content for blazor grid accessibility
> 845328: Update accessibility.md

- blazor/gantt-chart/scheduling-tasks.md
Task mode column is not updating while editing cell
Different type is used of IsManual field
Changed the type of IsManual to bool.
Post the output screenshots if an UI is affected or added due …
> 871848: Changed string to boolean type in task mode

- blazor/badge/getting-started.md
documentation(ES-387205): Added Blazor Badge getting-started youtube video.
> documentation(ES-387205): Added Blazor Badge getting-started youtube video.

- blazor/gantt-chart/accessibility.md
Accessibility UG sample link need to be added
Accessibility UG sample link not provided 
Added sample link for Accessibility UG
Post the output screenshots if an UI is affected or added due to …
> 871865: Added sample link for Accessibility UG

- blazor/treegrid/accessibility.md
Have updated the preview sample links
> 872092: updated sample links

- blazor-toc.html
- blazor/pivot-table/performance-best-practices.md
To update the content of the best practices for improving the performance of the Pivot Table
> 868619: To update the content of the best practices for improving the performance of the Pivot Table

- blazor/query-builder/data-binding.md
- blazor/scheduler/header-bar.md
I have worked on links with redirects.
Kind Regards,
Beryl.
> SEO-180457-Redirect-Links-Blazor

- blazor/common/accessibility.md
In this PR, we have updated the common accessibility md file.
> 845328: Commit for update the accessibility testing tool name

- blazor/gantt-chart/globalization.md
Need to make correction Localization values in Dutch resource file
The german localization words are not handled properly.
Modified the german localization of words properly in SfResoruce.de.resx file.
Is this common issue need to be addressed in the same component or on other components in our …
> 873086: Resources

- blazor-toc.html
- blazor/breadcrumb/accessibility.md
- blazor/button-group/accessibility.md
- blazor/button/accessibility.md
- blazor/color-picker/accessibility.md
- blazor/context-menu/accessibility.md
- blazor/drop-down-menu/accessibility.md
- blazor/image-editor/accessibility.md
- blazor/listbox/accessibility.md
- blazor/menu-bar/accessibility.md
- blazor/progress-button/accessibility.md
- blazor/query-builder/accessibility.md
- blazor/radio-button/accessibility.md
- blazor/signature/accessibility.md
- blazor/split-button/accessibility.md
- blazor/toggle-switch-button/accessibility.md
864907: New Accessibility ug sample for blazor tools component
[Task 874368](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/874368): New Accessibility ug sample for blazor tools component
[Task 874368](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/874368): New Accessibility ug sample for blazor tools component
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this …
> 864907: New Accessibility ug sample for blazor tools component

- blazor/gantt-chart/resource-multi-taskbar.md
- blazor/gantt-chart/resource-view.md
Resolved custom column displayed in Resourceview SB sample
> 874458: Custom column displayed in Resourceview SB sample

- blazor/appbar/design.md
UG(ES-874669): Removing Bootstrap Dependency for Syncfusion controls.
URL: https://blazor.syncfusion.com/documentation/appbar/design#designing-appbar-with-sidebar
> 874669: Removing Bootstrap Dependency for Syncfusion controls

- blazor/data-form/validation.md
Added information on installing the Blazored.FluentValidation NuGet package in Dataform Fluent Validation Sample
> Documentation(BLAZ-872098): Added information on installing the FluentValidation NuGet package.

- blazor/datagrid/connecting-to-database/mysql-server.md
MYSQL-Data-Binding-Documentation(871699)
> MYSQL-Data-Binding-Documentation(871699)

- blazor/datagrid/accessibility.md
Updated the UG documentation for keyboard navigation topic.
> 876120: Need to updated keyboard navigation sample in UG documentation.

- blazor/autocomplete/virtualization.md
- blazor/combobox/virtualization.md
- blazor/dropdown-list/code-snippet/virtualization/group.razor
- blazor/dropdown-list/virtualization.md
Need to update the documentation for virtualscroll in multiselect and object value binding
NA
Updated the documentaion 
- Checked with fix component behavior
* []  Yes, Tag `breaking-issue`. 
NA
NA
Confirm whether this feature is ensured in both Blazor Server and WASM
Is there any new API or existing API name change?
Do the code …
> 875674: Need to update the documentation for virtualscroll in multiselect and object value binding

- blazor-toc.html
- blazor/dashboard-layout/state-persistence.md
I have added the EnablePersistence topic in the Blazor Dashboard Layout documentation.
> Documentation(ES-876264): Need to add the EnablePersistence topic in the Blazor Dashboard Layout documentation. 

- blazor/file-manager/file-operations.md
Added user guide documentation for SortComparer property in Blazor File Manager component.
> 871488: Added user guide documentation for SortComparer property in Blazor File Manager component.

- blazor/pdfviewer-2/toolbar-customization.md
Update the Code changes in the Toolbar customization page in the Blazor docs
> 873999: Update the Code Changes in the Toolbar customization Page

- blazor/pdfviewer-2/toolbar-customization.md
Updated the code changes in the Toolbar customization page in documentation
> 873999: Update the code changes in the toolbar customization

- blazor/image-editor/annotation.md
Added additional parameters in Image Editor Annotations public methods in all platforms
- Ellipse
- Rectangle
- Line
- Arrow
- Path
- Text
- Image
> 876447: Added additional parameters in Image Editor Annotations public methods

- blazor/data-form/data-annotation-attributes.md
Document the DataAttributes and Floating label features of DataForm component
> 875918: Document the DataAttributes and Floating label features of DataForm component

- blazor/dropdown-tree/data-binding.md
- blazor/dropdown-tree/style.md
- blazor/dropdown-tree/templates.md
874005: Corrections-Add UG document for Dropdown Tree in Blazor.
> 874005: Corrections-Add UG document for Dropdown Tree in Blazor.

- blazor/pivot-table/excel-export.md
- blazor/pivot-table/pivot-chart.md
Add the UG Documentation for combined multiple axis mode and ExportAllPages.
> 875842: Add the UG Documentation for combined multiple axis mode and ExportAllPages.

- blazor/pivot-table/excel-export.md
- blazor/pivot-table/pivot-chart.md
Add the UG Documentation for combined multiple axis mode and ExportAllPages
> 875842: Add the UG Documentation for combined multiple axis mode and ExportAllPages in hotfix is completed

- blazor-toc.html
- blazor/file-upload/how-to/how-to-prevent-to-upload-or-remove-upload-file.md
- blazor/file-upload/how-to/html-attributes.md
- blazor/file-upload/template.md
- blazor/file-upload/validation.md
877017: Changed service URL links for Input and dropdown components documentations.
> 877017: Changed service URL links for Input and dropdown components documentations.

- blazor/pdfviewer-2/command-manager.md
- blazor/pdfviewer-2/events.md
- blazor/pdfviewer-2/magnification.md
- blazor/pdfviewer-2/toolbar-customization.md
Updated the documentation links in SfPdfViewer
> 876920: Updated the documentation links

- blazor/gantt-chart/accessibility.md
- blazor/treegrid/accessibility.md
Need to update the Accessibility document section for following Blazor component refer by EJ2 [gantt](https://ej2.syncfusion.com/javascript/documentation/gantt/accessibility) document.
* Gantt Chart
* Tree grid
_NA_
Updated the Accessibility document section in Blazor UG refer by EJ2 [gantt](https://ej2.syncfusion.com/javascript/documentation/gantt/accessibility) document.
Automation details - Mark `Is Automated` field as (Yes, Manual, Not Applicable) in corresponding JIRA task once …
> 877422: Accessibility document updated in Blazor gantt UG.

- blazor/timeline/align.md
- blazor/timeline/events.md
- blazor/timeline/items.md
- blazor/timeline/orientations.md
- blazor/timeline/reverse.md
- blazor/timeline/template.md
Need to map API link to the timeline property.
> UG(875578): Need to Map API link to the timeline property.

- blazor-toc.html
- blazor/datagrid/connecting-to-database/postgresql-server.md
PostgreSQL-DataBinding-Documentation(872737)
> PostgreSQL-DataBinding-Documentation(872737)

- blazor/file-manager/file-operations.md
Added user guide documentation for SortComparer property in Blazor File Manager component.
> 869321: Added user guide documentation for SortComparer property in Blazor File Manager component.

- blazor-toc.html
- blazor/autocomplete/accessibility.md
- blazor/calendar/accessibility.md
- blazor/combobox/accessibility.md
- blazor/datepicker/accessibility.md
- blazor/daterangepicker/accessibility.md
- blazor/datetime-picker/accessibility.md
- blazor/dialog/accessibility.md
- blazor/dropdown-list/accessibility.md
- blazor/file-upload/accessibility.md
- blazor/in-place-editor/accessibility.md
- blazor/input-mask/accessibility.md
- blazor/mention/accessibility.md
- blazor/multiselect-dropdown/accessibility.md
- blazor/numeric-textbox/accessibility.md
- blazor/splitter/accessibility.md
- blazor/textbox/accessibility.md
- blazor/timepicker/accessibility.md
- blazor/toast/accessibility.md
877603: Need to update accessibility document
> 877603: Need to update accessibility document

- blazor/breadcrumb/accessibility.md
- blazor/button-group/accessibility.md
- blazor/button/accessibility.md
- blazor/check-box/accessibility.md
- blazor/color-picker/accessibility.md
- blazor/context-menu/accessibility.md
- blazor/drop-down-menu/accessibility.md
- blazor/image-editor/accessibility.md
- blazor/listbox/accessibility.md
- blazor/menu-bar/accessibility.md
- blazor/progress-button/accessibility.md
- blazor/query-builder/accessibility.md
- blazor/radio-button/accessibility.md
- blazor/split-button/accessibility.md
- blazor/toggle-switch-button/accessibility.md
Need to update the Accessibility document section for following Blazor component refer by EJ2 document.
* Skeleton
* Speed dial
* Stepper
* BreadCrumb
* Button group
* Buttons
* Checkbox
* Color picker
* Context menu
* Dropdown Menu
* Image editor
* List Box
* Menu Bar
* Progress button
* Query builder
* Radio Button
* Signature
* Split button
* Toggle switch button
_NA_
Updated the Accessibility document section in Blazor UG refer by EJ2  document.
Automation details - Mark `Is …
> 877422 : Accessibility document updated

- blazor/diagram/accessibility.md
Need to update the Accessibility document section for following Blazor component refer by EJ2 document.
* Diagram
_NA_
Updated the Accessibility document section in Blazor UG refer by EJ2  document.
Is this common issue need to be addressed in the same component or on other components in our …
> 877422: Accessibility document updated.

- blazor/file-manager/file-operations.md
- blazor/file-manager/flat-data.md
Resolved UG corrections in File Manager component SortComparer and FlatData.
> 869321: Resolved UG corrections in File Manager component SortComparer and FlatData.

- blazor-toc.html
- blazor/getting-started/blazor-web-app-linux.md
Need to draft Getting Started UG for Blazor WebApp Linux
If there is an external design, link to its project documentation area.
The Getting Started UG for Blazor WebApp Linux draft was prepared.
Post the output screenshots if an UI is affected or added due to this feature.
Added:
Changed:
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the …
> 863486: Need to draft Getting Started UG for Blazor WebApp - Linux

- blazor/query-builder/clone-group-rule.md
- blazor/query-builder/import-export.md
- blazor/query-builder/lock-group-rule.md
Modify Querybuilder UG Content for Import-Export, Lock and CIone Samples
> 878261: Modify Querybuilder UG Content for Import-Export, Lock and CIone Samples

- blazor/diagram/accessibility.md
Need to update the Accessibility document section for following Blazor component refer by EJ2 document.
* Diagram
_NA_
Updated the Accessibility document section in Blazor UG refer by EJ2  document.
Is this common issue need to be addressed in the same component or on other components in our …
> 878635: Accessibility document updated.

- blazor-toc.html
Resolved file path validation failures occurs from this PR https://github.com/syncfusion-content/blazor-docs/pull/4189
> 876873: Resolved file path validation failures

- blazor/image-editor/filter.md
- blazor/image-editor/finetune.md
Added note content for filter and finetuning limitation in iOS.
> 871837: filter and finetune limitation

- blazor/autocomplete/accessibility.md
- blazor/calendar/accessibility.md
- blazor/combobox/accessibility.md
- blazor/datepicker/accessibility.md
- blazor/daterangepicker/accessibility.md
- blazor/datetime-picker/accessibility.md
- blazor/dialog/accessibility.md
- blazor/dropdown-list/accessibility.md
- blazor/file-upload/accessibility.md
- blazor/in-place-editor/accessibility.md
- blazor/input-mask/accessibility.md
- blazor/mention/accessibility.md
- blazor/multiselect-dropdown/accessibility.md
- blazor/numeric-textbox/accessibility.md
- blazor/splitter/accessibility.md
- blazor/textbox/accessibility.md
- blazor/timepicker/accessibility.md
- blazor/toast/accessibility.md
I modified the Accessibility UG documentation for Blazor components. The components list is given below,
1. AutoComplete
2. Calendar
3. Card
4. ComboBox
5. DatePicker
6. DateRangePicker
7. DateTimePicker
8. Dialog
9. DropDownList
10. File Upload
11. In-place Editor
12. Input Mask
13. Mention
14. MultiSelect Dropdown
15. NumericTextBox
16. Predefined Dialogs
17. Spinner
18. Splitter
19. TextBox
20. TimePicker
21. Toast
> Modified Accessibility UG documentation for Blazor components

- blazor/accumulation-chart/accessibility.md
- blazor/bullet-chart/accessibility.md
- blazor/chart/accessibility.md
- blazor/progress-bar/accessibility.md
- blazor/range-selector/accessibility.md
- blazor/smith-chart/accessibility.md
- blazor/sparkline/accessibility.md
- blazor/stock-chart/accessibility.md
Changed the casing in Chart, Bullet Chart, Accumulation chart, Range Navigator, Sparkline, Smith chart and stock chart in accessibility pages.
> 872993: Added UG for accessibility to all chart controls(hotfix).

- blazor/accumulation-chart/accessibility.md
- blazor/bullet-chart/accessibility.md
- blazor/chart/accessibility.md
- blazor/progress-bar/accessibility.md
- blazor/range-selector/accessibility.md
- blazor/smith-chart/accessibility.md
- blazor/sparkline/accessibility.md
- blazor/stock-chart/accessibility.md
Changed the casing in Chart, Bullet Chart, Accumulation chart, Range Navigator, Sparkline, Smith chart and stock chart in accessibility pages.
> 872993: Added UG for accessibility to all chart controls(dev).

- blazor/query-builder/clone-group-rule.md
- blazor/query-builder/import-export.md
- blazor/query-builder/lock-group-rule.md
Modified Querybuilder UG API links
> 878261: Modified Querybuilder UG API links

- blazor-toc.html
Added the How to improve performance using CDN topic in how to section of doc
> 878343: how to topic for "How to improve performance using CDN"

- blazor/toolbar/item-configuration.md
**Description**:
Draft UG for spacer support in Blazor toolbar.
**Areas affected and ensured**:
Added the new topic for aligning items using spacer support in toolbar.
**Output**:
NA
**Test cases**:
NA
**Test bed sample location**:
NA
**Additional checklist**:
> 876873: Added the missed topic in UG for blazor toolbar spacer support

- blazor/browser-support.md
- blazor/introduction.md
I removed opera browser and modular details in Blazor common UG documentation.
> Removed Opera and modular detail in Blazor common UG documentation

- blazor/document-editor/accessibility.md
Update accessibility documentation
> Update accessibility documentation

- blazor/pdfviewer-2/how-to/change-the-highlighted-color-of-the-text.md
- blazor/pdfviewer-2/how-to/print-the-sfpdfiewer-inside-the-dialog-component.md
Hi @MallikaRK 
Kindly review my PR below.
Regards
Dickson J
> SEO-174654-Blazor-Title-to-long

- blazor/datagrid/searching.md
Documentation(880906)Clear Searching
> Documentation(880906)Clear Searching

- blazor/kanban/accessibility.md
- blazor/rich-text-editor/accessibility.md
I modified the Accessibility UG documentation for Blazor components. The components list is given below,
1. Kanban
2. RichTextEditor
> Update the Accessibility documentation for Blazor components

- blazor-toc.html
- blazor/floating-action-button/accessibility.md
- blazor/rating/accessibility.md
- blazor/skeleton/accessibility.md
- blazor/speeddial/accessibility.md
- blazor/timeline/accessibility.md
Need to update the Accessibility document section for following Blazor component refer by EJ2 document.
* Rating
* Skeleton
* Stepper
* Floating action button
* Speed Dial
* Timeline
_NA_
Updated the Accessibility document section in Blazor UG refer by EJ2  document.
Is this common issue need to …
> documentation(877422): Accessibility document updated.

- blazor/document-editor/track-changes.md
Added documentation for toggle track pane in track-changes.md file .
> 380577: Added documentation for toggle track pane

- blazor/file-upload/how-to/getting-started-with-blazor-webassembly.md
Provide support for catch the returned response body in uploader component.
- https://dev.azure.com/EssentialStudio/b6db0cd2-2cc5-4f25-849c-c7a027012a1a/_apis/wit/attachments/9feb4c86-5abf-4dc0-8193-6899a5aa488a?fileName=Specification%20Document%20-%20Support%20for%20Returning%20Response%20Body%20Syncfusion%20JavaScript%20File%20Upload%20Component.docx&download=true&api-version=5.0-preview.2
- https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/83631
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Docu …
> 83631: Provide support for catch the returned response body in uploader component

- blazor/kanban/style.md
- blazor/range-selector/grid-tick.md
- blazor/scheduler/working-hours.md
Hi @gowthamanthavasiyappan,
Worked on blazor control changes.
Regards,
Sharly A.
> SEO-182342-Coverage-issue-fixes-blazor

- blazor/common/how-to/port-blazor-server-maui.md
Need to resolve the alignment issue in the following UG link:
https://sfblazor.azurewebsites.net/staging/documentation/common/how-to/port-blazor-server-maui
> 854312: alignment issue resolved

- blazor/common/custom-resource-generator.md
Need to updated UG content in Blazor Custome Resource Generator(CRG)
> 883511: CRG UG content updated

- blazor/common/localization.md
I cleared the code syntax issues in Localization documentation of Blazor.
> Cleared code syntax error

- blazor/chart/selection.md
- blazor/chart/zooming.md
Added a note for performing rectangular selection in zooming and selection page.
> documentation(885085): To add double tap functionality details of device in selection

- blazor/datagrid/filter-menu.md
Need-correct-names-filter-operators(884871)
> Need-correct-names-filter-operators(884871)

- blazor/splitter/pane-content.md
In splitter component ,Html heading and text area differs and not showing properly.
- The issue of HTML markup  headings not displaying properly and text areas appearing differently arises from recent code alterations in the splitter component. It appears that the splitter component is unable to render HTML content provided as a string.
- The issue has been resolved by directly providing HTML content within the splitter component, eliminating , the need to construct HTML content as a string variable. As a result, the component now functions correctly.
- Due to CSP/XSS violations in the Blazor Forms component. We have to  Removed the MarkupString type from the content property to only set string values as content.
- …
> 880589:  Html mark string heading not showing and text differs 

- blazor/splitter/pane-content.md
In splitter component ,Html heading and text area differs and not showing properly.
- The issue of HTML markup  headings not displaying properly and text areas appearing differently arises from recent code alterations in the splitter component. It appears that the splitter component is unable to render HTML content provided as a string.
- The issue has been resolved by directly providing HTML content within the splitter component, eliminating , the need to construct HTML content as a string variable. As a result, the component now functions correctly.
- Due to CSP/XSS violations in the Blazor Forms component. We have to  Removed the MarkupString type from the content property to only set string values as content.
- …
> 880589: Html mark string heading not showing and text differs 

- blazor/pdfviewer-2/open-pdf-file/from-amazon-s3.md
- blazor/pdfviewer-2/save-pdf-file/to-azure-blob-storage.md
Updated the  SfPdfViewer2 instance name properly in the open pdf from the Amazon s3 md file
> 885174:  Updated the  SfPdfViewer2 instance name properly

- blazor/common/localization.md
Added Syncfusion Blazor Localization User Guide for Blazor Web App for Server.
> 880725: Modified Syncfusion Blazor Localization UG for Blazor Web App

- blazor-toc.html
Provided the wrong toc for save from different platforms so updated those properly in this pr
> 885174: Updated the SfPdfViewer2 mismatched TOC

- blazor/common/localization.md
Added Syncfusion Blazor Localization User Guide for Blazor Web App for Server.
> 881050: Update localization.md

- blazor/treegrid/data-binding.md
Changed service link in remote samples.
> 887205: Changed service link in Blazor documentation

- blazor-toc.html
- blazor/pdfviewer-2/open-pdf-file/from-amazon-s3.md
- blazor/pdfviewer-2/save-pdf-file/to-azure-blob-storage.md
- blazor/pdfviewer-2/save-pdf-file/to-google-cloud-storage.md
Provided the wrong toc for save from different platforms so updated those properly in this pr
> 885174: Updated the SfPdfViewer2 mismatched TOC 

- blazor/datagrid/data-binding.md
- blazor/datagrid/events.md
Service Url changes for the web api adaptors for the UG grid samples
> 887711: Service URL changes for Api adaptors

- blazor/appearance/icons.md
Need to improve the UG section for "Third party icons integration" in Blazor
> 887509: improved UG for third party icons integration

- blazor/file-manager/file-system-provider.md
- blazor/file-manager/getting-started-with-web-app.md
- blazor/file-manager/getting-started.md
Clearly and concisely describe the problem (this cannot be empty).
Briefly describe the root cause and analysis of the problem.
Describe the changes made in the code in detail for the reviewers.
Is this common issue need to be …
> 890059: Modified the getting started

- blazor/data/adaptors.md
- blazor/data/how-to/adding-custom-headers.md
Service Url changes for the web api adaptors for the UG data manager samples
> 887711: Service URL changes for Api adaptors 

- blazor/common/accessibility.md
Added all chart controls accessibility Page link in Common Accessibility file
> 886712: Added all chart controls accessibility Page link in Common Accessibility file(dev)

- blazor/pivot-table/sorting.md
Removed the note from sorting.
> 889142: Removed the note from sorting.

- blazor/skeleton/accessibility.md
- blazor/timeline/accessibility.md
Need to update accessibility content for timeline and skeleton..
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
Provide the test …
> UG(885110): Need to update accessibility content for timeline and skeleton.

- blazor/accordion/accessibility.md
- blazor/appbar/accessibility.md
- blazor/carousel/accessibility.md
- blazor/scheduler/accessibility.md
- blazor/tabs/accessibility.md
- blazor/toolbar/accessibility.md
Missed accessibility columns updated for Accordion, AppBar, Carousel, Scheduler, Tabs and Toolbar.
NA
- Specification document
- Common guidelines / Core team guideline
- Specification document
- Requirement document
NA
NA
NA
NA
No
NA
NA
This may vary for different teams or products. Check with your scrum masters.
- Did you run the automation against your fix? No
- Is there any API name change? NO
- Is there any existing behavior change of other features due to this code change? NO
- Does your new code introduce new warnings or binding errors? No
- Does your code pass all FxCop and StyleCop rules? Not applicable
- Did you record this case …
> 890780: Accessibility support table updated for Accordion, AppBar, Carousel, Scheduler, Tabs and Toolbar.

- blazor/diagram/constraints.md
- blazor/diagram/data-binding.md
- blazor/diagram/getting-started-with-maui-app.md
- blazor/diagram/layout/complex-hierarchical-layout.md
- blazor/diagram/layout/hierarchical-layout.md
- blazor/diagram/layout/mind-map.md
- blazor/diagram/layout/organizational-chart.md
- blazor/diagram/layout/radial-tree.md
I have added UG content for parent child relationship. Could you please review this PR?
Regards,
Sumathi U.
> 876429: Need to provide parent child relationship details in UG

- blazor/maps/internationalization.md
- blazor/maps/maps-event.md
- blazor/maps/markers.md
- blazor/maps/print-and-export.md
- blazor/maps/providers/azure-maps.md
- blazor/maps/providers/bing-maps.md
- blazor/maps/providers/openstreetmap.md
- blazor/maps/providers/other-maps.md
- blazor/maps/user-interactions.md
layerType API is no longer supported in the maps and include a duration property in the tooltip settings.
Need to remove the layerType property reference from the UG documentation.
Removed the layerType API and include a content for the duration property in the tooltip settings.
Ensured in the components.
Is this common issue need to be …
> 889448: Removed the deprecated APIs from the maps UG documentation.

- blazor/multiselect-dropdown/virtualization.md
Need to update the documentation for blazor multiselect component 
NA
we have added documentation for mutiselect virtualization in blazor.
- Checked with fix component behavior
* []  Yes, Tag `breaking-issue`. 
NA
NA
Confirm whether this feature is ensured in both Blazor Server and WASM
Is there any new API or existing API name change?
Is there any existing behavior change due to this code …
> 887665: updated the virtualization sample

- blazor/textarea/form-support.md
- blazor/textarea/styles-appearance.md
Need to update the documentation updated for textarea component.
NA
we have added documentation updated for textarea component.
- Checked with fix component behavior
* []  Yes, Tag `breaking-issue`. 
NA
NA
Confirm whether this feature is ensured in both Blazor Server and WASM
Is there any new API or existing API name change?
Do …
> 884601: documentation updated for textarea component.

- blazor/file-upload/getting-started.md
Need to add the client side response in uploader component documentation
- https://dev.azure.com/EssentialStudio/b6db0cd2-2cc5-4f25-849c-c7a027012a1a/_apis/wit/attachments/9feb4c86-5abf-4dc0-8193-6899a5aa488a?fileName=Specification%20Document%20-%20Support%20for%20Returning%20Response%20Body%20Syncfusion%20JavaScript%20File%20Upload%20Component.docx&download=true&api-version=5.0-preview.2
- https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/83631
Feature matrix document updated against this feature and committed in this [common location] (https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documen …
> 891182: Need to add the client side response in uploader component documentation

- blazor/listbox/selection.md
Listbox Selection sample not working in ug docs
Showcheckbox property was not declared so checkbox not rendered
added showCheckBox propert to the selection sample
Post the output screenshots …
> 890467: Listbox Selection sample not working in ug docs #

- blazor/listbox/selection.md
890467: Listbox Selection sample not working in ug docs
> 890467: Listbox Selection sample not working in ug docs

- blazor/treegrid/getting-started-webapp.md
Added Documentation For Handling Exceptions 
Spec document 
Task link :https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/890741
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/883352
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases. …
> 890741: Ug Doc Sample

- blazor/rich-text-editor/getting-started-webapp.md
- blazor/rich-text-editor/getting-started.md
To update documentation for the getting started page for Rich text editor component for all platform
Changed the documentation for the getting started page for Rich text editor component for all platform
> 890672: To update documentation for the getting started page for Rich text editor component for all platform

- blazor/treegrid/getting-started.md
Added Documentation For Handling Exceptions 
Spec document 
Task link :https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/890741
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/883352
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and worst-case test-cases. …
> 890741: Ug Server

- blazor/treeview/virtualization.md
Modified the content of TreeView Virtualization.
> 889256: modified the Virtualization documentation for TreeView.

- blazor/common/accessibility.md
Add missed accessibility links
> 892200: Update accessibility.md

- blazor/rich-text-editor/getting-started-webapp.md
- blazor/rich-text-editor/getting-started.md
To update documentation for the getting started in the Rich Text Editor for Blazor patform
No
No
No
No
No
No
/label ~bug
> 891405: To update the getting started documentation page in the Rich text editor component in Blazor platform

- blazor/range-slider/accessibility.md
Need to update empty cells in Blazor Slider UG documentation.
NA
I have updated empty cells in Blazor Slider UG documentation.
Confirm whether this feature is ensured in both Blazor Server and …
> 890756: Need to update empty cells in Blazor UG documentation.

- blazor/button-group/getting-started.md
- blazor/combobox/getting-started-with-web-app.md
- blazor/menu-bar/getting-started-webapp.md
- blazor/visual-studio-code-integration/convert-project.md
Hi @gowthamanthavasiyappan 
Kindly review my PR below.
Regards 
Dickson J
> SEO-174654-Blazor-Page-With-Redirect-1

- blazor/chart/tool-tip.md
- blazor/progress-button/how-to/hide-spinner.md
Hi @gowthamanthavasiyappan 
Kindly review my PR below.
Regards
Dickson J
> SEO-174654-Blazor-Page-With-Redirect-2

- blazor/timeline/accessibility.md
Need to update accessibility content for timeline and skeleton..
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
Provide the test …
> UG(885110): Updated accessibility content for timeline.

- blazor/media-query/break-points.md
Need to update the media query UG custom-media-breakpoints section
None
NA
NA
> docs(893176): custom-media-breakpoints code section updated

- blazor/listview/virtualization.md
Need to update the ListView Virtualization limitations.
NA
None
NA
NA
> docs(893473): ListView Virtualization limitations are updated.

- blazor/toast/accessibility.md
893672: Changed Accessibility support as N/A.
> 893672: Changed Accessibility support as N/A.

- blazor/common/accessibility.md
Need to resolve the icon is not rendering issue in the Common accessibility page
Need to resolve the icon is not rendering issue in the Common accessibility page
**Reason:**
Is there any other related areas also to be addressed?
If it is a breaking issue, …
> 889622: Need to resolve the icon is not rendering issue in the Common accessibility page

- blazor/document-editor/getting-started/web-app.md
> Updated the note section.

- blazor/document-editor/getting-started/web-app.md
> Updated the notes section.

- blazor/file-upload/chunk-upload.md
- blazor/file-upload/getting-started-with-web-app.md
- blazor/file-upload/getting-started.md
[UG documentation 888247](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/888247): Corrected "Controller Save and remove method"
> 888247: Corrected "Controller Save and remove method"

- blazor/pdfviewer-2/events.md
- blazor/pdfviewer-2/getting-started/deploy-maui-windows.md
- blazor/pdfviewer-2/getting-started/server-side-application.md
- blazor/pdfviewer-2/getting-started/web-app.md
- blazor/pdfviewer-2/getting-started/web-assembly-application.md
- blazor/pdfviewer-2/globalization.md
- blazor/pdfviewer-2/how-to/deploy-maui-using-android-emulator.md
- blazor/pdfviewer-2/how-to/get-data-from-sfpdfviewer.md
- blazor/pdfviewer-2/how-to/identify-the-values-in-the-undo-redo-collections.md
- blazor/pdfviewer-2/how-to/load-desired-pdf-for-initial-loading-in-hosted-sample.md
- blazor/pdfviewer-2/how-to/load-pdf-document-dynamically.md
- blazor/pdfviewer-2/how-to/unload-the-pdf-document-from-viewer.md
- blazor/pdfviewer-2/how-to/update-form-field-using-context-menu.md
- blazor/pdfviewer-2/interaction.md
- blazor/pdfviewer-2/navigation.md
- blazor/pdfviewer-2/open-pdf-file/from-amazon-s3.md
- blazor/pdfviewer-2/open-pdf-file/from-box-cloud-file-storage.md
- blazor/pdfviewer-2/print.md
- blazor/pdfviewer-2/save-pdf-file/to-box-cloud-file-storage.md
- blazor/pdfviewer-2/saving-pdf-file.md
- blazor/pdfviewer-2/text-search.md
- blazor/pdfviewer-2/toolbar-customization.md
Update API reference links to all the APIs mentioned in the existing UG in Blazor platform
> 895038: Update API reference link

- blazor/pivot-table/getting-started-webapp.md
- blazor/pivot-table/getting-started.md
Updated Getting Started UG Document in Blazor Pivot table
> 894649: Updated Getting Started UG Document in Blazor Pivot Table

- blazor/textarea/events.md
- blazor/textarea/styles-appearance.md
Textarea component documentation Corrections in Blazor
Not properly added the Disabled property, Styles and Events.
To resolved issue, updated the Disabled property, Styles and Events on the textarea documentation.
- Ensured all topics with runnable code
NA
Confirm whether this feature is …
> 890708: Textarea component documentation corrections in Blazor

- blazor/textarea/form-support.md
- blazor/textarea/methods.md
Textarea component documentation Corrections in Blazor
Not properly added the Form Validation Content and Methods.
To resolved issue, updated the Form Validation Content and Methods on the textarea documentation.
- Ensured all topics with runnable code
NA
Confirm whether this feature is …
> 896112: Textarea component documentation corrections in Blazor

- blazor/gantt-chart/accessibility.md
Need to validate the keyboard actions for both Windows and Mac devices and update the User Guide (UG) for keyboard interaction.
The Grid team has updated the keyboard interactions, but we have not yet applied these updates on our side.
Included the keyboard interaction changes in the User Guide (UG).
Is this common issue need to be addressed in the same component or on …
> 895768: Need to Update UG for Keyboard interaction

- blazor/common/accessibility.md
Need to correct the Common accessibility page's doc links.
If there is an external design, link to its project documentation area.
The Common accessibility page documentation links were corrected
Post the output screenshots if an UI is affected or added due to this feature.
Added:
Changed:
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the …
> 896368: The Common accessibility page's documentation links were corrected

- blazor/document-editor/comments.md
- blazor/document-editor/fields.md
- blazor/document-editor/history.md
- blazor/document-editor/how-to/customize-color-picker.md
- blazor/document-editor/how-to/customize-context-menu.md
- blazor/document-editor/how-to/disable-optimized-text-measuring.md
- blazor/document-editor/how-to/enable-ruler-in-document-editor.md
- blazor/document-editor/how-to/export-document-as-pdf.md
- blazor/document-editor/how-to/get-the-selected-content.md
- blazor/document-editor/how-to/insert-text-in-current-position.md
- blazor/document-editor/how-to/show-hide-spinner.md
- blazor/document-editor/styles.md
- blazor/document-editor/table-format.md
- blazor/document-editor/table-of-contents.md
- blazor/document-editor/text-format.md
- blazor/document-editor/track-changes.md
- blazor/document-editor/view.md
Added documentation correction for blazor documentation.
> 104441: Documentation correction for blazor Documentation.

- blazor-toc.html
- blazor/document-editor/how-to/add-save-button-in-toolbar.md
- blazor/document-editor/how-to/auto-save-document.md
- blazor/document-editor/how-to/customize-tool-bar.md
Added the save toolbar button to custom toolbar and auto save document.
> Added the save toolbar button to custom toolbar and auto save document.

- blazor-toc.html
- blazor/document-editor/faq/unsupported-file-format.md
Added FAQ on why do i get the unsupported warning message when opening document.
> 895726: Added documentation on unsupported file formats.

- blazor/floating-action-button/getting-started-with-web-app.md
Hi @gowthamanthavasiyappan, kindly review my PR template below.
-- | --
Task Category | Blazor Image Alt With issue
Content Task Link/Mail Screenshot |  
Master/Dev PR |  https://github.com/syncfusion-content/blazor-docs/pull/4613
Ticket/Task link |  https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185614/
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B02737F02-3DE6-4A37-BEEE-4021A663ADB6%7D&file=Dickson.xlsx&action=default&mobileredirect=true&wdsle=0
</div>
</body>
</html>
Ex- https://github.com/syncfusion-content/blazor-docs/pull/4613
Title	Description
Task Category	React DateRangePicker FT improvements
Content Task Link/Mail Screenshot	
Master/Dev PR	
Ticket/Task link …
> SEO-174654-Blazor-Permanent-Redirect-Two

- blazor/scheduler/how-to/blazor-web-assembly-scheduler.md
-- | --
|Task Category |  Coverage issues|
|Content Task Link/Mail Screenshot | NA |
|Hotfix | https://github.com/syncfusion-content/blazor-docs/pull/4636|
|Ticket/Task link |  https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185658/|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BD059EAE3-DA11-4570-A59B-D252A95C9DFD%7D&file=Faith.xlsx&action=default&mobileredirect=true&wdsle=0|
-- | --
> 185658-Blazor-Scheduler

- blazor/common/showcase-samples.md
Updated UG content for Blazor showcase samples
> 885233: Updated showcase samples

- blazor/visual-studio-integration/scaffolding.md
Update the Blazor scaffolding UG content
> Update the Blazor scaffolding UG content

- blazor-toc.html
- blazor/pdfviewer-2/how-to/load-custom-font-pdfium.md
- blazor/pdfviewer-2/how-to/render-n-pages-scrolling.md
I have rename title and changed Github sample
> 897381: Renamed Title and changed Github sample

- blazor/listbox/how-to/add-items.md
Blazor List box Add item API link was not proper
Method name was incorrect and api link is not provided
Method name was incorrect so changed the method name and provided api link 
Post the …
> 898724: Blazor List box Add item API link was not proper

- blazor/visual-studio-integration/scaffolding.md
update Blazor scaffolding UG content
> update Blazor scaffolding UG content

- blazor/nuget-packages.md
Updated Nuget packages documentation for Syncfusion.Blazor.Core.
> 869661: updated Nuget packages

- blazor/system-requirements.md
Added the notes for workload related info
> 854904: Update system-requirements.md

- blazor/data-form/form-items.md
Added razor page reference for the change editor section in dataform
> Docs(EJ2-889022): Added razor page reference for the change editor section in dataform

- blazor/treegrid/data-binding.md
Updated Documentation for LoadChildOnDemand Sample In data binding 
Spec document 
Task link :https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/899148
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/899148
NA
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive …
> 899148: dev doc

- blazor/dialog/how-to/add-minimize-and-maximize-button.md
> Bug(BLAZ-124241): Corrected the dialog docs

- blazor/datagrid/global-local.md
- blazor/datagrid/sorting.md
- blazor/pivot-table/how-to/customize-number-and-date-format.md
Hi @Yvone-Atieno ,
Please review the changes.
-- | --
Task Category | Blazor Page with redirect links|
Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4701 |
Ticket/Task link |N/A|
|Changes Made | Reason for change |
|-- | -- |
|Changed redirect links in the page | To avoid redirection issues in the page |  
Regards,
Edith.
> SEO-187232-Blazor-page-with--redirect

- blazor/chart/chart-series.md
Hi @Yvone-Atieno ,
Please review the changes.
-- | --
Task Category | Blazor Page with redirect links|
Content Task Link/Mail Screenshot | NA|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4702 |
Ticket/Task link |N/A|
|Changes Made | Reason for change |
|-- | -- |
|Changed redirect links in the page | To avoid redirection issues in the page and provide direct link |  
Regards,
Edith.
> SEO-187232-Blazor-page-with-redirect-changes

- blazor/stock-chart/appearance.md
-- | --
|Task Category | Coverage Issues|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4769|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187829|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
-- | --
> SEO-187829-Blazor-Stock-Chart-Apperance-Page-with-redirect-link

- blazor/pivot-table/data-binding.md
-- | --
|Task Category | Coverage Issues|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4771|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187829|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
-- | --
> SEO-187829-Blazor-Pivot-table-Data-Binding-Page-with-redirect-link

- blazor/pivot-table/olap.md
-- | --
|Task Category | Coverage Issues|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4776|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187829|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
-- | --
> SEO-187829-Blazor-Pivot-table-Olap-Page-with-redirect-link

- blazor/daterangepicker/data-binding.md
-- | --
|Task Category | Coverage Issues|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4778|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187829|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B2A368E74-D539-456F-9819-C9B68637E490%7D&file=Faith.xlsx&action=default&mobileredirect=true|
-- | --
|Task Category | Coverage Issues|
|Content Task Link/Mail Scr
-- | --
> SEO-187829-Blazor-Daterangepicker-Data-Binding-Page-with-redirect-links

- blazor/listbox/selection.md
904018: Remove checkbox form single and multiple selection listbox sample
> 904018: Remove checkbox form single and multiple selection listbox sample

- blazor/treeview/searching-and-filtering.md
Resolved customer mentioned typos in our Blazor TreeView component documentation
> 905323-TreeView: Corrected the typos.

- blazor/treeview/searching-and-filtering.md
Resolved customer mentioned typos in our Blazor TreeView component documentation
> 905323: Corrected the typos.

- blazor/chart/chart-types/bar.md
- blazor/chart/chart-types/column.md
Added ColumnSpacing and ColumnWidth content in UG
> 901924: Added ColumnSpacing and ColumnWidth content in UG(dev)

- blazor/gantt-chart/column-template.md
The row height has increased on the tree grid side compared to the previous version in the column template sample, causing row misalignment.
The button height is not properly set when adding the e-bigger class, compared to the latest NuGet package.
Removed the e-bigger class from the button.
Need to check properly on future related items.
Is …
> 902958: Rows are misaligned in column template sample

- blazor/pdfviewer-2/getting-started/web-app.md
I have included the maximum receive message size in the web app sample getting started code snippet.
Regards,
Gokulprsath
> 905548: Update web-app.md

- blazor/datagrid/column-rendering.md
corrected the issue under column rendering documentation
> 893184: Resolved mistake in complex column declaration

- blazor/listview/style.md
Corrected the css code snippet for selected item customization in Blazor ListView component.
> 905715: Corrected the css code snippet for selected item customization in ListView component.

- blazor/chart/chart-types/radar.md
- blazor/chart/chart-types/spline-area.md
- blazor/kanban/style.md
- blazor/rich-text-editor/exec-command.md
- blazor/rich-text-editor/image.md
Hi @Aishwarya-Ganesan, Kindly review my PR below.
-- | --
|Task Category | Site audit permanent page with redirect|
|Hotfix | Hotfix -https://github.com/syncfusion-content/blazor-docs/pull/4788 |
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187143/|
|Work link | [Dickson Sheet](https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BA6F46E82-664F-4309-8F4B-E550E0CC32DF%7D&file=Dickson.xlsx&action=default&mobileredirect=true&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Cdicksonjosephato%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDA4MDIxMjAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)| …
> SEO-174654-Blazor-Page-with-permanent-redirect-One

- blazor/accumulation-chart/chart-types/pie-doughnut.md
- blazor/bullet-chart/getting-started.md
- blazor/chart/multiple-panes.md
- blazor/gantt-chart/baseline.md
- blazor/rich-text-editor/form-validation.md
Hi @Aishwarya-Ganesan, Kindly review my PR below.
-- | --
|Task Category | Stite audit permanent Redirect Links|
|Hotfix | Hotfix -https://github.com/syncfusion-content/blazor-docs/pull/4789|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187143/|
|Work link | [Dickson Sheet](https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BA6F46E82-664F-4309-8F4B-E550E0CC32DF%7D&file=Dickson.xlsx&action=default&mobileredirect=true&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Cdicksonjosephato%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNDA4MDIxMjAwOCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)| …
> SEO-174654-Blazor-Page-with-Permanent-redirect-two

- blazor/treegrid/columns/column-chooser.md
Removed Space in ColumnChooser documentation
Spec document 
Task link : https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/882860
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/882860
Before:
After: 
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive and …
> 882860: Update HeaderText

- blazor/rich-text-editor/tools/table-manipulation.md
- blazor/scheduler/how-to/blazor-web-assembly-scheduler.md
-- | --
Task Category | Page with Redirect|
Content Task Link/Mail Screenshot | NA|
Hotfix | https://github.com/syncfusion-content/blazor-docs/pull/4847|
Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187645/|
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B5956DB12-BF41-423F-9337-A60CF7314B63%7D&file=Yvone.xlsx&action=default&mobileredirect=true |
Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Page with Redirect | To avoid redirection 301 or 302 links, providing direct links. |  
Regards,
Yvone.
> SEO-185066 Permanent Redirect links

- blazor/query-builder/data-binding.md
- blazor/query-builder/getting-started-webapp.md
- blazor/query-builder/import-export.md
- blazor/query-builder/localization.md
- blazor/rich-text-editor/accessibility.md
-- | --
Task Category | Page with Redirect|
Content Task Link/Mail Screenshot | NA|
Hotfix | https://github.com/syncfusion-content/blazor-docs/pull/4846|
Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187645/|
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B5956DB12-BF41-423F-9337-A60CF7314B63%7D&file=Yvone.xlsx&action=default&mobileredirect=true |
Changes Made | Reason for change | Reason for not identifying earlier
-- | -- | --
Page with Redirect | To avoid redirection 301 or 302 links, providing direct links. |  
Regards,
Yvone.
> SEO-185066 Blazor Permanent redirect

- blazor-toc.html
- blazor/multicolumn-combobox/sorting.md
Update the allow sorting and multi-column sorting.
> 910110: Update the allow sorting and multi-column sorting.

- blazor/file-manager/pagination.md
Added Correction in the Pagination feature in File Manager component
> 908289: Modified the UG documentation correction in the Pagination.

- blazor/file-manager/pagination.md
Added Correction in the Pagination feature in File Manager component
> 908289: Modified the UG documentation correction in the Pagination

- blazor/file-manager/pagination.md
Added Proper API Reference in the Pagination documentation in file manager component.
> 908289: Added Proper API reference in the Pagination documentation

- blazor-toc.html
- blazor/multicolumn-combobox/data-binding.md
- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-textarea/getting-started-webapp.md
Resolving the CI failures while staging publishing
> 878826: commit for resolving CI failures

- blazor/scheduler/accessibility.md
Added new documentation for Keyboard Interaction feature.
> 909653: Documenting the Key-interaction feature in hotfix branch.

- blazor-toc.html
- blazor/multicolumn-combobox/code-snippet/grouping/grouping.razor
- blazor/multicolumn-combobox/grouping.md
Update the grouping section in Multi column documentation.
> 910110: Update the grouping section in Multi column documentation.

- blazor/gantt-chart/criticalpath.md
Added the notes section for critical path taskbar end date validation.
> 858644: Added the notes section in critical path

- blazor-toc.html
- blazor/multicolumn-combobox/code-snippet/form-validation/combobox-inside-editform.razor
- blazor/multicolumn-combobox/form-validation.md
Update the form validation section in Multi column documentation.
> 910110: Update the form validation section in Multi column documentation.

- blazor-toc.html
- blazor/multicolumn-combobox/localization.md
Update the localization section in Multi column documentation.
> 910110: Update the localization section in Multi column documentation.

- blazor/multicolumn-combobox/custom-value.md
- blazor/multicolumn-combobox/data-binding.md
- blazor/multicolumn-combobox/filtering.md
- blazor/multicolumn-combobox/placeholder-and-floatlabel.md
- blazor/multicolumn-combobox/selection.md
- blazor/multicolumn-combobox/sorting.md
- blazor/multicolumn-combobox/value-binding.md
- blazor/multicolumn-combobox/virtualization.md
Need to provide preview sample for Multicolumn ComboBox
> 911019: Need to provide preview sample for Multicolumn ComboBox

- blazor-toc.html
- blazor/multicolumn-combobox/code-snippet/column/column-template.razor
- blazor/multicolumn-combobox/code-snippet/grid-settings/allow-column-resizing.razor
- blazor/multicolumn-combobox/code-snippet/grid-settings/gridlines.razor
- blazor/multicolumn-combobox/column.md
- blazor/multicolumn-combobox/grid-settings.md
- blazor/multicolumn-combobox/paging.md
- blazor/multicolumn-combobox/placeholder-and-floatlabel.md
Update the grid settings section in Multi column documentation.
> 910110: Update the grid settings section in Multi column documentation.

- blazor/nuget-packages.md
- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-paste/getting-started.md
- blazor/smart-textarea/getting-started-webapp.md
- blazor/smart-textarea/getting-started.md
Addressing the review concerns.
> 878826: commit for addressed the review concerns

- blazor/nuget-packages.md
- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-paste/getting-started.md
- blazor/smart-textarea/getting-started-webapp.md
- blazor/smart-textarea/getting-started.md
Addressing the review concerns in UG content
> 878826: commit for corrections

- blazor/chart/data-labels.md
- blazor/chart/data-markers.md
- blazor/chart/date-time-axis.md
- blazor/chart/how-to/synchronized-chart.md
- blazor/chart/internationalization.md
- blazor/chart/numeric-axis.md
- blazor/chart/working-with-data.md
-- | --
|Task Category | Site Audit|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/4849|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/187689|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BB4258E4F-94C7-4ADD-8526-9381FAEEDDCC%7D&file=Book.xlsx&action=default&mobileredirect=true|
|-- | -- |
|Changed-Permanent redirect links | To improve performance of the page |
> SEO-189122-Blazor-chart-data-labels-Permanent-Redirect-links

- blazor/treeview/how-to/check-uncheck-the-checkbox-on-clicking-the-tree-node-text.md
Corrected the user guide documentation for check/uncheck on clicking the tree node text in Blazor TreeView component.
> 912494: Corrected the user guide documentation for check/uncheck on clicking the tree node text in Blazor TreeView component.

- blazor/image-editor/open-save.md
824314: resolved liquid exception error in Image editor UG
> 824314: resolved liquid exception error in Image editor UG

- blazor-toc.html
908351: image editor toc file path error
> 908351: image editor toc file path error

- blazor-toc.html
- blazor/rich-text-editor/how-to/update-value.md
Reverts syncfusion-content/blazor-docs#4955
> Revert "904096: Need to correct the update value documentation section"

- blazor/document-editor/how-to/add-save-button-in-toolbar.md
Added correction for the sample code in add save button to toolbar documentation.
> 912809: Sample code changes for add save button to toolbar.

- blazor-toc.html
- blazor/file-manager/ASP-NET-Core-SharePoint-file-provider.md
- blazor/file-manager/file-system-provider.md
Included share point service-related details in file manager documentation.
> 909983: Included share point service related details in file manager documentation.

- blazor-toc.html
- blazor/rich-text-editor/import-and-export.md
To add documentation for Import/export feature in all the platform except angular
Need to add an Import/export documentation.
No
No
Created an  Import/export documentation.
No
No
NA
No
/label ~bug
> 914538: To add documentation for Import/export feature in all the platform except angular

- blazor/ai-assistview/getting-started-webapp.md
- blazor/ai-assistview/getting-started.md
Need to add getting started preview sample for AIAsssitView component
Sample link 
1. https://blazorplayground.syncfusion.com/embed/rZrfCjiMCTRHTGzR?appbar=false&editor=false&result=true&errorlist=false&theme=bootstrap5
2. https://blazorplayground.syncfusion.com/embed/BjhTCNsCMKFGRhuU?appbar=false&editor=false&result=true&errorlist=false&theme=bootstrap5
None
NA
NA
> docs(911314): preview sample added for AIAsssitView component

- blazor/data-form/validation.md
916560: Added more information for save and Remove Method
> 916560: Added more information for save and Remove Method

- blazor/data-form/validation.md
916560: Added NuGet Information for ObjectGraphDataAnnotationsValidator
> 916560: Added NuGet Information for ObjectGraphDataAnnotationsValidator

- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-paste/getting-started.md
- blazor/smart-textarea/getting-started-webapp.md
- blazor/smart-textarea/getting-started.md
Missed adding namespaces and need to add the script in body tag.
NA
**Reason:**
Is there any other related areas also to be addressed?
If it is a breaking issue, provide the commit detail which caused this break.
Describe your code changes in detail for …
> 916804: Updated Smart components.

- blazor/file-manager/file-operations.md
Included the traversal changes in physical and node JS code block.
> 916694: Included the traversal changes in physical and node JS code block.

- blazor/gantt-chart/data-binding.md
- blazor/gantt-chart/split-task.md
The segment template and expando object section in the UG changes modified and updated.
NA
None
NA
NA
> 914644: segment template sample modified

- blazor/check-box/native-event.md
912182: Need to cover the ValueChange event of the CheckBox in the UG section.
> 912182: Need to cover the ValueChange event of the CheckBox in the UG section.

- blazor/button-group/selection-and-nesting.md
UG documentation for single and multiple mode two way binding for button group in blazor
Need to add code snippet in UG documentation for single and multiple mode two way binding for button group in blazor
UG documentation for single and multiple mode two way binding for button group in blazor
UX changes got approval if UI is added or modified?
Drafted UG for this feature?
Content team reviewed the UI content changes.
Is this the common feature which …
> 916911: UG documentation for single and multiple mode two way binding for button group in blazor

- blazor/file-upload/chunk-upload.md
917671: Updated the latest code for chunk Uploading
> 917671: Updated the latest code for chunk Uploading

- blazor/datagrid/columns.md
Documentation(919643):Correction
> Documentation(919643):Correction

- blazor/button-group/selection-and-nesting.md
- blazor/image-editor/annotation.md
- blazor/listbox/how-to/filter-listbox.md
- blazor/menu-bar/data-source-binding-and-custom-menu-items.md
849591: Branch merging conflicts between UG hotfix and development branch
> 849591: Branch merging conflicts between UG hotfix and development branch

- blazor/pivot-table/getting-started-webapp.md
- blazor/pivot-table/getting-started.md
Need to resolve issues on the Getting Started documentation that has been reported on the following platforms. The issues are outlined in the document below.
Core
MVC
Angular
Vue2
Vue3
Blazor
Issues: [GettingStarted.docx](https://dev.azure.com/EssentialStudio/b6db0cd2-2cc5-4f25-849c-c7a027012a1a/_apis/wit/attachments/8bb36840-9781-4b8f-a1f7-cace61adf58d?fileName=GettingStarted.docx&download=true)
> 918590: Need to fix the Blazor documentation getting started issues

- blazor/file-upload/chunk-upload.md
[UG documentation 920406](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/920406): How can I get the chunk-index and total-chunk values from the file uploader in Asp.net
> 920406: Added note for chunk-index and total-chunk

- blazor/treegrid/paging.md
Added documentation for Pager template
> 835737: added documentation for Pager template

- blazor/appearance/themes.md
- blazor/common/data-binding/bind-entity-framework.md
- blazor/common/data-binding/restful-service-binding.md
- blazor/common/data-binding/sql-server-data-binding.md
- blazor/common/data-binding/webapi-service-binding.md
- blazor/common/how-to/upgrade-syncfusion-components-to-latest-version.md
- blazor/common/how-to/version-compatibility.md
- blazor/common/localization.md
- blazor/getting-started/blazor-webassembly-authentication.md
- blazor/getting-started/razor-class-library.md
- blazor/media-query/media-query-reusable.md
- blazor/pdfviewer-2/getting-started/web-app.md
- blazor/predefined-dialogs/getting-started-webapp.md
- blazor/smart-paste/getting-started.md
- blazor/smart-textarea/getting-started.md
- blazor/system-requirements.md
- blazor/visual-studio-integration/download-and-installation.md
I updated .NET 9 framework details in Blazor UG documentation.
> Updated .NET 9 framework in Blazor UG documentation

- blazor/datagrid/global-local.md
- blazor/datagrid/scrolling.md
- blazor/datagrid/virtualization.md
- blazor/daterangepicker/accessibility.md
-- | --
|Task Category | Coverage Issues page with redirect links|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/5052|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/191535/|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B701eddd6-381f-4da1-9bd5-1b21c58fda94%7D&action=edit&activeCell=%27PR%20sheet%27!A17&wdinitialsession=b315f4f6-a576-a231-7415-f9966443dbab&wdrldsc=4&wdrldc=1&wdrldr=AccessTokenExpiredWarning%2CRefreshingExpiredAccessT|
|-- | -- |
|Changed redirect links | To avoid redirection 301 or 302 links, providing direct links.|
> SEO-191535-Blazor-Grid-Getting-started

- blazor/pdfviewer-2/how-to/import-annotations-as-objects.md
- blazor/query-builder/getting-started.md
- blazor/rich-text-editor/miscellaneous.md
- blazor/rich-text-editor/resizable-editor.md
-- | --
|Task Category | Coverage Issues page with redirect links|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/5053|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/191535|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BB2C741AA-C1E5-4235-85AB-CD3E8BFC0F19%7D&file=[Faith.xlsx](https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BB2C741AA-C1E5-4235-85AB-CD3E8BFC0F19%7D&file=Faith.xlsx&action=default&mobileredirect=true)&action=default&mobileredirect=true|
|-- | -- |
|Changed redirect links | To avoid redirection 301 …
> SEO-191535-Blazor-pdfviewer-2-how-to-import-annotations-as-objects

- blazor/smart-paste/getting-started.md
- blazor/smart-textarea/getting-started.md
Added reference link for Smart component UG documentation.
1. SmartTextArea
2. SmartPaste
> Added reference link for Smart component UG documentation

- blazor/accordion/getting-started-with-web-app.md
- blazor/accordion/getting-started.md
I added trademark symbol in Blazor Accordion getting started UG documentation
> 921374: Added trademark symbol in Blazor UG documentation

- blazor/pivot-table/number-formatting.md
Hi @Yvone-Atieno  
|--|--|
|Task Category| Coverage issues
|UX task| NA|
|Hotfix|https://https://github.com/syncfusion-content/blazor-docs/pull/5165
|Ticket/Task link| 
|Excel/SharePoint link| NA|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_worktimes/edit/192108
|--|--|
|redirect link| updated valid link to solve redirect link 
Regards,
Esther
> SEO- 191915- Blazor- pivot table- Redirect links

- blazor/accumulation-chart/tool-tip.md
Hi @Yvone-Atieno  
|--|--|
|Task Category| Coverage issues
|UX task| NA
|Hotfix|https://https://https://github.com/syncfusion-content/blazor-docs/pull/5167
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/192108
|Excel/SharePoint link| NA|
|--|--|
|redirection link|updated valid link to the redirected link
Regards,
Esther
> SEO- 191915- Blazor  Accumulation Chart- Redirect links

- blazor/multicolumn-combobox/code-snippet/filtering/custom-filtering.razor
- blazor/multicolumn-combobox/filtering.md
[UG documentation 921102](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/921102): FilterAsync method support - MultiColumnComboBox
> 921102: FilterAsync method support in MultiColumnComboBox

- blazor/pdfviewer-2/getting-started/web-app.md
- blazor/pdfviewer-2/getting-started/web-assembly-application.md
Updated the getting started md file on UG documentation
> 924854: updated the getting started md file

- blazor/carousel/getting-started-with-web-app.md
- blazor/carousel/getting-started.md
Getting started code snippet issues resolved in carousel
> Getting started code snippet issues resolved in carousel

- blazor/datagrid/column-headers.md
- blazor/datagrid/column-rendering.md
- blazor/datagrid/column-template.md
- blazor/datagrid/columns.md
- blazor/datagrid/detail-template.md
- blazor/datagrid/frozen-column.md
- blazor/datagrid/row-template.md
- blazor/datagrid/row.md
- blazor/diagram/migration-classic-to-native.md
- blazor/dropdown-list/data-binding.md
I added the trademark symbol in Blazor UG documentation.
> 924450: Added trademark symbol in Blazor UG documentation

- blazor/pdfviewer-2/how-to/refer-SfPdfViewer-script-in-application.md
* Updated the UG content to resolve the low word count issue
* We have missed to add the content for CDN Reference and Static web assets 
* Now added the content for CDN Reference and Static web assets  
*I have added content for CDN Reference and Static web assets 
[x] No.
Confirm whether this bug is ensured in both Blazor Server and WASM
Is there any new API or existing API name change?
Do the code changes cause any memory leak and performance issue? (Test only if you suspect that your code may cause problem)
> 927564: Updated the UG content to resolve the low word count issue

- blazor/scheduler/appointments.md
Include UG documentation for AllowOverlap API.
Need to include UG documentation for AllowOverlap API.
https://syncfusion.sharepoint.com/:w:/r/sites/EJ2-ClientSide/Shared%20Documents/Components/Schedule/Prevent%20overlapping%20appointments%20Specification%20Document.docx?d=w309c2213b4324b64903fbf70e67a8124&csf=1&web=1&e=gG7Zjz
NA
NA
https://syncfusion.sharepoint.com/:w:/r/sites/EJ2-ClientSide/Shared%20Documents/Components/Schedule/Prevent%20overlapping%20appointments%20Specification%20Document.docx?d=w309c2213b4324b64903fbf70e67a8124&csf=1&web=1&e=gG7Zjz
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated. 
NA
UX changes …
> 925696: Overlap API UG doc.

- blazor/carousel/accessibility.md
Include UG for disabling keyboard interaction in carousel
> 925705: Disabling keyboard interaction in carousel in UG was added.

- blazor/tabs/how-to/prevent-content-swipe-selection.md
Include UG documentaion for Swipe mode property.
Provide UG documentation for preventing swipe mode using SwipeMode property in SfTab.
https://syncfusion.sharepoint.com/:w:/r/sites/Blazor/_layouts/15/Doc.aspx?sourcedoc=%7BE137628E-A2EB-4B7D-AA77-B9EA185D4DE4%7D&file=Disabling%20swipe%20action%20specification%20documentation.docx&action=default&mobileredirect=true
NA
NA
https://syncfusion.sharepoint.com/:w:/r/sites/Blazor/_layouts/15/Doc.aspx?sourcedoc=%7BE137628E-A2EB-4B7D-AA77-B9EA185D4DE4%7D&file=Disabling%20swipe%20action%20specification%20documentation.docx&action=default&mobileredirect=true
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task …
> 925700: Swipe mode API UG doc

- blazor/dropdown-tree/templates.md
Removed Unused style in value template UG
> 925192: Removed unused style

- blazor-toc.html
- blazor/chat-ui/getting-started-webapp.md
- blazor/chat-ui/getting-started.md
- blazor/ribbon/backstage.md
- blazor/ribbon/events.md
- blazor/ribbon/filemenu.md
- blazor/ribbon/gallery.md
- blazor/ribbon/getting-started-webapp.md
- blazor/ribbon/getting-started.md
- blazor/ribbon/help-pane-template.md
- blazor/ribbon/items.md
- blazor/ribbon/layouts.md
- blazor/ribbon/resizing.md
- blazor/ribbon/tooltip.md
API Reference links updated for Ribbon component
> 903619: Updated API reference links for Ribbon component

- blazor-toc.html
- blazor/chat-ui/getting-started-webapp.md
- blazor/chat-ui/getting-started.md
- blazor/ribbon/backstage.md
- blazor/ribbon/events.md
- blazor/ribbon/filemenu.md
- blazor/ribbon/gallery.md
- blazor/ribbon/getting-started-webapp.md
- blazor/ribbon/getting-started.md
- blazor/ribbon/help-pane-template.md
- blazor/ribbon/items.md
- blazor/ribbon/layouts.md
- blazor/ribbon/resizing.md
- blazor/ribbon/tooltip.md
API Reference links updated for Ribbon component
> 903619: API ref links for Ribbon

- blazor-toc.html
Need to update the TOC order for ChatUI.
NA
None
NA
NA
> docs(928736): Need to update the TOC order for ChatUI.

- blazor/autocomplete/highlight-search.md
Update highlight-search code snipped path
(Briefly describe analysis of the feature. If there is an internal discussion on the Forum, provide the link.)
(Describe your code changes in detail for reviewers.)
(List out the areas are affected by your code changes.)
(Provide unit testing spec coverage details.)
(Provide new or update of API details)
/label ~bug
> 927515: Update highlight-search code snipped path

- blazor/chat-ui/getting-started-webapp.md
- blazor/chat-ui/getting-started.md
- blazor/ribbon/getting-started-webapp.md
- blazor/ribbon/getting-started.md
Preview sample URL updated for Ribbon and ChatUI
> 920008: Preview sample URL updated for Ribbon and ChatUI

- blazor/autocomplete/highlight-search.md
Update highlight-search code snipped path
(Briefly describe analysis of the feature. If there is an internal discussion on the Forum, provide the link.)
(Describe your code changes in detail for reviewers.)
(List out the areas are affected by your code changes.)
(Provide unit testing spec coverage details.)
(Provide new or update of API details)
/label ~bug
> 927515: Update highlight-search.md

- blazor/treegrid/data-binding.md
- blazor/treegrid/paging.md
Updated the paging docs reg the PageSizeMode
> 927349 filtering

- blazor/treegrid/data-binding.md
- blazor/treegrid/paging.md
Updated the paging docs reg the PageSizeMode
> 927349: Updated paging

- blazor-toc.html
- blazor/context-menu/how-to/scrollable-context-menu.md
- blazor/drop-down-menu/animation.md
- blazor/drop-down-menu/how-to/customize-popup-width.md
- blazor/drop-down-menu/template.md
- blazor/image-editor/image-restrictions.md
Clearly and concisely describe the problem or feature (this cannot be empty).
Briefly describe the root cause and analysis of the problem.
**Reason:**
Is there any other related areas also …
> 925769: Resolve UG staging issues completed for 2024 Vol 4 features

- blazor/pivot-table/grouping-bar.md
- blazor/pivot-table/row-and-column.md
Updated the YouTube link in the grouping bar and row/column md file.
> 930126: Updated the youtube link for the blazor documentation.

- blazor/diagram/serialization.md
Added tutorial link for serialization.
> 930821: Tutorial links

- blazor/scheduler/data-binding.md
- blazor/scheduler/editor-template.md
- blazor/scheduler/exporting.md
- blazor/scheduler/getting-started-webapp.md
- blazor/scheduler/resources.md
- blazor/scheduler/row-auto-height.md
- blazor/scheduler/virtual-scrolling.md
- blazor/scheduler/working-hours.md
Added tutorial videos in Blazor Scheduler
> Added tutorial videos in Blazor Scheduler

- blazor/dropdown-tree/getting-started.md
929039 : Add youtube video for Getting started Dropdown Tree component.
> 929039 : Add youtube video for Getting started Dropdown Tree component.

- blazor/in-place-editor/getting-started.md
- blazor/in-place-editor/style.md
- blazor/in-place-editor/validation.md
[UG documentation 930945](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/930945): Add the video to the Blazor platform documentation page
> 930945: Added YouTube Videos to In-Place Editor

- blazor/treegrid/data-binding.md
- blazor/treegrid/getting-started-webapp.md
- blazor/treegrid/getting-started.md
Added to the blazor you-tube video in UG documentation.
You tube video are added under below topics.
1.Getting Started with Blazor TreeGrid in Blazor Web Application (web server).
2.Getting Started with Blazor TreeGrid Component (Blazor server and wasm server).
3.Data Binding in Blazor TreeGrid Component.
> 928539: Added the you-tube video in the blazor platform

- blazor/common/playground/getting-started.md
- blazor/getting-started/blazor-server-side-visual-studio.md
- blazor/getting-started/blazor-web-app.md
- blazor/getting-started/blazor-webassembly-visual-studio.md
- blazor/getting-started/maui-blazor-app.md
- blazor/getting-started/wpf-blazor-app.md
- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-textarea/getting-started-webapp.md
I added video reference for Blazor UG documentation.
> 930500: Added video reference for Blazor UG documentation

- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-textarea/getting-started-webapp.md
I added video reference for Blazor UG documentation for below Blazor components,
1. Smart TextArea
2. Smart Paste Button
> 930943: Added video reference for Blazor UG documentation

- blazor/image-editor/getting-started-with-web-app.md
- blazor/image-editor/getting-started.md
Add the video to the Blazor platform documentation page for Image editor
> 907917: Added YouTube Videos to Image Editor

- blazor/carousel/getting-started.md
- blazor/carousel/navigators-and-indicators.md
- blazor/dashboard-layout/seo.md
- blazor/file-manager/drag-and-drop.md
- blazor/file-manager/getting-started-with-wasm-app.md
- blazor/listview/customizing-templates.md
- blazor/listview/data-binding.md
- blazor/listview/getting-started.md
- blazor/range-slider/getting-started.md
- blazor/sidebar/getting-started.md
- blazor/treeview/data-binding.md
- blazor/treeview/node-editing.md
- blazor/treeview/template.md
931454: Youtube video for ListView, Carousel, Dashboard Layout, TreeView, Sidebar, Slider, FileManager.
> 931454: Youtube video for ListView, Carousel, Dashboard Layout, TreeView, Sidebar, FileManager.

- blazor/appearance/themes.md
Need to add new themes in documentation.
* Bootstrap 5.3
* Bootstrap 5.3 dark
* Fluent2
* Fluent2 dark
* Tailwind 3.4
* Tailwind 3.4 Dark
Missed to update the new themes.
**Reason:**
Is there any other related areas also to be addressed?
If it is a …
> 678253: New themes updated in documentation.

- blazor/combobox/cascading.md
- blazor/combobox/templates.md
- blazor/dropdown-list/cascading.md
- blazor/dropdown-list/templates.md
- blazor/dropdown-list/virtualization.md
- blazor/multicolumn-combobox/getting-started-with-web-app.md
- blazor/multicolumn-combobox/getting-started.md
- blazor/multiselect-dropdown/multiple-selection-display-mode.md
- blazor/multiselect-dropdown/templates.md
[UG documentation 933074](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/933074): RE: Add tutorial videos in UG
> 933074: Added YouTube Video

- blazor/timeline/getting-started.md
- blazor/treeview/getting-started.md
933104: Test and resolve issues in UG all sections -Blazor Timeline.
> 933104: Test and resolve issues in UG all sections -Blazor Timeline.

- blazor/sidebar/auto-close.md
- blazor/sidebar/custom-context.md
- blazor/sidebar/docking-sidebar.md
- blazor/sidebar/getting-started.md
- blazor/sidebar/how-to/multiple-sidebar.md
- blazor/sidebar/how-to/open-and-close-the-sidebar.md
933104: Test and resolve issues in UG all sections -Blazor Sidebar.
> 933104: Test and resolve issues in UG all sections -Blazor Sidebar.

- blazor/drop-down-menu/popup-items.md
- blazor/drop-down-menu/template.md
- blazor/image-editor/how-to/render-dialog.md
1. Provide the DropdownEvents code for template support sample of dropdown button.
2. Corrected the image editor with dialog  sample.
> 850794: Provide the DropdownEvents code for template support sample of dropdown button.

- blazor/treeview/check-box.md
- blazor/treeview/data-binding.md
- blazor/treeview/drag-and-drop.md
- blazor/treeview/expand-collaspe-actions.md
- blazor/treeview/getting-started-webapp.md
- blazor/treeview/how-to/check-uncheck-the-checkbox-on-clicking-the-tree-node-text.md
- blazor/treeview/how-to/customize-the-expand-and-collapse-icons.md
- blazor/treeview/how-to/get-all-child-nodes.md
- blazor/treeview/how-to/get-dynamic-icon.md
- blazor/treeview/how-to/validate-the-text-when-renaming-the-tree-node.md
- blazor/treeview/integration.md
- blazor/treeview/multiple-selection.md
- blazor/treeview/navigation.md
- blazor/treeview/node-customization.md
- blazor/treeview/node-editing.md
- blazor/treeview/node-selection.md
- blazor/treeview/sorting.md
- blazor/treeview/template.md
933104: Test and resolve issues in UG all sections -Blazor TreeView.
> 933104: Test and resolve issues in UG all sections -Blazor TreeView.

- blazor/dropdown-tree/data-binding.md
- blazor/dropdown-tree/popup-setting.md
- blazor/dropdown-tree/style.md
- blazor/dropdown-tree/templates.md
- blazor/dropdown-tree/value-binding.md
933104: Test and resolve issues in UG all sections -Blazor Dropdown Tree
> 933104: Test and resolve issues in UG all sections -Blazor Dropdown Tree

- blazor/accordion/getting-started.md
I updated the Getting Started UG documentation for Blazor Accordion component.
> 935206: Updated Getting Started UG documentation for Blazor Accordion component

- blazor/accordion/getting-started.md
I updated the Getting Started UG documentation for Blazor Accordion component.
> 935206: Updated Getting Started UG documentation for Blazor Accordion component`

- blazor/accordion/getting-started.md
- blazor/accumulation-chart/getting-started.md
- blazor/ai-assistview/getting-started.md
- blazor/appbar/getting-started.md
- blazor/autocomplete/getting-started.md
- blazor/avatar/getting-started.md
- blazor/badge/getting-started.md
- blazor/barcode/getting-started.md
- blazor/breadcrumb/getting-started.md
- blazor/bullet-chart/getting-started.md
- blazor/button-group/getting-started.md
- blazor/button/getting-started.md
- blazor/calendar/getting-started.md
- blazor/card/getting-started.md
- blazor/carousel/getting-started.md
- blazor/chart/getting-started-wasm.md
- blazor/chart/getting-started.md
- blazor/chat-ui/getting-started.md
- blazor/check-box/getting-started.md
- blazor/chip/getting-started.md
- blazor/circular-gauge/getting-started.md
- blazor/color-picker/getting-started.md
I updated the Getting Started UG documentation for Blazor components.
> 935206: Updated Getting Started UG documentation for Blazor components

- blazor/pdfviewer-2/getting-started/web-app.md
- blazor/pdfviewer-2/getting-started/web-assembly-application.md
I have updated the skiasharp version 3.116.1 in the UG documentation properly like our source version.
Regards,
Gokulprasath
> ES-936145: Update Skiasharp version 3.116.1

- blazor/ribbon/items.md
Need to update items event description in the API links.
NA
None
NA
NA
> docs(935241): updated items event description in the API links.

- blazor/ai-assistview/getting-started.md
- blazor/timeline/getting-started.md
Need to add a getting started video for blazor Ai-assistview and timeline component
NA
NA
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated.
NA
UX changes got approval if UI is added or modified?
Drafted UG for this feature?
Content team reviewed the UI content changes.
Is this the common feature which needs to be addressed in the same component or on other components in our platform?
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code changes cause any memory leak and performance issue?
Created task in Blazor to synchronize …
> Config(928822): Added a getting started video link

- blazor/diagram/getting-started-with-web-app.md
Updated Getting Started Web App UG documentation for Blazor Diagram component
> 935206: Updated Getting Started Web App UG documentation for Blazor Diagram component

- blazor/3D-chart/getting-started-wasm.md
- blazor/3D-chart/getting-started-with-web-app.md
- blazor/3D-chart/getting-started.md
- blazor/spinner/getting-started-webapp.md
- blazor/split-button/getting-started-webapp.md
- blazor/splitter/getting-started-webapp.md
- blazor/stepper/getting-started-webapp.md
- blazor/stock-chart/getting-started-webapp.md
- blazor/tabs/getting-started-webapp.md
- blazor/textarea/getting-started-webapp.md
- blazor/textbox/getting-started-webapp.md
- blazor/timeline/getting-started-webapp.md
- blazor/timepicker/getting-started-webapp.md
- blazor/toast/getting-started-webapp.md
- blazor/toggle-switch-button/getting-started-webapp.md
- blazor/toolbar/getting-started-webapp.md
- blazor/tooltip/getting-started-webapp.md
- blazor/treegrid/getting-started-webapp.md
- blazor/treemap/getting-started-webapp.md
- blazor/treeview/getting-started-webapp.md
I updated the Getting Started Web App UG documentation for Blazor components.
> 935206: Updated Getting Started Web App UG documentation for Blazor components

- blazor/chip/getting-started.md
Hi @Girija-Rajendran 
Please review and merge the PRs,
|--|--|
|Category|Money Keywords |
|Keywords|Blazor Chips|
|Position|2FT, 3UG|
|Dev PR|https://github.com/syncfusion-content/featuretour-web-ej2/pull/5017|
|Master PR|https://github.com/syncfusion-content/featuretour-web-ej2/pull/5018|
|Task|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/193300/|
|Content Ticket| |
|UX Ticket|NA|
|Reference|https://syncfusion.sharepoint.com/sites/GH/SEO/SitePages/Blazor-Chips---Money-Keywords(1).aspx?Mode=Edit|
|--|--|
| Added Note section|To stuff the Keyword in the UG page along with the Interlinking<img width="730" alt="image" src="https://github.com/user-attachments/assets/bc12ed30-f33d-4f48-8aab-4084771e470f"> …
> SEO-193300-Blazor-Chips-Interlinking-Money-Keywords

- blazor/ai-assistview/getting-started-webapp.md
- blazor/ai-assistview/getting-started.md
- blazor/chat-ui/getting-started-webapp.md
- blazor/chat-ui/getting-started.md
Need to resolve the getting started issues logged for our components.
Unwanted highlighting of defining rendermode has been removed.
NA
None
NA
NA
> docs(937286): Resolve the getting started issues logged for our components.

- blazor/smart-paste/getting-started-webapp.md
- blazor/smart-paste/getting-started.md
- blazor/smart-textarea/getting-started-webapp.md
- blazor/smart-textarea/getting-started.md
Need to update the smartcomponent UG.
NA
Recently, we have removed the Azure.AI.OpenAI from smartcomponents dependency. So need to update in that UG like install Azure.AI.OpenAi package to use Azure OpenAI services.
NA
Added:
Changed:
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the unit testing written file details to understand the use cases considered in this implementation.
If there …
> 936192: Updated Smartcomponents.

- blazor/diagram/getting-started-with-maui-app.md
- blazor/diagram/getting-started-with-wasm-app.md
- blazor/diagram/getting-started.md
I updated Getting Started Web App UG documentation for Blazor Diagram component.
> 936482: Updated Getting Started Web App UG documentation for Blazor Diagram component

- blazor/treegrid/virtualization.md
Added limitation in virtualization.md
> 937560: Added limitation for reorder rows in virtualization documentation page

- blazor/diagram/getting-started-with-maui-app.md
Removed unwanted highlighted code.
> 936482: Removed unwanted highlighted code

- blazor/getting-started/blazor-server-side-visual-studio.md
- blazor/getting-started/blazor-web-app.md
- blazor/getting-started/blazor-webassembly-visual-studio.md
I updated common getting started ug documentation for Blazor Server, WASM and Web App.
> Updated common getting started ug documentation

- blazor/scheduler/appointments.md
IsBlock field mapping is missed in UG - Resolved
> 916469: IsBlock field mapping is missed in UG - Resolved

- blazor-toc.html
- blazor/getting-started/blazor-web-app.md
I removed unwanted common Getting Started UG documentation in Blazor UG documentation
> Removed unwanted common Getting Started UG documentation

- blazor/dashboard-layout/getting-started-with-web-app.md
- blazor/dashboard-layout/getting-started.md
- blazor/dashboard-layout/interaction-with-panels/dragging-moving-of-panels.md
- blazor/dashboard-layout/interaction-with-panels/floating-of-panels.md
- blazor/dashboard-layout/interaction-with-panels/resizing-of-panels.md
- blazor/dashboard-layout/panels/position-sizing-of-panels.md
- blazor/dashboard-layout/panels/setting-header-of-panels.md
- blazor/dashboard-layout/responsive-adaptive.md
- blazor/dashboard-layout/seo.md
- blazor/dashboard-layout/setting-size-of-cells.md
- blazor/dashboard-layout/style.md
933104: Corrections in Blazor Dashboard Layout component.
> 933104: Corrections in Blazor Dashboard Layout component.

- blazor/image-editor/resize.md
941529: ImageEditor component IsAspectRadio need to explain for resize method
Briefly describe the root cause and analysis of the problem.
**Reason:**
Is there any other related areas also …
> 941529: ImageEditor component IsAspectRadio need to explain for resize method

- blazor/getting-started/blazor-web-app.md
- blazor/getting-started/blazor-webassembly-app.md
I updated common Blazor Getting Started UG documentation
> Updated common Blazor Getting Started UG documentation

- blazor/range-slider/format.md
- blazor/range-slider/getting-started-webapp.md
- blazor/range-slider/getting-started.md
- blazor/range-slider/how-to/customize-slider-ticks-label.md
- blazor/range-slider/how-to/customize-the-bar.md
- blazor/range-slider/how-to/customize-the-limits.md
- blazor/range-slider/how-to/customize-the-thumb.md
- blazor/range-slider/how-to/date-range-slider.md
- blazor/range-slider/how-to/numeric-range-slider.md
- blazor/range-slider/how-to/reversible-slider.md
- blazor/range-slider/how-to/time-range-slider.md
- blazor/range-slider/how-to/validate.md
- blazor/range-slider/limits.md
- blazor/range-slider/orientation.md
- blazor/range-slider/ticks.md
- blazor/range-slider/tooltip.md
- blazor/range-slider/types.md
- blazor/tooltip/accessibility.md
- blazor/tooltip/content.md
- blazor/tooltip/customization.md
- blazor/tooltip/getting-started-webapp.md
- blazor/tooltip/getting-started.md
- blazor/tooltip/open-mode.md
- blazor/tooltip/position.md
- blazor/tooltip/setting-dimension.md
- blazor/tooltip/style.md
933104: Corrections in Blazor Range Slider and Tooltip component.
> 933104: Corrections in Blazor Range Slider and Tooltip component.

- blazor/accordion/getting-started.md
- blazor/accumulation-chart/getting-started.md
- blazor/ai-assistview/getting-started.md
- blazor/appbar/getting-started.md
- blazor/autocomplete/getting-started.md
- blazor/avatar/getting-started.md
- blazor/badge/getting-started.md
- blazor/barcode/getting-started.md
- blazor/breadcrumb/getting-started.md
- blazor/bullet-chart/getting-started.md
- blazor/button-group/getting-started.md
- blazor/button/getting-started.md
I updated the Getting Started UG documentation for Blazor components.
Accordion, Accumulation Chart, AI AssistView, AppBar, AutoComplete, Avatar, Badge, Barcode, Breadcrumb, Bullet Chart, Button Group and Button.
> Updated the Getting Started UG documentation for Blazor components

- blazor/getting-started/blazor-web-app.md
- blazor/getting-started/blazor-webassembly-app.md
- blazor/getting-started/razor-class-library.md
Updated the common Getting Started UG documentation
> Updated the common Getting Started UG documentation

- blazor/getting-started/blazor-web-app.md
Updated style inside tabcontents tag for UG content for Blazor Web App UG documentation.
> Updated style inside tabcontents tag for UG content

- blazor/getting-started/blazor-web-app.md
Removed <p> tag styles in Web App getting started UG documentation.
> Removed <p> tag styles in Web App getting started UG documentation

- blazor/accumulation-chart/getting-started-with-web-app.md
- blazor/daterangepicker/data-binding.md
- blazor/query-builder/getting-started-webapp.md
- blazor/scheduler/getting-started.md
- blazor/scheduler/how-to/blazor-web-assembly-scheduler.md
Hi @Mallika
|--|--|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/blazor-docs/pull/5601|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/197305/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfezZFOTA3MzQ5LTM4ODUtNDBDRC04ODNCLUNFNTRBOEIyNzIwRX0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
|--|--|
Regards,
Hillary
> SEO-197305-blazor-ug-page-with-redirect4

- blazor/card/getting-started.md
- blazor/getting-started/blazor-server-side-visual-studio.md
- blazor/getting-started/blazor-web-app.md
- blazor/spinner/getting-started.md
- blazor/tabs/getting-started.md
Hi @Mallika
|--|--|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/blazor-docs/pull/5600|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/197305/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfezZFOTA3MzQ5LTM4ODUtNDBDRC04ODNCLUNFNTRBOEIyNzIwRX0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
|--|--|
Regards,
Hillar
> SEO-197305-blazor-ug-page-with-redirect3

- blazor/button/getting-started.md
- blazor/datepicker/getting-started.md
- blazor/dropdown-list/getting-started.md
- blazor/kanban/getting-started.md
- blazor/timepicker/getting-started.md
Hi @Mallika
|--|--|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/blazor-docs/pull/5582|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/197305/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfe0NCQ0ZBN0JGLTUwM0YtNEJCNS05QjlELTM5MDA0QTA2NTZCM30&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
|--|--|
Regards,
Hillary
> SEO-197305-blazor-ug-page-with-redirect

- blazor/datagrid/getting-started.md
- blazor/datepicker/getting-started.md
- blazor/pivot-table/getting-started.md
- blazor/tabs/getting-started.md
- blazor/toolbar/getting-started.md
Hi @Mallika
|--|--|
|UX task| NA|
|Hotfix PR|https://github.com/syncfusion-content/blazor-docs/pull/5591|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/197305/|
|Excel/SharePoint link| https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfezZFOTA3MzQ5LTM4ODUtNDBDRC04ODNCLUNFNTRBOEIyNzIwRX0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true|
|--|--|
Regards,
Hillary
> SEO-197305-blazor-ug-page-with-redirect1

- blazor/pdfviewer/how-to/view-docx-file-in-blazor-application.md
- blazor/pivot-table/data-binding.md
- blazor/pivot-table/drill-through.md
- blazor/rich-text-editor/getting-started.md
- blazor/rich-text-editor/markdown.md
Hi @mallika,
|--|--|
|Task Category| Blazor page with redirect|
|Content Task Link/Mail Screenshot| |
|UX task| NA|
|Hotfix PR link| https://github.com/syncfusion-content/featuretour-file-formats/pull/1036|
|Ticket/Task link||
|Excel/SharePoint link|[Excel](https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BC7946AB1-0EE7-4CD1-8129-50040FF5758C%7D&file=Book.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1740556412508&web=1&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Cedithakinyia%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNTAxMzEwNjAxMyIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D)| …
> SEO-193848-coverage-blazor-page-with-redirect

- blazor/dashboard-layout/getting-started-with-web-app.md
- blazor/dashboard-layout/getting-started.md
- blazor/file-manager/getting-started-with-server-app.md
- blazor/file-manager/getting-started-with-wasm-app.md
- blazor/file-manager/getting-started-with-web-app.md
- blazor/file-manager/upload.md
933104: Corrections in File Manager and Dashboard Layout component.
> 933104: Corrections in Blazor File Manager and Dashboard Layout component.

- blazor-toc.html
Updated toc file for Blazor components getting started ug documentation.
> Updated toc file

- blazor/pdfviewer/annotation/shape-annotation.md
- blazor/pdfviewer/annotation/sticky-notes-annotation.md
- blazor/pdfviewer/how-to/unload-the-pdf-document-from-viewer.md
-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |NA|
|Hotfix | https://github.com/syncfusion-content/blazor-docs/pull/5617|
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/198439|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/doc.aspx?sourcedoc=%7Bd6c21776-a481-4928-84c3-5d7da3c22ebb%7D&action=edit&isSPOFile=1&ovuser=77f1fe12-b049-4919-8c50-9fb41e5bb63b%2Cfaithatienoa%40syncfusion.com&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiI0OS8yNTAyMTQwMDkxMCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D|
|-- | -- |
| Worked on redirect links | To avoid redirect links hence …
> SEO-198439-Blazor--pdfviewer-Page-with-redirect-links

- blazor/rich-text-editor/keyboard-support.md
- blazor/rich-text-editor/link.md
Hi @gowthamanthavasiyappan 
|--|--|
|Task Category|Coerage issue fixes
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/wpf-docs/pull/5630
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/198639/
|Excel/SharePoint link| NA|https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true
|--|--|
|redirect link| updated valid link to solve redirect link
Regards,
Mercy A.
> 198639-coverage-page-with-redirect-Blazor-docs

- blazor/datepicker/style-appearance.md
Documentation(Blaz-942330): Customized the Datepicker label using CssClass property
> Documentation(Blaz-942330): Customized the Datepicker label using CssClass property

- blazor/common/how-to/configure-blazor-component-in-bunit-testing.md
Need to update the latest changes made in our Blazor source which caused a breaking changes in bunit
NA
Recently, we have made changes in the blazor source which caused a breaking changes in bunit. 
NA
Added:
Changed:
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the unit testing written file details to understand the use cases considered in this implementation.
If there is no TDD (if …
> 929808: Update configure-blazor-component-in-bunit-testing.md

- blazor/diagram/container.md
Update heading on interaction section for container support.
> 930542: Container support

- blazor/diagram/interaction.md
Hi Team,
Modified the navigation link for Selection highlighter customization.
> 892673: Navigation link.

- blazor/multiselect-dropdown/multicolumn.md
Added Information on how to display MultiColumn item and CheckBox inline
> Documentation(BLAZ-939176): Added Information on how to display MultiColumn item and CheckBox inline

- blazor/gantt-chart/template-pdf-export.md
Added UG documentation for newly added label template support in PDF export
If there is an external design, link to its project documentation area.
Added detailed UG documentation for label template support in PDF export with use of PdfQueryTaskbarInfo event.
Post the output screenshots if an UI is affected or added due to this feature.
**Sample output:**
**PDF export output:**
List the areas are affected by your code changes - NA
List all API changes here (or just put None) - None
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the unit testing written file details to understand the use cases considered in this implementation.
If …
> 947742: Added Pdf label template UG documentation

- blazor/diagram/annotations/interactions.md
- blazor/diagram/container.md
- blazor/diagram/interaction.md
Added API reference for Container, RotationReference and CanToggleSelection
> 930542: API reference

- blazor-toc.html
- blazor/diagram/annotations/connector-annotation.md
- blazor/diagram/annotations/node-annotation.md
- blazor/diagram/bpmn-shapes/bpmn-shapes.md
- blazor/diagram/connectors/connectors.md
- blazor/diagram/container.md
- blazor/diagram/group.md
- blazor/diagram/ports/ports.md
- blazor/diagram/swimlane/swimlane.md
Updated sections and added notes.
> 930542: Diagram UG changes

- blazor/speech-to-text/appearance.md
- blazor/speech-to-text/getting-started-wasm.md
- blazor/speech-to-text/getting-started-web-app.md
- blazor/speech-to-text/methods.md
- blazor/speech-to-text/speech-recognition.md
Added api links for SpeechToText component
> 946519: Added api links for SpeechToText component

- blazor-toc.html
> 946519: Updated SpeechToText API ref link in toc

- blazor-toc.html
- blazor/scheduler/clipboard.md
Include UG for clipboard actions in Blazor.
> 931711: Include UG for clipboard actions in Blazor in hotfix.

- blazor/datagrid/filtering.md
- blazor/datagrid/frozen-column.md
- blazor/daterangepicker/globalization.md
-- | --
|Task Category | Coverage Issues page with redirect links|
|Content Task Link/Mail Screenshot |NA|
|Hotfix |https://github.com/syncfusion-content/blazor-docs/pull/5734 |
|Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/198600|
|Work link |https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BC7946AB1-0EE7-4CD1-8129-50040FF5758C%7D&file=Book.xlsx&action=default&mobileredirect=true&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&wdExp=TEAMS-TREATMENT&wdhostclicktime=1740465739326&web=1|
|-- | -- |
| Worked on redirect links | To avoid redirect links hence improving the performance of our page|
> SEO-198600-Blazor-Grid-page-with-redirect-links

- blazor/listview/data-binding.md
Updated the Entity Framework documentation in the ListView component.
> 867874: Need to update the Entity Framework documentation in the ListView component.

- blazor/document-editor/opening-a-document.md
940741:Modified Opening a document in Blazor DocumentEditor
> 940741:Modified Opening a document in Blazor DocumentEditor

- blazor/introduction.md
- blazor/nuget-packages.md
Added new component list in Blazor common UG documentation.
3D Chart
Accumulation Chart
DataManager
Predefined Dialogs
Markdown Editor
OTP Input
Speech To Text
TextArea
> 949653: Added new component list in Blazor UG documentation

- blazor/ui-kit/build-your-first-blazor-app-with-blocks.md
- blazor/ui-kit/getting-started.md
UI Kit URL links for online SB demo links are updated
> 00000: UI Kit URL links updated

- blazor/treeview/data-binding.md
Updated the child property type details in the Blazor TreeView documentation.
> 105089: Need to update the TreeViewFieldSettings UG of Blazor TreeView.

- blazor/predefined-dialogs/getting-started-webapp.md
Need to inject SFdialogService in documentation
> 948053: Need to inject SFdialogService in documentation

- blazor/treegrid/rows/row-drag-and-drop.md
Blazor documentation changes in row drag and drop file.
> 939197: Documentation changes

- blazor/drop-down-menu/how-to/position-popup.md
Modifying sample of Positioning Popup in How to section of Dropdown Menu
> 952808: Modifying sample of Positioning Popup in How to section of Dropdown Menu

- blazor/drop-down-menu/how-to/position-popup.md
Modifying sample of Positioning Popup in How to section of Dropdown Menu
> 952808 : Modifying sample of Positioning Popup in How to section of Dropdown Menu

- blazor/common/how-to/version-compatibility.md
Update Version Compatibility Changes in our blazor
https://blazor.syncfusion.com/documentation/common/how-to/version-compatibility
N/A
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in …
> 716156: Update version-compatibility.md

- blazor/common/how-to/version-compatibility.md
Update Version Compatibility Changes in our blazor
https://blazor.syncfusion.com/documentation/common/how-to/version-compatibility
N/A
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in …
> 716156: Update Version Compatibility Changes in our blazor

- blazor/system-requirements.md
Update Linux OS requirements for Blazor Documentation
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/859212/
N/A
N/A
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in …
> 859212: Update Linux OS requirements

- blazor/ui-kit/build-your-first-blazor-app-with-blocks.md
- blazor/ui-kit/overview.md
Updating UG for the UI Kit topic
> 954133: Updating UG for the UI Kit topic

- blazor/dialog/getting-started-with-web-app.md
- blazor/dialog/getting-started.md
Documentation Update related to task - https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/954186
> 954186: Showing the Preview sample after Preview Button in Dialog

- blazor/datagrid/toolbar-items.md
https://blazorplayground.syncfusion.com/htBeNzUXgGVarUyV
> documentation(949728):Customize the built-in toolbar items

- blazor/document-editor/track-changes.md
933810:Added the enableTrackChanges feature document-level settings Content information in Blazor
> 933810:Added the enableTrackChanges feature document-level settings Content information in Blazor

- blazor/breadcrumb/getting-started.md
- blazor/datagrid/getting-started.md
- blazor/dropdown-list/getting-started.md
- blazor/file-upload/getting-started.md
- blazor/sidebar/getting-started-webapp.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5897|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect1

- blazor/chart/getting-started.md
- blazor/combobox/getting-started.md
- blazor/daterangepicker/getting-started.md
- blazor/spinner/getting-started.md
- blazor/toast/getting-started.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5898|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect-2

- blazor/calendar/getting-started.md
- blazor/datagrid/getting-started.md
- blazor/menu-bar/getting-started.md
- blazor/spinner/getting-started.md
- blazor/toggle-switch-button/getting-started.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5899|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect3

- blazor/carousel/getting-started.md
- blazor/check-box/getting-started.md
- blazor/pivot-table/getting-started.md
- blazor/tooltip/getting-started.md
- blazor/treeview/getting-started.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5900|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect4

- blazor/datagrid/getting-started.md
- blazor/diagram/getting-started.md
- blazor/listview/getting-started.md
- blazor/scheduler/getting-started.md
- blazor/toast/getting-started.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5901|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect5

- blazor/calendar/getting-started.md
- blazor/chip/getting-started.md
- blazor/dashboard-layout/getting-started-with-web-app.md
- blazor/listview/getting-started.md
- blazor/signature/getting-started.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5902|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect6

- blazor/data/getting-started.md
- blazor/image-editor/getting-started-with-web-app.md
- blazor/splitter/getting-started.md
- blazor/textbox/getting-started.md
- blazor/toast/getting-started-webapp.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5903|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect7

- blazor/dashboard-layout/getting-started-with-web-app.md
- blazor/document-editor/getting-started/server-side-application.md
- blazor/menu-bar/getting-started.md
- blazor/multiselect-dropdown/getting-started.md
- blazor/pdfviewer-2/getting-started/server-side-application.md
@Yvone-Atieno 
|--|--|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/5905|
|--|--|
Regards,
Hillary
> SEO-200810-blazor-page-with-redirect8

- blazor-toc.html
- blazor/datagrid/cell-selection.md
Revamp the cell selection topic in Blazor DataGrid documentation
1. Single cell selection: https://blazorplayground.syncfusion.com/VNhIDTMogkDEfUZP
2. Multiple cell selection: https://blazorplayground.syncfusion.com/VZByZftPTLzoDPqs
3. Cell selection mode: https://blazorplayground.syncfusion.com/hXLojfCyJcvLejSc
4. Single cell selection: https://blazorplayground.syncfusion.com/hthojzsefOMTNQRS
5. Multiple cell selection: https://blazorplayground.syncfusion.com/BZryjJMHBefDHtMz
6. How to get selected row cell indexes: https://blazorplayground.syncfusion.com/VXBetziRAPpKWdMw
7. Clear cell selection programmatically: https://blazorplayground.syncfusion.com/rDLyjJCxzNzEQyvE
8. Cell selection events: https://blazorplayground.syncfusion.com/VDBeDTMndIEZmTvp
> 936969: Revamp Cell Selection topic

- blazor/rich-text-editor/tools/custom-tool.md
- blazor/rich-text-editor/undo-redo-manager.md
104498: Added code snippet for custom tool section in RichTextEditor Blazor-dev
> 104498: Added code snippet for custom tool section in RichTextEditor Blazor-dev

- blazor/common/content-security-policy.md
- Need to update documentation for limitations of unsafe-inline CSP tag
-  [TaskID](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/953352)
> 953352: Updated documentation for limitations of unsafe-inline CSP tag

- blazor/ui-kit/overview.md
Updating the UI kit overview documentation content
> 925823: Updating the UI kit overview documentation content

- blazor/rich-text-editor/exec-command.md
- blazor/rich-text-editor/getting-started-webapp.md
- blazor/rich-text-editor/paste-cleanup.md
- blazor/rich-text-editor/style.md
Hi @MallikaRK 
|--|--|
|Task Category|Coerage issue fixes
|UX task| NA|
|Hotfix|https://github.com/syncfusion-content/blazor-docs/pull/5965
|Ticket/Task link|https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/201705/
|Excel/SharePoint link| NA|https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B8D09F47E-B62B-44E2-8EFE-FF4F4B48899B%7D&file=Page%20with%20redirect.xlsx&nav=MTVfezAwMDAwMDAwLTAwMDEtMDAwMC0wMDAwLTAwMDAwMDAwMDAwMH0&wdOrigin=TEAMS-MAGLEV.p2p_ns.rwc&action=default&mobileredirect=true
|--|--|
|redirect link| updated valid link to solve redirect link
Regards,
Mercy A.
> 201705-Coverage-Issue-fixes-Page-with-redirect-Blazor-Rich-text-editor

- blazor/treeview/data-binding.md
Updated the TreeView CRUD operation Entity framework document sample.
> 106146: Need to update the TreeView CRUD operation document with latest source.

- blazor/document-editor/getting-started/client-side-application.md
- blazor/document-editor/getting-started/server-side-application.md
- blazor/document-editor/getting-started/web-app.md
958208:  Added warning note for incompatibility of Syncfusion.Blazor components
> 958208:  Added warning note for incompatibility of Syncfusion.Blazor components

- blazor/ui-kit/overview.md
Updating the UI kit overview documentation content
> 963203: Updating the UI kit overview documentation content

- blazor/getting-started/razor-class-library.md
* Updated Razor class library related UG
* Updated net6 and net7 to net 8 and net 9
> 964808: Remove net6 and net7 reference in UG

- blazor-toc.html
- blazor/tutorials/build-a-blazor-stay-reservation-app.md
Drafted the tutorial for stay reservation show case application.
https://github.com/syncfusion/blazor-showcase-stay-reservation/tree/master
> drafted the tutorial for stay reseveration app

- blazor/smart-paste/claude-service.md
- blazor/smart-paste/custom-inference-backend.md
- blazor/smart-paste/deepseek-service.md
- blazor/smart-paste/gemini-service.md
- blazor/smart-paste/groq-service.md
- blazor/smart-textarea/claude-service.md
- blazor/smart-textarea/custom-inference-backend.md
- blazor/smart-textarea/deepseek-service.md
- blazor/smart-textarea/gemini-service.md
- blazor/smart-textarea/groq-service.md
Provided proper headings in custom AI services.
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/957498/
Revised the content and made changes wherever necessary.
NA
Added:
Changed:
Describe any non-bug related behavioral changes that may change how users app behaves when upgrading to this version of the codebase.
Provide the unit testing written file details to understand the use cases considered in this implementation.
If there is no TDD (if it’s not possible to …
> 966118: Moved smartcomponents related changes to master

- blazor/pdfviewer-2/how-to/print-the-sfpdfiewer-inside-the-dialog-component.md
Description:
Updated the dialog height
> 966652: Updated the dialog height

- blazor-toc.html
- blazor/rich-text-editor/tools/code-block.md
Implement Feature Documentation for Code Block in Rich Text Editor
> 965200: Implement Feature Documentation for Code Block in Rich Text Editor

- blazor/spreadsheet/clipboard.md
- blazor/spreadsheet/filtering.md
- blazor/spreadsheet/formulas.md
- blazor/spreadsheet/sorting.md
- blazor/spreadsheet/worksheet.md
Updated the following MD files
1) Sorting
2) Filtering
3) Clipboard
4) Worksheet
5) Formulas
> BLAZ-001: Corrections

- blazor/spreadsheet/contextmenu.md
- blazor/spreadsheet/hyperlink.md
Context menu and hyperlink sample updation
> 967161: Corrections for context menu and hyperlink

- blazor/image-editor/open-save.md
Prepared UG for IE 2025 Vol2 completed features
> 961191: Prepare UG for IE 2025 Vol2 completed features

- blazor/introduction.md
- blazor/nuget-packages.md
Added new component (Spreadsheet) information in introduction page.
> Added new component in introduction page

- blazor/diagram/ports/ports.md
Updated node port connection content for diagram.
> 969656: Updated Node port connection content.

- blazor/tutorials/build-a-blazor-stay-reservation-app.md
Stay reservation tutorial topic modified.
> 921523: modify stay reservation sample topic

- blazor/scheduler/header-bar.md
Added the scheduler date range customization using dateRangeTemplate topic in schedule header bar section
> 921523: Added dateRangeTemplate section in blazor documentation

- blazor/scheduler/events.md
[Task-970219](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/970219) - Remove deprecated properties before 27.1.48 release for Blazor Scheduler and Tab
The **Action** property from **NavigatingEventArgs** needs to be removed and replaced with the **ActionType** property, as **Action** property is now marked as obsolete.
NA
NA
NA
Mark …
> 970219: Removed deprecated properties from the Scheduler component

- blazor/progress-button/spinner-and-progress.md
Need to correct start and stop section codesnippet in blazor ProgressButton https://blazor.syncfusion.com/documentation/progress-button/spinner-and-progress#start-and-stop-methods
> Updated spinner-and-progress.md

- blazor/tabs/how-to/create-wizard-using-tab.md
[Task-970219](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/970219) - Remove deprecated properties before 27.1.48 release for Blazor Scheduler and Tab
[Deprecated property List.loop](https://loop.cloud.microsoft/p/eyJ1IjoiaHR0cHM6Ly9zeW5jZnVzaW9uLnNoYXJlcG9pbnQuY29tL2NvbnRlbnRzdG9yYWdlL0NTUF9kNmYwNDE2Ny1iZjAwLTQ0MjgtYThmZC1kM2Q4NjdiM2I4ZDQ%2FbmF2PWN6MGxNa1pqYjI1MFpXNTBjM1J2Y21GblpTVXlSa05UVUY5a05tWXdOREUyTnkxaVpqQXdMVFEwTWpndFlUaG1aQzFrTTJRNE5qZGlNMkk0WkRRbVpEMWlKVEl4V2pCSWR6Rm5RMTlMUlZOdlgyUlFXVm8zVHpReFFUaGtiVVpSWWtneE9VZHRZamh3VkVwMVUzbG5hM2N0ZUhSVlJUbGFNRlJMUjA1M1kxUnNTMlpHUnlabVBUQXhSRXROTmtoVFZrRlFWVk5hU2tKUVdEUTFSVE0xUzBkVVFVWlJWbEZIUmtjbVl6MGxNa1ltWVQxTWIyOXdRWEJ3Sm5BOUpUUXdabXgxYVdSNEpUSkdiRzl2Y0Mxd1lXZGxMV052Ym5SaGFXNWxjaVo0UFNVM1FpVXlNbmNsTWpJbE0wRWxNakpVTUZKVVZV …
> 970219: Removed Grid component ColumnType.Number deprecated property in the Tab sample

- blazor/ui-kit/overview.md
Updating the UI kit overview documentation content
> 878023: Updating the UI kit overview documentation content

- blazor-toc.html
- blazor/getting-started/maui-blazor-app.md
- blazor/getting-started/maui-blazor-web-app.md
* Need to updated title for .NET MAUI Blazor Hybrid and Web App UG.
> 970293: Updated title for .NET MAUI Blazor Hybrid and Web App UG

- blazor/getting-started/blazor-webassembly-app.md
Removed the youtube link which uses the very older frameworks
> 00000: Update blazor-webassembly-app.md

- blazor/datagrid/getting-started-with-server-app.md
- blazor/datagrid/getting-started.md
- blazor/getting-started/blazor-server-side-visual-studio.md
Updated Getting Started UG documentation for Blazor components UG documentation.
> Updated Getting Started UG documentation for Blazor components UG documentation

- blazor-toc.html
> Updated toc file for Blazor Server App UG

- blazor-toc.html
- blazor/dialog/resize.md
- blazor/dialog/style.md
866877: Correction in blazor Dialog UG section layout.
Specs: [documentation.](https://syncfusion-my.sharepoint.com/:w:/p/udhayakumar_duraisamy/Een6DSy4YidHpDq0_ct-1xsB0HPxLjwKuhZ6TTAMkuIxnA?e=5wMhKs)
> 866877: Correction in blazor Dialog UG section layout

- blazor-toc.html
- blazor/color-picker/events.md
Need a closed event for the ColorPicker component for restoring the selection in the RTE component
[Task 969011](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/969011): Need a closed event for the ColorPicker component for restoring the selection in the RTE component
The RTE team requested this feature to restore selection after the ColorPicker popup is closed. The ColorPicker inherits from SfSplitButton, which already supports a Closed event. This feature exposes that event in the SfColorPicker component.
Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/969011
Feature matrix document updated against this feature and committed in this [common location]  …
> Blaz 948846 eve

- blazor-toc.html
- blazor/common/how-to/port-blazor-server-maui.md
- blazor/getting-started/maui-blazor-app.md
- Updated review corrections reg the port blazor webapp to maui UG
- Updated Blazor maui UG based on latest project structure
> 971284: Update project structure in Blazor docs

- blazor/color-picker/events.md
Need a closed event for the ColorPicker component for restoring the selection in the RTE component
The RTE team requested this feature to restore selection after the ColorPicker popup is closed. The ColorPicker inherits from SfSplitButton, which already supports a Closed event. This feature exposes that event in the SfColorPicker component.
Task: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/969011
Feature matrix document updated against this feature and committed in this [common location] 
Mark 'Is Automated' field as (Yes, …
> 969011: Need a closed event for the ColorPicker component for restoring the selection in the RTE component

- blazor/common/accessibility.md
- blazor/nuget-packages.md
Updated NuGet packages UG documentation
> Updated NuGet packages UG documentation

- blazor/chat-ui/mention.md
Update mention.md for the mention support for the chat UI in Blazor documentation
Azure Task URL: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/977092
NA
NA
NA
NA
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the feature is automated.
NA
UX changes got approval if UI is added or modified?
Drafted UG for this feature?
Content team reviewed the UI content changes.
Is this the common feature which needs to be addressed in the same component or on other components in our platform?
Confirm whether the ensured feature is in both Blazor Server and WASM.
Do the code changes …
> 977092: Updation concerns in md file

- blazor-toc.html
- blazor/gantt-chart/excel-like-filter.md
- blazor/gantt-chart/timezone.md
- blazor/gantt-chart/wbs-column.md
Added UG documentation for WBS column in Blazor Gantt chart
> 977520: Added WBS column documentation

- blazor/datagrid/cell.md
(Task link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/968769/)
Need to display Tooltip in Grid content and header and also custom tooltip for header.
After:
Tested with following combinations manually:
1. Sorting
2. Complex column
3. Filtering
4. Aggregates
5. Frozen
6. BrowserScrolling
7. InfiniteScrolling cases
8. Column chooser
9. Template samples in UG document
10. Editing cases
11. Stacked Header
12. Grouping cases
13. Re-ordering cases
14. Adding new record and then hovering – tooltip shows
15. Feature-matrix sample
Provide the test bed sample location for code reviewers to verify the feature's behavior.
> 978180: Need to add Tooltip feature in UG documentation

- blazor/ai-developer-tools/copilot-extension.md
- blazor/ai-developer-tools/mcp-server.md
- blazor/ai-developer-tools/overview.md
Need to update the ai-developer-tools documents
[980907](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/980907/)
NA
NA
Feature matrix document updated against this feature and committed in this [common location](https://syncfusion.sharepoint.com/sites/EJ2ProductOwners/Shared%20Documents/Forms/AllItems.aspx?viewid=ae81c682%2D3d0f%2D462a%2Db8ec%2D7358748d489d&id=%2Fsites%2FEJ2ProductOwners%2FShared%20Documents%2FGeneral%2FFeature%20Matrix%20%2D%20Documents) . 
Mark 'Is Automated' field as (Yes, Manual, Not Applicable) in …
> 980907: Fixed document issues

- blazor/common/accessibility.md
Update the Target Link for SfPdfViewer in common accessibility sample
> 983312: Update the Target Link for SfPdfViewer

- blazor/accordion/accessibility.md
- blazor/accordion/animations.md
- blazor/accordion/content-render-mode.md
- blazor/accordion/data-binding.md
- blazor/accordion/expand-mode.md
- blazor/accordion/getting-started-with-web-app.md
- blazor/accordion/getting-started.md
- blazor/accordion/how-to/add-icon-to-accordion-header.md
- blazor/accordion/how-to/add-nested-accordion.md
- blazor/accordion/how-to/add-remove-accordion-items.md
- blazor/accordion/how-to/create-wizard-using-accordion.md
- blazor/accordion/how-to/enable-disable-accordion-item.md
- blazor/accordion/how-to/integrate-treeview-inside-the-accordion.md
- blazor/accordion/how-to/prevent-expand-collapse-accordion-item.md
- blazor/accordion/how-to/show-hide-accordion-item.md
- blazor/accordion/style.md
Updated the content and sample for Accordion Component.
> Updated the UG Content for Accordion.

- blazor/3D-chart/print-export.md
- blazor/bullet-chart/actual-bar.md
- blazor/circular-gauge/how-to/place-gauge-inside-other-components.md
Updated the preview samples in 3DChart, bullet chart and circular gauge.
> 982808: Updated the preview samples in 3DChart, bullet chart and circular gauge.

- blazor-toc.html
- blazor/treegrid/accessibility.md
- blazor/treegrid/adaptive-layout.md
- blazor/treegrid/aggregate.md
- blazor/treegrid/auto-fill-like-excel.md
- blazor/treegrid/cell.md
> 983239: Treegrid Filed updated

- blazor/treegrid/clipboard.md
- blazor/treegrid/context-menu.md
- blazor/treegrid/custom-binding.md
- blazor/treegrid/custom-style.md
> 983239: Treegrid files updated

- blazor/treegrid/scrolling.md
- blazor/treegrid/searching.md
- blazor/treegrid/sorting.md
- blazor/treegrid/state-management.md
- blazor/treegrid/toolbar.md
scrolling, searching, sorting and state-management updated
> 983239: scrolling, searching, sorting and state-management updated

- blazor/treegrid/events.md
- blazor/treegrid/globalization.md
- blazor/treegrid/selection.md
- blazor/treegrid/templates.md
- blazor/treegrid/virtualization.md
> 983239: files updated in TreeGrid

- blazor/treegrid/aggregate.md
- blazor/treegrid/cell.md
- blazor/treegrid/columns/columns.md
- blazor/treegrid/editing/template-editing.md
- blazor/treegrid/rows/rows.md
> 984006: Sample updated

- blazor/datagrid/events.md
983330: Blazor DataGrid – Updated UG Samples (Events).
Depreciated properties and methods have been removed and added the corresponding alternative methods.
> 983330: Blazor DataGrid – Updated UG Samples (Events)

- blazor/chip/customization.md
- blazor/chip/types.md
Resolved the issue that leading icon is not loading correctly in the Blazor chip documentation preview sample
> Docs(BLAZ-982804): Resolved the issue that leading icon is not loading correctly in the Blazor chip documentation preview sample

- blazor-toc.html
- blazor/ai-assistview/ai-integrations/gemini-integration.md
- blazor/ai-assistview/ai-integrations/openai-integration.md
- blazor/chat-ui/ai-integrations/gemini-integration.md
- blazor/chat-ui/ai-integrations/openai-integration.md
Description
Need to update the contents of the ai-integrations samples
Gemini integration
Azure Openai
> 982891: Update the ai-integrations contents

- blazor-toc.html
Description
Removing the ai-integration for chat ui in blazor
> 982891: Removing the ai-integration for chat ui in blazor

- blazor/dialog/getting-started-with-web-app.md
- blazor/dialog/getting-started.md
Correct the preview output in Blazor Dialog Getting Started UG
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/984091
https://support.syncfusion.com/agent/tickets/771145
Previously, the preview output in the Blazor Dialog Getting Started UG was wrongly updated; now the preview sample is updated correctly.
> 984091: Need to correct the preview output in Blazor Dialog Getting Started UG

- blazor/datagrid/column-chooser.md
- blazor/datagrid/column-headers.md
984345: Blazor DataGrid – Updated UG Samples (Column)
> 984345: Blazor DataGrid – Updated UG Samples (Column)

- blazor/chart/chart-types/bubble.md
- blazor/chart/chart-types/high-low.md
- blazor/chart/chart-types/polar.md
- blazor/chart/chart-types/radar.md
- blazor/chart/chart-types/scatter.md
- blazor/chart/chart-types/stack-bar.md
- blazor/chart/chart-types/stacked-bar.md
**Updated the contents and samples in the UG for the following pages in chart control:**
- Stacked Bar
- 100% Stacked Bar
- Scatter
- Bubble
- Polar
- Radar
- Hilo
> 983838: Updated the UG content and example changes in the chart control.

- blazor/rich-text-editor/getting-started-webapp.md
- blazor/rich-text-editor/getting-started-with-maui-app.md
- blazor/rich-text-editor/getting-started-with-server-app.md
- blazor/rich-text-editor/getting-started.md
983303: Updated getting-started.md
> 983303: Updated getting-started.md

- blazor/kanban/accessibility.md
- blazor/kanban/cards.md
- blazor/kanban/columns.md
- blazor/kanban/data-binding.md
- blazor/kanban/dialog.md
- blazor/kanban/dimensions.md
- blazor/kanban/drag-and-drop.md
- blazor/kanban/events.md
- blazor/kanban/getting-started-with-web-app.md
- blazor/kanban/getting-started.md
- blazor/kanban/localization.md
- blazor/kanban/responsive-mode.md
- blazor/kanban/sort.md
- blazor/kanban/style.md
- blazor/kanban/swimlane.md
- blazor/kanban/tooltip.md
- blazor/kanban/validation.md
- blazor/kanban/workflow.md
983303: Updated Kanban documentation
> 983303: Updated Kanban documentation
