syncfusion-content/blazor-docs

blazor/scheduler/accessibility.md
Ctrl + Shift + Arrow keys and F12 functionality were not added in the below UG.
https://blazor.syncfusion.com/documentation/scheduler/accessibility#keyboard-navigation
=> documentation(EJ2-56305): Added missed keys in the Keyboard navigation section

blazor/gantt-chart/virtual.md
Limitations added for Virtual Scroll in Blazor Gantt Chart Component.
Limitations added
- Collapse all tasks and Expand all tasks are not supported with Virtual scrolling.
=> bug(BLAZ-21578): Limitations

blazor/scheduler/editor-template.md
Documentation description:
Need to remove ElementType related codes and explanations in QuickInfoTemplate topics
Issue:
The ElementType virtual property has been deprecated on the source side. And it can be achieved by checking the Id field as default(int). So need to change the UG sample and related content.
Solution:
1.Remove the propertry ElementType from AppointmentData
2.Change the contion as (context as AppointmentData).Id == default(int)
=> documentation(BLAZ-20575):Need to remove ElementType related codes and explanations in QuickInfoTemplate topics

blazor/pdfviewer/how-to/client-side-error.md
Resolve the “Client-side error…” issue in .Net 6.0 which uses System.Text.Json for serialization instead of Newtonsoft.Json
=> documentation(BLAZ-23329): Resolve the “Client-side error…” issue in .Net 6.0 which uses System.Text.Json for serialization instead of Newtonsoft.Json

blazor/carousel/populating-items.md
Reference link does not navigate to the another page issue has been resolved.
=> documentation(EJ2-62728): link does not navigate to the another page issue has been resolved.

blazor/treegrid/how-to/single-click-editing-with-batch-mode.md
Bug description
Didn't work for toolbar item in Single click editing with batch mode
Root cause
There is no property declared for a particular field that leads to Argument exception and prevent the program to enable update in ToolBar
Reason for not identifying earlier
Find how it was missed in our earlier testing and development by analysing the below checklist. This will help prevent similar mistakes in the future.
Guidelines/documents are not followed
Guidelines/documents are not given
Reason:
Output screenshots:
Action taken:
Ensured the sample with changes made
Related areas:
Blazor Documentation …
=> bug(BLAZ-27217):removed

blazor/tooltip/getting-started.md
In our Tooltip component, the Tooltip target is taken based on the HTML elements id or class name. When using the GUID as the target id for a tooltip, it is not possible to obtain an ID that begins with a digit. This is the current behavior of Tooltip component. 
So, I have added the additional information about Tooltip Target property
=> BLAZ-28030 : Additional information's were added

blazor/treegrid/how-to/editing-with-template-column.md
After editing a row, the value is not changed. The "Resources" field is not defined in the model class, but it is used in the column definition. So, this issue occurred.
=> documentation(BLAZ-27180):edit

blazor/appearance/themes.md
Description:
As certain components do not have support for NPM package reference feature, so they have been removed from the table.
=> documentation(BLAZ-28742): Removal of components from NPM package reference section's table

blazor/getting-started/maui-blazor-app.md
Description:
Details have been updated in Troubleshooting section for resolving the `Attempting to JIT compile method '...' while running in aot-only mode` issue that occurred while deploying certain Blazor component containing app on an iOS device.
=> documentation(BLAZ-28742): Need to update maui-blazor-app documentation's Troubleshooting section

blazor/common/adding-script-references.md, blazor/common/how-to/configure-blazor-component-in-bunit-testing.md, blazor/common/localization.md, blazor/getting-started/maui-blazor-app.md, blazor/rich-text-editor/paste-cleanup.md
Description:
The UG has been modified because Built-in JavaScript isolation has been removed since 21.1.* version.
Modified Adding Script References page.
Modified Localization page.
Getting started pages are already not using IgnoreScriptIsolation property.
=> documentation(823572): Need to modify the UG because Built-in JavaScript isolation has been remove since 21.1.* version

blazor/datetime-picker/getting-started.md
Remove the unwanted content from Getting Started with Blazor DateTimePicker Component.
=> Remove the unwanted content from Getting Started with Blazor DateTimePicker Component

blazor/common/how-to/create-blazor-webassembly-prerendering.md, blazor/diagram/connectors/segments/segments.md, blazor/scheduler/crud-actions.md, blazor/scheduler/working-hours.md
Hi @Aishwarya-Ganesan 
I have corrected the invalid links in our Blazor doc pages. Please check and merge the changes.
Thanks,
Mallika
=> SEO-175881: Corrected page not found link issue in Blazor doc

blazor/datagrid/columns.md
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/835302/
DataGrid column supports the following types:
* String
* Integer
* Double
* Long
* Decimal
* Boolean
* Date
* DateTime
* CheckBox
* DateOnly
* TimeOnly
> * If the [Type](https://help.syncfusion.com/cr/blazor/Syncfusion.Blazor.Grids.GridColumn.html#Syncfusion_Blazor_Grids_GridColumn_Type) is not defined, it will be determined from the first record of the [DataSource](https://help.syncfusion.com/cr/blazor/Syncfusion.Blazor.Grids.GridColumn.html). In case, if the first record of the [DataSource](https://help.syncfusion.com/cr/blazor/Syncfusion.Blazor.Grids.GridColumn.html) is null/blank value for a column then it is necessary to define the [Type](https://help.syncfusion.com/cr/blazor/Syncfusion.Blazor.Grids.GridC …
=> documentation(835302): Support to define different datatype (number types) at column level using Type property

blazor/button/how-to/html-attribute-support.md, blazor/button/how-to/tooltip-for-button.md
HtmlAttribute link was outdated  in Button UG
Button component component there is no HtmlAttribute property and it can be used direct button tag
Not consider Earlier
HtmlAttributes was directly assigned to button tag
-NA
No
HtmlAttributes was directly assigned to button tag
- HtmlAttribute
- Did you run the automation against your fix - Yes
- Is there any API name change - No
- Is there any existing behavior change of other features due to this code change - No
- Does your new code introduce new warnings or binding errors - NA
- Does your code pass all FxCop and StyleCop rules - NA
- Did you record this case in the unit test or UI test or B-unit
=> UG(857488) - Updated outdated HtmlAttribute link in Button UG

blazor/appearance/themes.md
**Root:**
Need to add notes section for "Can't find stylesheet to import" error when installing blazor theme.
**Solution:**
The notes section for "Can't find stylesheet to import" error has been added.
=> documentation(856202): Need to add notes section for "Can't find stylesheet to import" error when installing blazor theme

blazor/gantt-chart/data-binding.md
Changed the access modifier to the taskName property.
=> bug(859722): Console error occurs when editing taskname in observable collection sample

blazor-toc.html
862368: Path correction in query builder gets filtered records page.
=> 862368: Path correction in query builder gets filtered records page.

blazor/tooltip/template.md
I have changed the image URL link in the Blazor Tooltip template documentation sample.
=> documentation(ES-863462): Need to change the image URL link in the Blazor Tooltip template documentation sample

blazor/datagrid/column-rendering.md
Blaz-Remove-format-property-complex-column
=> Blaz-Remove-format-property-complex-column

blazor/file-upload/how-to/how-to-prevent-to-upload-or-remove-upload-file.md
Addressed the documentation correction in uploader component
=> Bug(BLAZ-869848) : Addressed the documentation correction in uploader component

blazor/datagrid/searching.md
Add the line to disable the warning and remove the unnecessary reference code
Content location:https://blazor.syncfusion.com/documentation/datagrid/searching
=> Blazor-869969-Need to modify the code to avoid displaying the warning BL0005 when using the grid instance searchsettings.key.

blazor/datagrid/accessibility.md
Documentation(870554)Accessibility-Revamp
=> Documentation(870554)Accessibility-Revamp

blazor/scheduler/editor-template.md
UG(ES-861836):  Clicked is spelled wrong in this event handler.
MoreEventsClicked="OnMoreEventsCliecked" Clicked is spelled wrong in this event handler
URL: https://blazor.syncfusion.com/documentation/scheduler/editor-template#how-to-prevent-the-display-of-popup-when-clicking-on-the-more-text-indicator
=> UG(ES-861836):  Clicked is spelled wrong in this event handler.

blazor/datagrid/column-validation.md, blazor/datagrid/custom-aggregate.md, blazor/datagrid/data-annotation.md, blazor/datagrid/print.md, blazor/datagrid/scrolling.md, blazor/datagrid/searching.md
878521-Blazor Grid Documentation code correction
=> 878521-Blazor Grid Documentation code correction

blazor/autocomplete/accessibility.md, blazor/calendar/accessibility.md, blazor/combobox/accessibility.md, blazor/datepicker/accessibility.md, blazor/daterangepicker/accessibility.md, blazor/datetime-picker/accessibility.md, blazor/dialog/accessibility.md, blazor/dropdown-list/accessibility.md, blazor/file-upload/accessibility.md, blazor/in-place-editor/accessibility.md, blazor/input-mask/accessibility.md, blazor/mention/accessibility.md, blazor/multiselect-dropdown/accessibility.md, blazor/numeric-textbox/accessibility.md, blazor/splitter/accessibility.md, blazor/textbox/accessibility.md, blazor/timepicker/accessibility.md, blazor/toast/accessibility.md
I modified the Accessibility UG documentation for Blazor components. The components list is given below,
1. AutoComplete
2. Calendar
3. Card
4. ComboBox
5. DatePicker
6. DateRangePicker
7. DateTimePicker
8. Dialog
9. DropDownList
10. File Upload
11. In-place Editor
12. Input Mask
13. Mention
14. MultiSelect Dropdown
15. NumericTextBox
16. Predefined Dialogs
17. Spinner
18. Splitter
19. TextBox
20. TimePicker
21. Toast
=> Update the Accessibility documentation for Blazor components

blazor-toc.html, blazor/datagrid/connecting-to-database/dapper.md, blazor/datagrid/connecting-to-database/sqlite-server.md
Documentation(878589)SQLite DataBinding
=> Documentation(878589)SQLite DataBinding

blazor/multiselect-dropdown/events.md
**Task: [UG documentation 883467](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/883467): OnChipTag event documentation missing**
The Clearing event is used instead of the OnChipTag event in the Blazor MultiSelect OnChipTag event documentation. We have now added the OnChipTag event code snippet.
=> 883467: Add OnChipTag event code snippet

blazor/pivot-table/state-persistence.md
The code snippets in the Blazor UG documentation's "Save and Load Pivot Layout" section are incorrect. The "pivot" declaration is missing from that section. To use the component instance, specify "SfPivotView<ProductDetails> pivot". So, we need to update the code example in the Blazor UG documentation section.
**Task link** : https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/883058
=> 883058: Need to update the sample code snippet for state persistence in the Blazor Pivot Table

blazor/pivot-table/events.md, blazor/pivot-table/row-and-column.md
Previously the current cell DOM element holds in "args.CurrentCell" property, and now it has been deprecated on our end due to C#'s limitations on DOM element modification. Thus, need to change the code snippet of the samples(CellClick, CellSelected and CellSelecting) that we have customized using args.currentCell.
**Task link** : https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/883058
=> 883098: Need to update the content for the cell click event in the UG Documentation

blazor/gantt-chart/scheduling-tasks.md
Console error occurs when loading working time range UG sample
Format of the bottom tier is not in a correct manner
So, corrected the bottom tier format in the correct manner.
Tag label `update-guideline-coreteam` or `update-guideline-productteam`.
The issue was already in the sample but now identified because of the code improvement.
If yes, provide the breaking commit details / MR here.
E2E: https://github.com/essential-studio/blazor-gantt-playwright-tests/blob/development/tests/Documentation/Scheduling%20tasks.spec.ts
Automation details - Mark `Is Automated` field as (Yes, Manual, Not Applicable) in corresponding JIRA task once the bug is automated.
Do the code changes cause any memory leak and performance issues? (Test only if you suspect that your code …
=> 886857: Console error occurs when loading working time range UG sample

blazor/diagram/methods.md, blazor/diagram/swimlane/lane/interaction.md
UG sample testing for volume 2, 2024 release
=> 886587:UG sample testing for volume 2, 2024 release

blazor/kanban/data-binding.md
Need to move the web service link into 'services.syncfusion.com' from 'ej2services.syncfusion.com
Updating the sample host URLs
No
No
Updating the sample host URLs
Yes
No
No
No
/label ~bug
=> 889328: Need to move the web service link into 'services.syncfusion.com' from 'ej2services.syncfusion.com

blazor/datagrid/batch-editing.md, blazor/datagrid/events.md
Changed the CellSaved event argument CellSaveArgs to CellSavedArgs
=> Blazor - DataGrid - Changed the CellSaved event argument CellSaveArgs to CellSavedArgs

blazor/otp-input/input-types.md, blazor/otp-input/placeholder.md, blazor/otp-input/styling-modes.md
Need to update otp images and placeholder value
None
NA
NA
=> docs(893176): otp images and placeholder value updated 

blazor/diagram/data-binding.md
Added UG documentation for the use case of rendering diagram layout with remote data from various Remotedata services using SFDatamanager for the following services
OData:[blazor.syncfusion.com/services/development/odata/DiagramOData](https://blazor.syncfusion.com/services/development/odata/DiagramOData)
ODataV4: [blazor.syncfusion.com/services/development/odata/DiagramODataV4](https://blazor.syncfusion.com/services/development/odata/DiagramODataV4)
URL: https://blazor.syncfusion.com/services/development/api/DiagramRemoteAPI
WebAPI : https://blazor.syncfusion.com/services/production/api/EmployeeDetails
=> 890869: UG documentation for remote data using various data adapters

blazor/rich-text-editor/toolbar.md
Need to validate and resolve the liquid exception in the toolbar.md file of the Blazor Docs repository.
I have checked the reported issue, and the issue occurred because the code highlight is not specified correctly. It hasn't added the code highlight start.
`{% tabs %}
{% highlight razor %}`
No
No
I have corrected the code highlight.
No
No
No
No
/label ~bug
=> 895522: We need to resolve the liquid exception in the toolbar.md file of the Blazor Docs repository.

blazor/pivot-table/getting-started-webapp.md, blazor/pivot-table/getting-started.md
Updated Getting Started UG Document in Blazor Pivot table
=> 894649: Updated Getting Started UG Document in Blazor Pivot Table-Hotfix

blazor/floating-action-button/getting-started.md
Hi @gowthamanthavasiyappan, kindly review my PR template below.
-- | --
Task Category | Blazor permanent redirect
Content Task Link/Mail Screenshot |  
Master/Dev PR | https://github.com/syncfusion-content/blazor-docs/pull/4610
Ticket/Task link | https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185614/
Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7B02737F02-3DE6-4A37-BEEE-4021A663ADB6%7D&file=Dickson.xlsx&action=default&mobileredirect=true&wdsle=0
</div>
</body>
</html>
Ex- https://github.com/syncfusion-content/blazor-docs/pull/4610
Title	Description
Task Category	React DateRangePicker FT improvements
Content Task Link/Mail Screenshot	
Master/Dev PR	
Ticket/Task link	
Work …
=> SEO-174654-Blazor-Permanent-Redirect-One

blazor/pivot-table/calculated-field.md, blazor/pivot-table/getting-started-webapp.md, blazor/pivot-table/getting-started.md
Updated the calculated-field note in Blazor
=> 894645: Updated the calculated-field note

blazor/diagram-classic/layout/radial-tree-layout.md
-- | --
|Task Category |  Coverage issues|
|Content Task Link/Mail Screenshot | NA |
|Hotfix | https://github.com/syncfusion-content/blazor-docs/pull/4635|
|Ticket/Task link |  https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/185658/|
|Work link | https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BD059EAE3-DA11-4570-A59B-D252A95C9DFD%7D&file=Faith.xlsx&action=default&mobileredirect=true&wdsle=0|
-- | --
=> 185658-Blazor-Diagram-classic

blazor/treegrid/data-binding.md
Updated Documentation for LoadChildOnDemand Sample In data binding 
Spec document 
Task link :https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/899148
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/899148
NA
Draft the test cases in excel and attach it in the MR itself. The automation must be covered based on this positive …
=> 899148: Update Documentation

blazor/textbox/getting-started-webapp.md, blazor/textbox/getting-started.md
[UG documentation 898985](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/898985): Need to use Blazor TextBox instead of CSS component
Previously, a CSS component was used to demonstrate how to add an icon to a TextBox component. Now, I have replaced it with Blazor TextBox using Razor and C# code.
=> 895343: Replaced Blazor TextBox code instead of CSS component

blazor/query-builder/columns-binding.md
905894: Updated the QueryBuilder operator "Does Not Start With" "Does Not End With" and "Does Not Contain" in UG documentation
=> 905894: Updated the QueryBuilder operator "Does Not Start With" "Does Not End With" and "Does Not Contain" in UG documentation

blazor/datagrid/cell-edit-types.md, blazor/datagrid/filtering.md
Documentation added for the task
BLAZ-907597 : Exception throws while save the record in multiselect edit template.
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/907597/
=> 907597: Fix the null exception for the multiselect.

blazor/ai-assistview/custom-view.md
Need to remove the promptRequested event added for viewTemplate sample.
NA
None
NA
NA
=> docs(903622): Added complete UG for the AI AssistView Component.

blazor-toc.html, blazor/multicolumn-combobox/code-snippet/popup-setting/popup-height.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/popup-resize.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/popup-width.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/popupclosed-event.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/popupclosing-event.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/popupopening-event.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/preventing-opening-closing.razor, blazor/multicolumn-combobox/code-snippet/popup-setting/show-popup-on-initial-loading.razor, blazor/multicolumn-combobox/getting-started-with-web-app.md, blazor/multicolumn-combobox/getting-started.md, blazor/multicolumn-combobox/popup-setting.md
Update the popup setting section in Multi column documentation.
=> 910110: Update the popup setting section in Multi column documentation.

blazor/gantt-chart/pdf-export.md
Added API links for PDF UG document
=> 908232: Added API link to PDF UG

blazor/diagram/tool-tip.md
=> 892862: Port UG

blazor/diagram/connectors/segments/bezier/bezier.md, blazor/diagram/connectors/segments/straight.md, blazor/diagram/tool-tip.md
=> 892868: Sub topics

blazor/datagrid/detail-template.md
The method name is incorrect so changed like this below .
Incorrect: DetailExpandAll
Correct: ExpandAllDetailRowAsync
=> Blaz 912400-method changed from 'DetailExpandAll' to 'ExpandAllDetailRowAsync

blazor-toc.html, blazor/rich-text-editor/how-to/update-value.md
Need to correct the update value documentation section
The issue occurs because in the key down method have the UIKeyboardEventArgs instead of KeyboardEventArgs 
No
No
The issue is resolved by changing the UIKeyboardEventArgs as KeyboardEventArgs and changed the corrected code.
No
No
NA
No
/label ~bug
=> 904096: Need to correct the update value documentation section

blazor/gantt-chart/managing-tasks.md
Bug description
When trying to edit the task name using the arrow down key in the cell edit template sample, it does not work.
=> 902827: Arrow down key is not working in cell edit template sample

blazor/image-editor/open-save.md
855683: ImageEditor UG content correction for Save the image as Byte Array sample
=> 855683: ImageEditor UG content correction for Save the image as Byte Array sample

blazor/gantt-chart/data-binding.md, blazor/gantt-chart/split-task.md
The segment template and expando object section in the UG changes modified and updated.
The previously attached code snippet did not include the label. We have now updated the code with the label and made the necessary changes.
Before code snippet O/P :
After code snippet changed O/P:
None
NA
NA
=> 914644: segment template sample modified

blazor/datagrid/column-validation.md
The field name is not specified in the ValidationRequested method, so it needs to be changed. It should be modified like this
HandleValidation(CurrentEditContext.Field("**Freight"**));
=> Blaz-917231Need to provide the field name in the custom validation ValidationRequested method.

blazor/treegrid/editing/column-validation.md
Issue 1: 
Bug-Description :
Alert popup is not working in Custom Validation Sample
In the treegrid, when clearing the "Duration" field and saving, its saved with an empty value ,without showing any alert 
message.
Root-Cause : 
In the custom validation logic which is present in the sample side, the if condition checks if its is only null value or not and 
then displays the alert message, which is wrong when entered with empty values.The expected alert message should be          
like "No value", when saving an empty value.
Reason:
Issue occurs in the custom validation logic ,where it doesn't validate whether the value is empty or not
Solution description : 
In the if condition present in the custom validation logic ,added a condition which checks for empty values along with null 
value. …
=> Documentation(69252) column validation

blazor/file-upload/chunk-upload.md
[UG documentation 920406](https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/920406): How can I get the chunk-index and total-chunk values from the file uploader in Asp.net
=> 920406: Added note for chunk-index and total-chunk

blazor/avatar/getting-started-with-web-app.md, blazor/avatar/getting-started.md
https://syncfusion.sharepoint.com/sites/WebFileManager/_layouts/15/Doc.aspx?sourcedoc={19b9a9f4-ec28-4b0a-8199-06e8b65b6a92}&action=edit&wd=target%28Testing%2FTesting%202023%20Volume%202.one%7Cae657d68-84d1-4d05-8714-823e2b1e830f%2FBlazor%20-%20Documentation%20testing%7Ca6b40384-eedc-45fb-af8b-6807fc0d4f0d%2F%29&wdorigin=NavigationUrl
The issue mentioned in the above one-note page need to be resolve.
Link for the Avatar component is mapped but it opens the same page.
Some of the queries are resolved in live documentation. 
For the link in Avatar component is mapped as Avatar demo. 
For the space issue in ListView is corrected for UI puprpose.
* [] Guidelines not followed. If yes, provide which guideline is not followed.
Tag label `update-guideline-coreteam` or …
=> 837836: Hyperlink not referred properly and alignment issue occurs in UG Blazor site

blazor/datagrid/filter-menu.md
Clear Filter issue resolved
_**Before the issue :**_
`  public async Task FilteringHandler(Syncfusion.Blazor.Grids.FilteringEventArgs args)
{
if (args.ColumnName == "OrderDate")
{
----------
}`
_**After the issue was resolved added the below code**_ 
`  public async Task FilteringHandler(Syncfusion.Blazor.Grids.FilteringEventArgs args)
{
if (args.ColumnName == "OrderDate" && args.FilterPredicates !=null)
{
----------------------------
}`
=> Blaz 929651-Clear filtering is not working, so it is necessary to handle the null case to prevent the condition

blazor/datagrid/filter-menu.md
Clear Filter issue resolved
_**Before the issue :**_
`  public async Task FilteringHandler(Syncfusion.Blazor.Grids.FilteringEventArgs args)
{
if (args.ColumnName == "OrderDate")
{
----------
}`
_**After the issue was resolved added the below code**_ 
`  public async Task FilteringHandler(Syncfusion.Blazor.Grids.FilteringEventArgs args)
{
if (args.ColumnName == "OrderDate" && args.FilterPredicates !=null)
{
----------------------------
}`
=> Blaz 929651-Clear filtering is not working, so it is necessary to handle the null case to prevent

blazor/listview/data-binding.md
Removed the SortBy property from ListViewFieldSettings.
In the below link, ListViewFieldSettings includes SortBy property. But it is not available in ListView.
https://blazor.syncfusion.com/documentation/listview/data-binding/#data-binding
API link for ListViewFieldSettings : https://help.syncfusion.com/cr/blazor/Syncfusion.Blazor.Lists.ListViewFieldSettings-1.html#properties
So, need to remove the field from the ListView documentation.
=> 105925: Removed the SortBy property from ListViewFieldSettings.

blazor-toc.html, blazor/rich-text-editor/code-snippet/xhtml-validation.razor, blazor/rich-text-editor/xhtml-validation.md
104941: Added the XHTML validation section in Blazor Rich Text Editor UG documentation(Dev)
=> 104941: Added the XHTML validation section in Blazor Rich Text Editor UG documentation(Dev)

blazor-toc.html, blazor/rich-text-editor/code-snippet/xhtml-validation.razor, blazor/rich-text-editor/xhtml-validation.md
104941: Added the XHTML validation section in Blazor Rich Text Editor UG documentation
=> 104941: Added the XHTML validation section in Blazor Rich Text Editor UG documentation

blazor/pdfviewer-2/form-designer/create-programmatically.md
Removed the Usage Sub tittle in FormDesigner Programmatic Documentation
=> 947270: Removed the Usage Sub tittle in FormDesigner Programmatic Documentation

blazor/range-slider/types.md
Description:
Updated the Slider Types related outdated content
Default – Allows to a single value in the Slider.
Min- Range – Allows to select a single value in the Slider. Its display’s a shadow from the start to the current value.
Range Slider - Allows to select a range of values in the Slider. It displays shadow in-between the selection range.
=> 901008: Updated the Slider Type definition.

blazor/datagrid/columns.md
Newly added the Removing hidden column elements from the DOM topic under the Columns section in the Blazor documentation.
=> 949462: Included Removing hidden column elements from the DOM topic in Blazor UG

blazor/diagram/interaction.md
Hi @MallikaRK 
|--|--|
|Task Category| Blazor Duplicate title and H1|
|Content Task Link/Mail Screenshot| ![image](https://github.com/user-attachments/assets/ebc9fe72-523e-417a-8709-105d3595fb68) ![image](https://github.com/user-attachments/assets/c5b85a01-6fe7-45ce-841e-b7c0e19f2fdb)|
|UX task| NA|
|Dev PR link| N/A|
|Ticket/Task link| |
-- | -- |
Fixed the duplicate title and H1| To avoid duplicate meta elements in different documentation pages|
Regards,
Dickson
=> SEO-174654-Duplicate-Title-Issue-Fix

blazor/datagrid/column-rendering.md, blazor/datagrid/column-template.md, blazor/datagrid/foreignKey-column.md
1.Complex column with foreign key column
Sample: https://blazorplayground.syncfusion.com/embed/LtBoXTisskOldOAN?appbar=true&editor=true&result=true&errorlist=true&theme=bootstrap5
2.Radio button component
sample: https://blazorplayground.syncfusion.com/embed/rZheXoNwgrBgAFeR?appbar=true&editor=true&result=true&errorlist=true&theme=bootstrap5
3.Render foreign key value in column template
Sample: https://blazorplayground.syncfusion.com/embed/VNVSXotQVxiXwxXo?appbar=true&editor=true&result=true&errorlist=true&theme=bootstrap5
=> 952312: Added the topic of How to set complex column as foreign key colum

blazor/otp-input/getting-started-webapp.md, blazor/pdfviewer/annotation/stamp-annotation.md, blazor/radio-button/getting-started.md, blazor/sidebar/getting-started.md, blazor/tabs/getting-started-webapp.md
@MallikaRK 
|--|--|
|Task Category|Coverage-Blazor- Page with redirect-docs|
|UX task| NA|
|Hotfix PR| https://github.com/syncfusion-content/blazor-docs/pull/6006|
|Ticket/Task link| https://dev.azure.com/Syncfusion-Infrastructure/Syncfusion%20SEO/_workitems/edit/201908/|
|Excel/SharePoint link|https://syncfusion.sharepoint.com/:x:/r/sites/SEOWebsiteAuditing/_layouts/15/Doc.aspx?sourcedoc=%7BB6F5F271-B5FF-4E65-A3B5-BAE6D5BA14EB%7D&file=Blazor%20page%20with%20redirect.xlsx&action=default&mobileredirect=true |
|--|--|
Regards,
Hillary
=> SEO-201908-blazor-page-with-redirect-docs3

blazor/getting-started/razor-class-library.md
* Updated Razor class library related UG
* Updated net6 and net7 to net 8 and net 9
=> 937492: Remove net6 and net7 reference in UG

blazor/datagrid/foreignKey-column.md
Syntax Error: In datagrid ```razor was used which is not the correct standard.
=> Syntax Error: In datagrid ```razor was used which is not the correct standard.

blazor/chip/style.md
Customizing chip icon is not proper in documentation https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/968312
=> Customizing chip icon is not proper in documentation

blazor/treegrid/clipboard.md, blazor/treegrid/columns/column-chooser.md, blazor/treegrid/columns/columns.md, blazor/treegrid/context-menu.md, blazor/treegrid/editing/batch-editing.md, blazor/treegrid/editing/dialog-editing.md, blazor/treegrid/editing/edit.md, blazor/treegrid/events.md, blazor/treegrid/excel-export.md, blazor/treegrid/exporting.md, blazor/treegrid/filtering/filter-bar.md, blazor/treegrid/filtering/filtering.md, blazor/treegrid/how-to/access-public-methods.md, blazor/treegrid/how-to/custom-control-in-treegrid-toolbar.md, blazor/treegrid/how-to/row-cell-index.md, blazor/treegrid/how-to/select-treegrid-rows-based-on-condition.md, blazor/treegrid/how-to/single-click-editing-with-batch-mode.md, blazor/treegrid/how-to/tool-bar-with-drop-down-list.md, blazor/treegrid/print.md, blazor/treegrid/rows/row-drag-and-drop.md, blazor/treegrid/searching.md, blazor/treegrid/selection.md, blazor/treegrid/sorting.md, blazor/treegrid/toolbar.md, blazor/treegrid/virtualization.md
=> 983313: Files update.

blazor/3D-chart/working-with-data.md, blazor/circular-gauge/how-to/place-gauge-inside-other-components.md, blazor/circular-gauge/pointers.md, blazor/circular-gauge/ranges.md
Removed the improper playground samples in 3D Chart and Circular Gauge.
=> 982808: Removed the improper playground samples in 3D Chart and Circular Gauge.

blazor/ai-assistview/ai-integrations/gemini-integration.md, blazor/ai-assistview/ai-integrations/openai-integration.md, blazor/chat-ui/ai-integrations/gemini-integration.md, blazor/chat-ui/ai-integrations/openai-integration.md
Description
Need to update the contents of the ai-integrations samples
Gemini integration
Azure Openai
=> 982891: Update the ai-integrations contents

blazor/dialog/getting-started-with-web-app.md, blazor/dialog/getting-started.md
Correct the preview output in Blazor Dialog Getting Started UG
https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/984091
https://support.syncfusion.com/agent/tickets/771145
Previously, the preview output in the Blazor Dialog Getting Started UG was wrongly updated; now the preview sample is updated correctly.
=> 984091: Need to correct the preview output in Blazor Dialog Getting Started UG

blazor/smith-chart/accessibility.md, blazor/smith-chart/events.md, blazor/smith-chart/smith-chart-axis.md, blazor/smith-chart/smith-chart-dimensions.md, blazor/smith-chart/smith-chart-legend.md, blazor/smith-chart/smith-chart-marker.md, blazor/smith-chart/smith-chart-print.md, blazor/smith-chart/smith-chart-series.md, blazor/smith-chart/smith-chart-tool-tip.md, blazor/smith-chart/title-subtitle.md
- Complete the UG content and example changes/corrections in the Smith chart control.
=> 983838: Updated the UG content and example changes in the Smith chart control.
