blazor/listbox/accessibility.md
blazor/listbox/data-binding.md
blazor/listbox/drag-and-drop.md
blazor/listbox/dual-listbox.md
blazor/listbox/getting-started.md
blazor/listbox/how-to/add-items.md
blazor/listbox/how-to/bind-change-event.md
blazor/listbox/how-to/enable-or-disable-items.md
blazor/listbox/how-to/enable-scroll.md
blazor/listbox/how-to/select-items.md
blazor/listbox/icons-and-templates.md
blazor/listbox/selection.md
blazor/listbox/sorting-grouping.md
blazor/listbox/style-and-appearance.md
blazor/maps/providers/bing-maps.md
blazor/maps/providers/openstreetmap.md
blazor/maps/providers/other-maps.md

Reviewed listbox files in Blazor

BLAZ-20133 Reviewed listbox files in Blazor

---

blazor/linear-gauge/accessibility.md
blazor/linear-gauge/annotations.md
blazor/linear-gauge/axis.md
blazor/linear-gauge/events.md
blazor/linear-gauge/getting-started.md
blazor/linear-gauge/internationalization.md
blazor/linear-gauge/linear-gauge-appearance.md
blazor/linear-gauge/linear-gauge-dimensions.md
blazor/linear-gauge/methods.md
blazor/linear-gauge/pointers.md
blazor/linear-gauge/print.md
blazor/linear-gauge/ranges.md
blazor/linear-gauge/user-interaction.md

BLAZ-20133 Reviewed linear gauge

---

blazor/appearance/themes.md

Modified the content for the errors in live site

documentation(BLAZ-4730): updating the changes

---

blazor/appearance/themes.md

documentation(BLAZ-4730): modified changes

---

blazor/pivot-table/conditional-formatting.md
blazor/pivot-table/row-and-column.md

Tutorial video for Blazor Pivot Table features added.

documentation(EJ2-57226): Tutorial video for Blazor Pivot Table features added.

---

blazor/scheduler/accessibility.md

updated the keyboard accessibility content

documentation(BLAZ-20199): Updating accessibility

---

blazor/autocomplete/grouping.md
blazor/combobox/data-source.md
blazor/combobox/grouping.md
blazor/dialog/animation.md
blazor/dialog/draggable.md
blazor/dialog/resize.md
blazor/dialog/template.md
blazor/dropdown-list/data-source.md
blazor/dropdown-list/grouping.md
blazor/dropdown-list/templates.md
blazor/listbox/sorting-grouping.md
blazor/multiselect-dropdown/checkbox.md
blazor/multiselect-dropdown/getting-started.md
blazor/multiselect-dropdown/grouping.md
blazor/multiselect-dropdown/templates.md

**Adding YouTube tutorials**
- How to Filter and Group the Blazor AutoComplete Items - XtqNSV0B3h8
- Customize Blazor MultiSelect Dropdown Items Using Templates - 6A61PDatD0s
- How to Filter and Group the Blazor MultiSelect Dropdown Items - 9PRq4u-t2Yw
- Add a MultiSelect Dropdown to a Blazor WebAssembly App - vS4NNQBJ0p4
- How to Group the Blazor ListBox Items - Ja_UJva-cHA
- How to Create a Cascading Dropdown List in Blazor - N_xI_aE76C0
- How to Create a Cascading ComboBox in Blazor – zGGntfBPQNI
- How to Filter and Group the Blazor ComboBox Items - 2UuJzgfbi48
- How to Filter and Group the Blazor Dropdown List Items - 9Ouje7KEOEU
- How to Drag, Resize, and Animate the Blazor Dialog Control - qNW5d7C2L7g
- Customize the Appearance of Blazor Dialog Using Templates - K5o9JWbgjvQ

documentation(BLAZ-20486): Adding youtube tutorials and linking forums

---

blazor-toc.html
blazor/document-editor/bookmark.md
blazor/document-editor/comments.md
blazor/document-editor/form-fields.md
blazor/document-editor/getting-started/client-side-application.md
blazor/document-editor/getting-started/server-side-application.md
blazor/document-editor/how-to/change-document-view.md
blazor/document-editor/how-to/customize-context-menu.md
blazor/document-editor/how-to/customize-tool-bar.md
blazor/document-editor/how-to/disable-optimized-text-measuring.md
blazor/document-editor/how-to/export-document-as-pdf.md
blazor/document-editor/how-to/get-the-selected-content.md
blazor/document-editor/how-to/read-only-default.md
blazor/document-editor/how-to/resize-document-editor.md
blazor/document-editor/how-to/show-hide-spinner.md
blazor/document-editor/image.md
blazor/document-editor/link.md
blazor/document-editor/styles.md
blazor/document-editor/table-format.md
blazor/document-editor/table-of-contents.md
blazor/document-editor/track-changes.md

documentation(BLAZ-19814): Updated documentation to hotfix

documentation(BLAZ-19814): Updated documentation to hotfix

---

blazor/document-editor/getting-started/features.md
blazor/document-editor/how-to/export-document-as-pdf.md

documentation(BLAZ-19814): Updated overview page

---

blazor/combobox/accessibility.md
blazor/combobox/custom-value.md
blazor/combobox/data-binding.md
blazor/combobox/data-source.md
blazor/combobox/events.md
blazor/combobox/filtering.md
blazor/combobox/getting-started.md
blazor/combobox/grouping.md
blazor/combobox/how-to/tooltip.md
blazor/combobox/localization.md
blazor/combobox/native-events.md
blazor/combobox/style.md
blazor/combobox/templates.md
blazor/combobox/virtualization.md
blazor/context-menu/accessibility.md
blazor/context-menu/customizing-and-multilevel-nesting.md
blazor/context-menu/getting-started.md
blazor/context-menu/how-to/bind-menu-events.md
blazor/context-menu/how-to/change-animation-settings.md
blazor/context-menu/how-to/data-binding.md
blazor/context-menu/how-to/enable-or-disable-context-menu-items.md
blazor/context-menu/how-to/open-and-close-context-menu.md
blazor/context-menu/how-to/open-dialog.md
blazor/context-menu/icons-and-navigations.md

documetation(BLAZ-20028): Reviewed the contents of combo box and context-menu.

---

blazor-toc.html
blazor/document-editor/form-fields.md
blazor/document-editor/getting-started/overview.md
blazor/document-editor/how-to/disable-optimized-text-measuring.md
blazor/document-editor/how-to/export-document-as-pdf.md
blazor/document-editor/link.md

documentation(BLAZ-19814):  Updated documenteditor correction

documentation(BLAZ-19814):  Updated documenteditor correction

---

blazor/rich-text-editor/link.md

documentation(BLAZ-20712): Explained about EnableAutoUrl property in RTE

documentation(BLAZ-20712): Explained about EnableAutoUrl property in RTE

---

blazor/card/horizontal.md

adding card virtualization forum in UG

documentation(BLAZ-20486): adding card virtualization in UG

---

blazor/drop-down-menu/getting-started.md
blazor/listbox/icons-and-templates.md
blazor/progress-button/getting-started.md

Adding the youtube  video for progress button and dropdown-menu in UG documentation.

documentation(BLAZ-20492): Adding the youtube video to dropdown menu and progress button.

---

blazor/gantt-chart/data-binding.md

Updated the Handling Http error sample code in documentation

Documentation(BLAZ-18290): HandlingHttpError

---

blazor/file-upload/async.md

Adding see also section for how to  upload files to database in Blazor

documentation(BLAZ-20486): upload files to DB

---

blazor/common/localization.md

MD to html conversion issue fixed.

BLAZ-100 MD to html conversion issue fixed. 

---

blazor/common/localization.md

BLAZ-100 localization changes committed.

BLAZ-100 localization changes committed.

---

blazor/split-button/getting-started.md

Adding the youtube video for split button in UG documentation.

documentation(BLAZ-20492): Adding the youtube video to split button.

---

blazor/common/localization.md

BLAZ-100 MD to html conversion issue fixed.

BLAZ-100 MD to html conversion issue fixed.

---

blazor/common/localization.md

Reviewed the content in localization in Blazor

BLAZ-19185 Reviewed the content in Localization in Blazor

---

blazor/spinner/getting-started.md

documentation(BLAZ-21361): Added the Blazor Spinner video to the UG.

documentation(BLAZ-21361): Added the Blazor Spinner video to the UG.

---

blazor/barcode/barcodeGenerator.md
blazor/barcode/datamatrixgenerator.md
blazor/barcode/export.md
blazor/barcode/getting-started.md
blazor/barcode/qrcodegenerator.md
blazor/diagram-component/serialization.md

I have corrected the error codes and committed.
Regards,
Ranjitha A.

BLAZ-20943 Barcode error codes hotfix

---

blazor/kanban/cards.md
blazor/kanban/data-binding.md
blazor/kanban/dialog.md
blazor/kanban/dimensions.md
blazor/kanban/events.md
blazor/kanban/getting-started.md
blazor/kanban/responsive-mode.md
blazor/kanban/sort.md
blazor/kanban/swimlane.md
blazor/kanban/workflow.md

Please review the interlinking changes for the Blazor kanban board.
Regards,
Girija R.

SEO-2079-Blazor kanban interlinking

---

blazor/common/cdn-fallback.md

Blazor UG CDN fallback changes committed.

documentation(BLAZ-20240): Blazor UG CDN fallback changes committed.

---

blazor-toc.html
blazor/common/adding-script-references.md
blazor/common/cdn-fallback.md

Blazor UG CDN fallback changes moved to hotfix.

documentation(BLAZ-20240): Blazor UG CDN fallback changes moved to hotfix.

---

blazor/appearance/themes.md

BLAZ-100 fluent theme reference added

---

blazor/common/adding-script-references.md
blazor/common/cdn-fallback.md

Hotfix to dev branch conflicts resolved.

documentation(BLAZ-20240): Hotfix to dev branch conflicts resolved.

---

blazor/common/cdn-fallback.md

Blazor CDN fallback changes committed.

documentation(BLAZ-20240): Blazor CDN fallback changes committed.

---

blazor/common/adding-script-references.md

BLAZ-100 - Warning added for un-version cdn links usage.

BLAZ-100 - Warning added for un-version cdn links usage.

---

blazor/document-editor/getting-started/client-side-application.md
blazor/document-editor/getting-started/server-side-application.md

1. Added link to generate custom resource for using Document Editor with other syncfusion blazor component

documentation(EJ2-58572): Added documentation for custom script genertor

---

blazor/signature/customization.md
blazor/signature/draw.md
blazor/signature/how-to/integration-toolbar.md
blazor/signature/open-save.md
blazor/signature/user-interaction.md

UG documentation content correction for signature component.

documentation(EJ2-58632): UG documentation content correction for signature.

---

blazor/dropdown-list/getting-started.md
blazor/dropdown-list/how-to/blazor-web-assembly-dropdown-list.md
blazor/multiselect-dropdown/getting-started.md
blazor/multiselect-dropdown/how-to/blazor-web-assembly-multiselect-dropdown.md

Could you also please review and merge the below pull request

SEO-1969-Doc-updates-howto-section-added

---

blazor/autocomplete/getting-started.md
blazor/autocomplete/how-to/blazor-web-assembly-autocomplete.md
blazor/listbox/getting-started.md
blazor/listbox/how-to/blazor-web-assembly-listbox.md

Could you also please review and merge the below pull request

SEO-2006-Updates-Blazor-MoneyKeywords-AutoComplete-ListBox

---

blazor/linear-gauge/pointers.md
blazor/maps/accessibility.md
blazor/maps/layers.md
blazor/maps/user-interactions.md

content changes for maps.
we did not consider before.
This scenario is not identified earlier.
This scenario is not identified earlier.
NA.
E2E test case / Manual testing
No
content changes for maps.
NA
No areas affected.
- Did you run the automation against your fix? <b> Yes </b>
- Is there any API name change? <b> No </b>
- Is there any existing behavior change of other features due to this code change? <b> No </b>
- Did you record this case in the unit test or UI test? <b> No </b>
- Did you added issue fix comment? <b> No </b>
- Did you tested this issue fix for all browsers? <b> [x] Chrome [x] Firefox [x] Edge [x] Internet Explorer </b>
- Does it have any known issues? <b> No </b>

bug(EJ2-59028): content changes for maps.

---

blazor/textbox/validation.md

Added code snippet in validation

documentation(BLAZ-21751): Added code snippet in validation

---

blazor/datagrid/paging.md

documentation(BLAZ-21465): Documentation link added

---

blazor/datetime-picker/data-binding.md

Event Added in Datetime picker

documentation(BLAZ-21695): Event Added

---

blazor/gantt-chart/task-dependencies.md

documentation(BLAZ-21731): UG for predecessor configuration

---

blazor/chart/axis-labels.md
blazor/datagrid/excel-exporting.md

documentation(BLAZ-21920): sample Added

---

blazor/datagrid/excel-like-filter.md

Reviewed excel-like filter in Datagrid

DOC-4263 Reviewed Excel-like filter file in Datagrid

---

blazor/treegrid/custom-binding.md

added notes for custom binding

documentation(blaz-22183): added notes for custom binding

---

blazor/treegrid/custom-binding.md

added notes for custom binding in tree grid

documentation(blaz-22183): added notes for custom binding in tree grid

---

blazor/breadcrumb/overflow.md

Conflicts Issue breadcrumb component has been resolved.

(EJ2-22511):Conflicts Issue breadcrumb component has been resolved.

---

blazor/gantt-chart/context-menu.md

documentation(blaz-8888): updated hotfix to dev gantt

---

blazor-toc.html

documentation(BLAZ-22344): html link added

---

blazor/maps/populate-data.md

Committed code snippet changes.

bug(BLAZ-22363): Committed code snippet changes.

---

blazor/check-box/how-to/checkbox-model-binding.md

Compilation error occurs while running the checkbox model binding sample has been resolved.

(BLAZ-18514):Compilation error occurs while running the checkbox model binding sample has been resolved.

---

blazor/button-group/getting-started.md

Please review the changes for the Blazor Button Group.
Regards,
Yvone.

SEO-1994 Blazor Button Group interlinking 

---

blazor/pdfviewer/getting-started/web-assembly-application.md

Update PDF Viewer services in GitHub

bug(EJ2-59059): Update PDF Viewer services in GitHub

---

blazor/gantt-chart/context-menu.md

Missed topics add for Context menu in Gantt.
Topics added:
- Built-in and custom context menu items.
- Sub context menu items in Gantt.
- Disable the Context menu for specific columns in Gantt
- Disable context menu items for Gantt dynamically

bug(Blaz-5301): AddContextMenu

---

blazor/drop-down-menu/getting-started.md

Please review the changes for the Blazor Dropdown Menu.
Regards,
Yvone.

SEO-1994 Blazor Dropdown Menu Interlinking

---

blazor/split-button/getting-started.md
blazor/split-button/icons.md

Please find the changes for Blazor Split Button Interlinking changes.
Regards,
Yvone.

SEO-1994 Blazor Split Button Interlinking

---

blazor/listview/check-list.md
blazor/listview/getting-started.md

Please review the changes for Blazor ListView Interlinking.
Regards,
Yvone.

SEO-1994 Blazor ListView Interlinking Changes

---

blazor/toast/getting-started.md

Please review the changes made for Blazor Toast Interlinking.
Regards,
Yvone.

SEO-2024 Blazor Toast Interlinking

---

blazor/menu-bar/accessibility.md
blazor/menu-bar/data-source-binding-and-custom-menu-items.md
blazor/menu-bar/getting-started.md

Please review the Interlinking changes on Blazor menu-Bar.
Regards,
@Sharly-Atieno .

SEO-1997- Blazor Menu Bar Interlinking

---

blazor/context-menu/customizing-and-multilevel-nesting.md
blazor/context-menu/getting-started.md
blazor/context-menu/icons-and-navigations.md
blazor/context-menu/style-and-appearance.md

Please review the Interlinking changes for the Blazor Context menu.
Regards,
@Sharly-Atieno .

SEO-1731-Blazor Context Menu Interlinking

---

blazor/breadcrumb/breadcrumb-items.md
blazor/breadcrumb/getting-started.md
blazor/breadcrumb/icons.md
blazor/breadcrumb/navigation.md
blazor/breadcrumb/overflow.md

Please review the Interlinking changes for the Blazor Breadcrumb.
Regards,
@Sharly-Atieno .

SEO-1731-Blazor Breadcrumb Interlinking

---

blazor/toolbar/accessibility.md
blazor/toolbar/getting-started.md
blazor/toolbar/item-configuration.md

Please review the interlinking changes for the blazor toolbar.
Regards,
@Sharly-Atieno

SEO-1731-Blazor Toolbar Interlinking

---

blazor/common/data-binding/bind-entity-framework.md
blazor/common/data-binding/dapper-databinding.md
blazor/common/data-binding/restful-service-binding.md
blazor/common/data-binding/sql-server-data-binding.md
blazor/common/data-binding/webapi-service-binding.md

documentation(BLAZ-20520): Updating content for .NET6 

---

blazor/toast/config.md

Added topic in toast component

documentation(BLAZ-22358): Added topic in toast component

---

blazor/tabs/accessibility.md
blazor/tabs/animations.md
blazor/tabs/content-render-modes.md
blazor/tabs/drag-and-drop.md
blazor/tabs/getting-started.md

Please review the interlinking changes for the Blazor Tabs.
Regards,
@Sharly-Atieno .

SEO-1997-Blazor Tabs Interlinking

---

blazor/sidebar/auto-close.md
blazor/sidebar/custom-context.md
blazor/sidebar/docking-sidebar.md
blazor/sidebar/getting-started.md

Please review the Interlinking changes for the Blazor Sidebar.
Regards,
Sharly-Atieno

SEO-1731-Blazor Sidebar Interlinking 

---

blazor/signature/customization.md
blazor/signature/draw.md
blazor/signature/getting-started.md
blazor/signature/open-save.md
blazor/signature/user-interaction.md

Please review the Interlinking changes for the Blazor Signature.
Regards,
Sharly A.

SEO-1731-Blazor signature interlinking

---

blazor/check-box/getting-started.md
blazor/check-box/label-and-size.md
blazor/check-box/style-and-appearance.md

Please review the Interlinking changes for the Blazor Checkbox.
Regards,
Sharly A.

SEO-2087-Blazor Checkbox Interlinking changes

---

blazor/sparkline/dimensions.md
blazor/sparkline/getting-started.md

Please review the interlinking changes for Blazor Sparkline Chart.
Regards,
Sharly A.

SEO-2125-Blazor Sparkline Chart Interlinking

---

blazor/splitter/getting-started.md

Hi @christoIsaac,
Please find changes made on Blazor Splitter Interlinking.
Regards,
@scholar jaruha

SEO-1996 Blazor Splitter Interlinking

---

blazor-toc.html

Committed toc file changes in blazor docs.

bug(BLAZ-22988): Committed toc file changes in blazor docs.

---

blazor/kanban/events.md

documentation(BLAZ-23101): TValue added in the KanbanEvents tag

documentation(BLAZ-23101): TValue added in the KanbanEvents tag

---

blazor/progress-button/getting-started.md

Please review the changes for Blazor Progress Button Interlinking.
Regards,
Yvone.

SEO-1994 Blazor Progress Button interlinking

---

blazor/toggle-switch-button/getting-started.md

Please review the changes for Blazor Toggle Switch Button Interlinking Changes.
Regards,
Yvone.

SEO-2024 Blazor Toggle Switch Button Interlinking Changes

---

blazor/progress-bar/getting-started.md

Please find changes made on Blazor ProgressBar Interlinking.
Regards,

SEO-2298 Blazor ProgressBar Interlinking changes

---

blazor/radio-button/getting-started.md

Please find changes made on blazor radio button interlinking.
Regards,

SEO-2336 Blazor Radio Button Interlinking

---

blazor/button/getting-started.md

Please find changes made on blazor button interlinking.
Regards,

SEO-2336 Blazor Button Changes

---

blazor/card/getting-started.md
blazor/dialog/getting-started.md
blazor/progress-bar/getting-started.md
blazor/spinner/getting-started.md
blazor/tooltip/getting-started.md

Please find changes made on blazor interlinking.
Regards,

SEO-2336 Blazor Interlinking

---

blazor/timepicker/getting-started.md

Please find changes made on blazor timepicker interlinking.
Regards,

SEO-2128 Blazor TimePicker Interlinking Changes

---

blazor/splitter/getting-started.md

Please find changes made on blazor splitter interlinking.
Regards,

SEO-2336 Blazor Splitter Changes

---

blazor/treegrid/virtualization.md

Have given support for the **frozen column in virtualization**. So removing the line from limitations.

story(BLAZ-23749): Removed the frozen column limitation in Virtualization documentation.

---

blazor/datetime-picker/getting-started.md

Please review the changes for Blazor DateTime Picker Interlinking.
Regards,
Yvone.

SEO-2024 Blazor DateTime Picker Interlinking

---

blazor/treegrid/rows.md

IsPrimaryKey added in code snippets and in Notes section

documentation(BLAZ-17750): Fixed

---

blazor/combobox/events.md

documentation(BLAZ-23701): changed the code block based on actioncomplete event method handler.

documentation(BLAZ-23701): changed the code block based on actioncomplete event method handler.

---

blazor/treegrid/selection.md

Have added the highlight tab in drag selection UG.

doc(BLAZ-23750): Dragselection Changes

---

blazor/stock-chart/getting-started.md

Updated changes to resolve build error

documentation(BLAZ-23707): modified content

---

blazor/common/adding-script-references.md

Drafted the individual blazor script component wise support for blazor docs

documentation(BLAZ-23879): Drafted the individual blazor script component wise support for blazor docs

---

blazor/rich-text-editor/exec-command.md

documentation(BLAZ-17216): Review comments addressed

---

blazor/common/adding-script-references.md

Modified the table data bold letters to normal text in script reference topic

documentation(BLAZ-23879): Modified the table data bold letters to normal text in script reference topic

---

blazor/barcode/barcodeGenerator.md
blazor/barcode/qrcodegenerator.md

I have updated the enablechecksum and errorcorrectionlevel properties in ug and committed. Please review the changes.
Regards,
Ranjitha A.

BLAZ-23149 Barcode changes for hotfix branch

---

blazor/scheduler/appointments.md

Issue:
Multi dragging is not working in mobile mode
Solution: 
Added a note in the Documentation for Drag and Drop Multiple Appointments

Documentation(BLAZ-23257):Multi dragging is not working in mobile mode

---

blazor/pivot-table/events.md
blazor/pivot-table/excel-export.md
blazor/pivot-table/pdf-export.md
blazor/pivot-table/tool-bar.md

Pivot table documentation mistakes changed

Doc(BLAZ-21725):Pivot table Mistakes changed.

---

blazor/rich-text-editor/exec-command.md

Execute command alignment issue resolved-Hotfix

documentation(BLAZ-17216): Execute command alignment issue resolved-Hotfix

---

blazor/scheduler/appointments.md

Issue:
Multi dragging is not working in mobile mode
Solution: 
Added a note in the Documentation for Drag and Drop Multiple Appointments

Documentation(BLAZ-23257): Multi dragging is not working in mobile mode

---

blazor/scheduler/context-menu.md

Documentation for the context menu support has been completed.

documentation(BLAZ-23880): UG documentation for context menu support

---

blazor-toc.html

Hi sir @Keerthivasan-Ramamoorthy,
I've made the navigation link changes and committed them

Documentation(BLAZ-23700):Navigation change for expand collapse document

---

blazor/pivot-table/events.md

toolbar rendered event code snippet altered.

Doc(BLAZ-23907):toolbar rendered event code snippet altered.

---

blazor/carousel/animations-and-transitions.md

Documentation Description:
Include UG documentation for newly added features in carousal component
Issues:
Alignment error in sub headings for custom animation
Solution:
Align the custom animation heading as like fade animation

documentation(BLAZ-24088):Include the UG documentation for newly add features

---

blazor/range-selector/getting-started.md

Please review the changes for Blazor Range Selector Interlinking changes.
Regards,
Yvone.

SEO-2100-Blazor Range Selector Interlinking changes

---

blazor/gantt-chart/column-reordering.md
blazor/gantt-chart/top-tier-and-bottom-tier.md

Review the changes in UG documentation

documentation(BLAZ-24166): Review the changes in UG documentation

---

blazor/scheduler/appointments.md

Appointment topics has been improved by adding API link to all properties and gives proper notes section in documentation.

documentation(BLAZ-22258): improve the Appointments topic in ug documentation

---

blazor/scheduler/appointments.md

Changed the notes section for recurrence rule in appointment topic

documentation(BLAZ-22258): addressed review comments in Appointments topic in ug documentation

---

blazor/rich-text-editor/accessibility.md

documentation(BLAZ-17216): Changed code block from razor to cshtml

documentation(BLAZ-17216): Changed code block from razor to cshtml

---

blazor/upgrade/release-history.md

documentation(BLAZ-20617): Updated spelling mistake

---

blazor/treegrid/virtualization.md

Resolved the indent documentation changes in blazor virtualization topic

doc(BLAZ-24183): resolve topic indentation

---

blazor/menu-bar/how-to/customize-menu-using-events.md

UG correction for Menubar component.

(EJ2-62118):UG correction for Menubar component.

---

blazor/treegrid/virtualization.md

Resolved the indentation changes for the limitation topic in the virtualization topic.

doc(BLAZ-24183): Resolved indentation

---

blazor/rich-text-editor/accessibility.md

documentation(BLAZ-17216): Resolved build failure

---

blazor-toc.html
blazor/common/animation.md

https://github.com/syncfusion-content/blazor-docs/pull/1163

documentation(BLAZ-23855): commit for update file names of global animation - hotfix

---

blazor/rich-text-editor/import-export.md

Import export heading issue has been resolved - Hotfix

documentation(BLAZ-23476): Import export heading issue has been resolved - Hotfix

---

blazor/treegrid/column-validation.md
blazor/treegrid/data-binding.md

documentation(blaz-24573): added missing code snippets

---

blazor/treegrid/searching.md

documentation(blaz-24573): compilation error resolved

documentation(blaz-24573): compilation error

---

blazor-toc.html
blazor/scheduler/how-to/different-work-hours-for-each-days.md
blazor/scheduler/how-to/set-different-work-hours-for-each-resources.md

Added a new topic for setting up different work hours for each days of the each resource in blazor scheduler.

documentation(BLAZ-24950): Different work hours

---

blazor/document-editor/clipboard.md
blazor/document-editor/find-and-replace.md
blazor/document-editor/header-footer.md
blazor/document-editor/history.md
blazor/document-editor/image.md
blazor/document-editor/list-format.md
blazor/document-editor/saving-document.md
blazor/document-editor/styles.md
blazor/document-editor/table-format.md
blazor/document-editor/table-of-contents.md
blazor/document-editor/table.md

[documentation(BLAZ-25495): Updated Async API changes](https://github.com/syncfusion-content/blazor-docs/commit/b6523e7bff88815c8846c3b2c3eb3dd4d0fe7c86)

documentation(BLAZ-25495): Updated Async API changes

---

blazor-toc.html
blazor/pdfviewer/annotation/comments.md
blazor/pdfviewer/annotation/import-export-annotation.md
blazor/pdfviewer/annotation/stamp-annotation.md
blazor/pdfviewer/download.md
blazor/pdfviewer/events.md
blazor/pdfviewer/how-to/check-status-of-annotations-or-comments.md
blazor/pdfviewer/how-to/create-pdf-viewer.md
blazor/pdfviewer/how-to/create-pdfviewer-in-a-popup-window.md
blazor/pdfviewer/how-to/customize-arrow-annotation-heads.md
blazor/pdfviewer/how-to/import-annotations-as-objects.md
blazor/pdfviewer/how-to/increase-connection-buffer-size.md
blazor/pdfviewer/how-to/load-pdf-document-dynamically.md
blazor/pdfviewer/how-to/print-the-PDFViewer-inside-the-Dialog-component.md
blazor/pdfviewer/how-to/show-or-hide-pdfviewer-dynamically.md
blazor/pdfviewer/opening-pdf-file.md
blazor/pdfviewer/toolbar-customization.md

I have added the sample links for the existing topics and added new md file for "How to check status of the annotations" and "show or hide comment panel". Please review the changes.
Regards,
Ranjitha A.

BLAZ-25141 Added ug.

---

blazor/check-box/how-to/checkbox-model-binding.md
blazor/radio-button/how-to/radio-button-model-binding.md
blazor/radio-button/native-event.md

Added youtube video for checkbox and radio button component in Blazor UG.

(BLAZ-24533):Added youtube video for checkbox and radio button component in Blazor UG.

---

blazor/document-editor/accessibility.md
blazor/document-editor/how-to/export-document-as-pdf.md
blazor/document-editor/opening-a-document.md
blazor/document-editor/saving-document.md

Added the show/hide documentation short cut.

feature(EJ2-36027): Added the show/hide documentation short cut.

---

blazor-toc.html
blazor/treegrid/state-management.md

Included documentation for persistence.

documentation(BLAZ-25845): Included documentation for persistence

---

blazor/treegrid/state-management.md

Made the correction in persistence documentation.

documentation(BLAZ-25845): Made the correction in persistence documentation

---

blazor/document-editor/paragraph-format.md

Added the show/hide paragraph marks.

feature(EJ2-36027): Added the show/hide paragraph marks.

---

blazor/scheduler/virtual-scrolling.md

Need to include the UG for newly added feature in Schedule and Navigations
**Solution:**
1.Made changes in virtual scrolling contents and added API links.

documentation(EJ2-63828):Need to include the UG for newly added feature in Schedule and Navigations

---

blazor/appbar/style-and-appearance.md

Description
Content correction in AppBar Style and Appearance
Solution description
Content correction in AppBar Style and Appearance
Output screenshots
NA
Areas affected and ensured
Test cases
NA
Test bed sample location
NA
Did you run the automation against your implementation? NA
Does your code pass all FxCop and StyleCop rules? Yes
Did you record this case in the unit test or UI test? NA

documentation(BLAZ-26063): Content correction in AppBar Style and Appearance

---

blazor/treegrid/excel-export.md
blazor/treegrid/exporting.md
blazor/treegrid/filtering/filtering.md
blazor/treegrid/toolbar.md

Have added video for pdf, excel, toolbar template and filtering in treegrid.

doc(BLAZ-17765): Added video for pdf, excel, toolbar template and filtering in treegrid.

---

blazor/treegrid/rows/row-drag-and-drop.md

Mentioned about the Primarykey importance for RowDD

Added isPrimaryKey note for RowDragandDrop

---

blazor/check-box/accessibility.md

UG correction for checkbox component.

UG(EJ2-64748):UG correction for checkbox component.

---

blazor/pivot-table/calculated-field.md
blazor/pivot-table/drill-down.md
blazor/pivot-table/editing.md
blazor/pivot-table/field-list.md
blazor/pivot-table/filtering.md
blazor/pivot-table/grouping-bar.md
blazor/pivot-table/sorting.md

Review corrections completed for Pivot Table UG - Action events

documentation(BLAZ-26008): Review corrections completed for Pivot Table UG - Action events

---

blazor/message/getting-started.md

Need to include the reviewed content.
Need to include the reviewed content for getting started section in Blazor Message component.
Added the reviewed content.
NA
NA
NA
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

feature(EJ2-64707): Updated getting started section with reviewed content.

---

blazor/appbar/position.md
blazor/appbar/size-and-color.md

Description
Content correction in AppBar position, size and color
Solution description
Content correction in AppBar position, size and color
Output screenshots
NA
Areas affected and ensured
Test cases
NA
Test bed sample location
NA
Did you run the automation against your implementation? NA
Does your code pass all FxCop and StyleCop rules? Yes
Did you record this case in the unit test or UI test? NA

documentation(BLAZ-26649): Content correction in AppBar position, size and color

---

blazor/carousel/styles-and-appearance.md

In styles and appearance the CSS list table has been corrected.

documentation(EJ2-61581): CSS list table alignment has been corrected

---

blazor/appbar/getting-started.md

Description
Need to add Blazor AppBar video in UG
Solution description
AppBar getting started video added in UG documentation
Areas affected and ensured
Test cases
NA
Test bed sample location
NA
Did you run the automation against your implementation? NA
Does your code pass all FxCop and StyleCop rules? Yes
Did you record this case in the unit test or UI test? NA

documentation(BLAZ-26874): AppBar getting started video added in UG documentation

---

blazor-toc.html
blazor/message/accessibility.md
blazor/message/customization.md
blazor/message/icons.md
blazor/message/severities.md
blazor/message/template.md
blazor/message/variants.md

Need to include the reviewed content.
Need to include the reviewed content for features section in Blazor Message component.
Added the reviewed content.
NA
NA
NA
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

documentation(EJ2-65405): Content review corrections addressed for Message.

---

blazor/dropdown-list/code-snippet/getting-started/get-selected-value.razor
blazor/dropdown-list/code-snippet/getting-started/item-data.razor
blazor/dropdown-list/getting-started.md

Completed the blazor documentation revamp work on getting started section in dropdownlist

Bug(BLAZ-17102): Completed blazor documentation on getting started section

---

blazor/introduction.md

| Title | Description |
| -------- | -------- |
|**Task Link**|https://syncfusion.atlassian.net/browse/IN-18623|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. Need to change the Control list alignment to make it looks better.<br>3.These changes are in Overview page only, Some platforms are present inside the table.|
|**Solution description**|1.Added the new line-height, and new class.<br> 2. Also added the padding for list data to make it readable.<br>3. Apply the line-height as like our contents.<br>|
|**Output screenshots**|Control list ![image](https://user-images.githubusercontent.com/110027500/199717832-b1985e7e-456b-4228-a5f1-dce1dc73516a.png)|
|**Areas affected and ensured**|<ul><li>Changes are Fine wile ran Locally and also ensured that the changes are not …

IN-18623-Control-Category

---

blazor-toc.html

Need to update toc list order for Speed Dial UG documentation.
Toc list order for Speed Dial UG documentation.
Toc list order is updated for Speed Dial UG documentation.
NA
NA

documentation(BLAZ-26273): toc is updated for speeddial.

---

blazor/introduction.md

| Title | Description |
| -------- | -------- |
|**Task Link**|https://syncfusion.atlassian.net/browse/IN-18623|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. Need to change the Control list alignment to make it looks better.<br>3.These changes are in Overview page only, Some platforms are present inside the table.|
|**Solution description**|1.Added the new line-height, and new class.<br> 2. Also added the padding for list data to make it readable.<br>3. Apply the line-height as like our contents.<br>|
|**Output screenshots**|Control list ![image](https://user-images.githubusercontent.com/110027500/199717832-b1985e7e-456b-4228-a5f1-dce1dc73516a.png)|
|**Areas affected and ensured**|<ul><li>Changes are Fine wile ran Locally and also ensured that the changes are not …

IN-18623-Control-category-blazor

---

blazor/floating-action-button/events.md
blazor/floating-action-button/getting-started.md
blazor/floating-action-button/icons.md
blazor/floating-action-button/positions.md
blazor/floating-action-button/styles.md

Need to update UG heading casing and API links
Update UG heading casing and API links for Floating Action Button.
NA 
NA
NA

documentation(BLAZ-26909): FAB UG heading casing and API links update

---

blazor/floating-action-button/events.md
blazor/floating-action-button/getting-started.md
blazor/floating-action-button/icons.md
blazor/floating-action-button/positions.md
blazor/floating-action-button/styles.md

Need to update UG heading casing and API links in Blazor platform
Update UG heading casing and API links for Floating Action Button.
NA 
NA
NA

documentation(BLAZ-26909): FAB heading and api links updated

---

blazor/rich-text-editor/exec-command.md
blazor/rich-text-editor/form-validation.md
blazor/rich-text-editor/iframe.md

documentation(BLAZ-27011): Improved UG documentation for RTE component.

documentation(BLAZ-27011): Improved UG documentation for RTE component.

---

blazor/dropdown-list/code-snippet/selection/change-the-selected-value.razor

Resolved the file path error in the selection section

Bug(BLAZ-17102): Resolved the file path error in selection section

---

blazor/dropdown-list/value-binding.md

Resolved the error in value binding section

Bug(BLAZ-17102): Resolved the error in value binding section

---

blazor-toc.html

Resolved the file path error in blazor documentation

Bug(BLAZ-17102): Resolved the file path error in blazor documentation

---

blazor/rich-text-editor/style.md

documentation(BLAZ-23476): Published error resolved - Hotfix

documentation(BLAZ-23476): Published error resolved - Hotfix

---

blazor-toc.html

documentation(BLAZ-23476): Page not found issue resolved

documentation(BLAZ-23476): Page not found issue resolved

---

blazor-toc.html

documentation(BLAZ-23476): Insert Audio name changes - HF

documentation(BLAZ-23476): Insert Audio name changes - HF

---

blazor/appbar/design.md

AppBar component design document content correction
AppBar component design document content correction
AppBar component design document content correction
NA
NA
NA
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

documentation(EJ2-66203): AppBar component design document content correction

---

blazor/floating-action-button/positions.md

Need to update position topic for Fab control UG documentation.
Update position topic for Fab control UG documentation.
Updated position topic for Fab control UG documentation.
NA
NA

documentation(BLAZ-26268): conflict resolved.

---

blazor/multiselect-dropdown/data-binding.md

Bug(BLAZ-26137): Resolved blazor docs failure

---

blazor/pdfviewer/annotation/comments.md
blazor/pdfviewer/annotation/import-export-annotation.md
blazor/pdfviewer/annotation/shape-annotation.md
blazor/pdfviewer/annotation/stamp-annotation.md
blazor/pdfviewer/download.md
blazor/pdfviewer/events.md
blazor/pdfviewer/getting-started/server-side-application.md
blazor/pdfviewer/getting-started/web-assembly-application.md
blazor/pdfviewer/how-to/authorization-token.md
blazor/pdfviewer/how-to/change-the-highlighted-color-of-the-text.md
blazor/pdfviewer/how-to/check-status-of-annotations-or-comments.md
blazor/pdfviewer/how-to/check-whether-the-loaded-PDF-document-is-edited-or-not.md
blazor/pdfviewer/how-to/create-pdf-document-in-the-created-event-of-pdf-viewer.md
blazor/pdfviewer/how-to/create-pdfviewer-in-a-popup-window.md
blazor/pdfviewer/how-to/create-pdfviewer-in-a-splitter-component.md
blazor/pdfviewer/how-to/customize-arrow-annotation-heads.md
blazor/pdfviewer/how-to/get-data-from-pdf-viewer.md
blazor/pdfviewer/how-to/import-annotations-as-objects.md
blazor/pdfviewer/how-to/increase-connection-buffer-size.md
blazor/pdfviewer/how-to/load-desired-pdf-for-initial-loading-in-hosted-sample.md
blazor/pdfviewer/how-to/load-pdf-document-dynamically.md
blazor/pdfviewer/how-to/print-the-PDFViewer-inside-the-Dialog-component.md
blazor/pdfviewer/how-to/show-or-hide-pdfviewer-dynamically.md
blazor/pdfviewer/how-to/stretch-the-pdf-viewer-size-to-its-container.md
blazor/pdfviewer/how-to/update-form-field-using-context-menu.md
blazor/pdfviewer/interaction.md
blazor/pdfviewer/navigation.md
blazor/pdfviewer/opening-pdf-file.md
blazor/pdfviewer/toolbar-customization.md

Hi Kamesh,
I have resolved the samples broken links issue in ug documentation and committed. Please review the changes.
Regards,
Ranjitha A.

BLAZ-25699 Resolved the broken links and committed.

---

blazor/pdfviewer/annotation/comments.md
blazor/pdfviewer/annotation/import-export-annotation.md
blazor/pdfviewer/annotation/shape-annotation.md
blazor/pdfviewer/annotation/stamp-annotation.md
blazor/pdfviewer/download.md
blazor/pdfviewer/events.md
blazor/pdfviewer/getting-started/server-side-application.md
blazor/pdfviewer/getting-started/web-assembly-application.md
blazor/pdfviewer/how-to/authorization-token.md
blazor/pdfviewer/how-to/change-the-highlighted-color-of-the-text.md
blazor/pdfviewer/how-to/check-status-of-annotations-or-comments.md
blazor/pdfviewer/how-to/check-whether-the-loaded-PDF-document-is-edited-or-not.md
blazor/pdfviewer/how-to/create-pdf-document-in-the-created-event-of-pdf-viewer.md
blazor/pdfviewer/how-to/create-pdfviewer-in-a-popup-window.md
blazor/pdfviewer/how-to/create-pdfviewer-in-a-splitter-component.md
blazor/pdfviewer/how-to/customize-arrow-annotation-heads.md
blazor/pdfviewer/how-to/get-data-from-pdf-viewer.md
blazor/pdfviewer/how-to/import-annotations-as-objects.md
blazor/pdfviewer/how-to/increase-connection-buffer-size.md
blazor/pdfviewer/how-to/load-desired-pdf-for-initial-loading-in-hosted-sample.md
blazor/pdfviewer/how-to/load-pdf-document-dynamically.md
blazor/pdfviewer/how-to/print-the-PDFViewer-inside-the-Dialog-component.md
blazor/pdfviewer/how-to/show-or-hide-pdfviewer-dynamically.md
blazor/pdfviewer/how-to/stretch-the-pdf-viewer-size-to-its-container.md
blazor/pdfviewer/how-to/update-form-field-using-context-menu.md
blazor/pdfviewer/interaction.md
blazor/pdfviewer/navigation.md
blazor/pdfviewer/opening-pdf-file.md
blazor/pdfviewer/toolbar-customization.md

Hi Kamesh,
I have resolved the samples broken links issue in ug documentation and committed. Please review the changes.
Regards,
Ranjitha A.

BLAZ-25699 Resolved the broken links issue in development branch.

---

blazor-toc.html

Bug(BLAZ-17102): Added path to toc file

---

blazor/document-editor/clipboard.md
blazor/document-editor/fields.md
blazor/document-editor/form-fields.md
blazor/document-editor/history.md
blazor/document-editor/how-to/change-document-view.md
blazor/document-editor/how-to/customize-tool-bar.md
blazor/document-editor/how-to/disable-optimized-text-measuring.md
blazor/document-editor/how-to/export-document-as-pdf.md
blazor/document-editor/how-to/hide-tool-bar-and-properties-pane.md
blazor/document-editor/image.md
blazor/document-editor/link.md
blazor/document-editor/list-format.md
blazor/document-editor/table-of-contents.md
blazor/document-editor/table.md

Task - https://syncfusion.atlassian.net/browse/EJ2-66339
Fixed the broken link issue in documentation

bug(EJ2-66339): Fixed the broken link issue

---

blazor-toc.html
blazor/pdfviewer/how-to/render-ej2-pdf-viewer-in-blazor.md

I have added the page to describe how to render js component in blazor. Please review the changes.
Regards,
Ranjitha A.

BLAZ-27657 Added the page to describe how to render js component in blazor

---

blazor-toc.html
blazor/pdfviewer/how-to/render-ej2-pdf-viewer-in-blazor.md

I have added the page to describe how to render js component in blazor. Please review the changes.
Regards,
Ranjitha A.

BLAZ-27657 Page to describe how to render js component in blazor

---

blazor/pdfviewer/how-to/render-ej2-pdf-viewer-in-blazor.md

I have updated the sample link in ug and committed the same. Please review the changes.
Regards,
Ranjitha A.

BLAZ-27657 Added the sample in ug in hotfix branch.

---

blazor/pdfviewer/how-to/render-ej2-pdf-viewer-in-blazor.md

I have added the sample link in ug and committed the same. Please review the changes.
Regards,
Ranjitha A.

BLAZ-27657 Added the sample in ug in development branch.

---

blazor/treegrid/clipboard.md
blazor/treegrid/events.md

Added clipboard events and row dropping, row dropped events

documentation(BLAZ-27873):event

---

blazor/pdfviewer/getting-started/server-side-application.md
blazor/pdfviewer/getting-started/web-assembly-application.md

Hi Team,
Kindly review the modified content in Blazor PdfViewer and provide your feedback.
With Regards,
Gayathri R

EJ2-66939-Modified content in Blazor PdfViewer

---

blazor-toc.html
blazor/diagram-classic/data-binding.md
blazor/diagram/annotations/labels.md
blazor/diagram/connectors/connectors.md
blazor/diagram/connectors/customization.md
blazor/diagram/connectors/events.md
blazor/diagram/context-menu.md
blazor/diagram/events.md
blazor/diagram/interaction.md
blazor/diagram/layout/events.md
blazor/diagram/layout/organizational-chart.md
blazor/diagram/nodes/customization.md
blazor/diagram/nodes/events.md
blazor/diagram/nodes/nodes.md
blazor/diagram/ports/ports.md
blazor/diagram/scroll-settings.md
blazor/diagram/symbol-palette.md
blazor/diagram/tools.md

Hi @Keerthivasan-Ramamoorthy 
I have added Missing events in diagram. Can you please review this PR?
Regards,
Sumathi U.

BLAZ-24833-Missing events in UG

---

blazor/treegrid/events.md

resolved conflict in PR 1809 https://github.com/syncfusion-content/blazor-docs/pull/1809

documentation(ej2-66968): resolved conflict in PR 1809

---

blazor/gantt-chart/globalization.md

Changes made to the RTL sample in Blazor Gantt UG documentation

documentation(BLAZ-26929): Rtl

---

blazor/gantt-chart/globalization.md

Changes made to the RTL sample in Blazor Gantt UG documentation

documentation(BLAZ-26929): Gantt

---

blazor/introduction.md

BLAZ-100 - Update introduction.md

BLAZ-100 - Update introduction.md

---

blazor/calendar/dateonly-support.md
blazor/datepicker/dateonly-support.md
blazor/datepicker/mask-support.md
blazor/daterangepicker/dateonly-support.md
blazor/datetime-picker/mask-support.md
blazor/timepicker/mask-support.md
blazor/timepicker/timeonly-support.md

feature(BLAZ-27946):Added UG documentation for Date, Time and Datetime picker mask support and DateOnly, TimeOnly support.

feature(BLAZ-27946):Added UG documentation for Date, Time and Datetime picker mask support

---

blazor/tooltip/position.md

Removed the unwanted changes in the documentation

BLAZ-28030 : Removed the unwanted changes

---

blazor/document-editor/bookmark.md
blazor/document-editor/clipboard.md
blazor/document-editor/comments.md
blazor/document-editor/form-fields.md
blazor/document-editor/getting-started/client-side-application.md
blazor/document-editor/getting-started/server-side-application.md
blazor/document-editor/how-to/customize-context-menu.md
blazor/document-editor/how-to/customize-tool-bar.md
blazor/document-editor/how-to/disable-optimized-text-measuring.md
blazor/document-editor/how-to/export-document-as-pdf.md
blazor/document-editor/how-to/get-current-word.md
blazor/document-editor/how-to/get-the-selected-content.md
blazor/document-editor/how-to/hide-tool-bar-and-properties-pane.md
blazor/document-editor/how-to/insert-page-number-and-navigate-to-page.md
blazor/document-editor/how-to/insert-text-in-current-position.md
blazor/document-editor/how-to/read-only-default.md
blazor/document-editor/how-to/retrieve-the-bookmark-content-as-text.md
blazor/document-editor/how-to/show-hide-spinner.md
blazor/document-editor/link.md
blazor/document-editor/opening-a-document.md
blazor/document-editor/print.md
blazor/document-editor/saving-document.md
blazor/document-editor/track-changes.md

Resolved formatting issues
1. Resolved indentation in code blocks.
2. Removed unnecessary lines and spaces.
3. Removed empty line between the bullet points.

documentation(EJ2-65644): Resolved formatting issues

---

blazor/treegrid/how-to/single-click-editing-with-batch-mode.md

documentation(ej2-66968): resolved conflict in PR 1888

---

blazor/document-editor/getting-started/server-side-application.md

documentation(EJ2-65644): resolved conflict in PR 1888 
[EJ2-65644]: https://syncfusion.atlassian.net/browse/EJ2-65644?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

documentation(EJ2-65644): resolved conflict in PR 1888 

---

blazor/datetime-picker/date-time-format.md

feature(BLAZ-27946):Resolved the Spelling error date-time-format.md file
[BLAZ-27946]: https://syncfusion.atlassian.net/browse/BLAZ-27946?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feature(BLAZ-27946):Resolved the Spelling error date-time-format.md file

---

blazor/diagram/layout/events.md

I have added Layout events file. can you please review this PR?
Regards,
Sumathi U.

BLAZ-25058-Added LayoutEvent file

---

blazor-toc.html

documentation(BLAZ-28129): File validation issue changes reverted 
https://github.com/syncfusion-content/blazor-docs/pull/1896/commits/7767e17a9e64d62287e85a0b766d151c0be42df2

documentation(BLAZ-28129): File validation issue changes reverted

---

blazor/gantt-chart/data-binding.md

Modified the content and include github sample.

documentation(BLAZ-24480): lazy loading

---

blazor-toc.html

- Added API Reference for Rating Control

documentation(EJ2-68067): Added API Reference for Rating Control-hotfix

---

blazor-toc.html

- Added API Reference for Rating Control

documentation(EJ2-68067): Added API Reference for Rating Control-dev

---

blazor/common/extend-and-customize-components.md
blazor/common/input-validation.md
blazor/getting-started/license-key/how-to-register-in-a-razor-class-library.md
blazor/getting-started/license-key/how-to-register-in-an-application.md
blazor/getting-started/license-key/licensing-faq.md
blazor/getting-started/razor-class-library.md
blazor/nuget-packages.md
blazor/rating/getting-started.md
blazor/treegrid/selection.md
blazor/visual-studio-code-integration/convert-project.md

Updated missed alert contents in Blazor documentation.

documentation(BLAZ-27497): Updated missed alert contents

---

blazor-toc.html
blazor/diagram/bpmn-shapes/bpmn-shapes.md

Hi sir @Keerthivasan-Ramamoorthy 
The following corrections are made in the UG for documentation for Bpmn shapes
1. Bpmn group name in Toc file changed to Bpmn Expanded subprocess
2. Heading Changes in The Bpmn shapes.md file
Regards,
BalaVignesh

Bug(BLAZ-28444):Documentation Corrections

---

blazor-toc.html

Description:
Updated the TOC file with newly added tab-key-navigation.md file in blazor toolbar.
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA

Documentation(EJ2-66488):Updated the TOC file with newly added md file

---

blazor/diagram/bpmn-shapes/bpmn-activity.md
blazor/diagram/bpmn-shapes/bpmn-connectors.md
blazor/diagram/bpmn-shapes/bpmn-data-object.md
blazor/diagram/bpmn-shapes/bpmn-data-store.md
blazor/diagram/bpmn-shapes/bpmn-event.md
blazor/diagram/bpmn-shapes/bpmn-expanded-sub-process.md
blazor/diagram/bpmn-shapes/bpmn-gateway.md
blazor/diagram/bpmn-shapes/bpmn-shapes.md
blazor/diagram/bpmn-shapes/bpmn-text-annotation.md
blazor/diagram/overview-panel.md

I have updated sample link for code snippet. Can you please review this PR?
Regards,
Sumathi U.

BLAZ-25058-Overview and BPMN samples link

---

blazor/rating/appearance.md
blazor/rating/labels.md
blazor/rating/precision-modes.md
blazor/rating/selection.md
blazor/rating/templates.md
blazor/rating/tooltip.md

Need to add value for code blocks in rating component UG Documentation Blazor platform.
Added value for code blocks in rating component UG Documentation Blazor platform.
NA
NA
NA

documentation(BLAZ-28129): Updated rating UG documentation.

---

blazor-toc.html
blazor/common/content-security-policy.md

Document the Content security Policy Changes in our blazor platform.

documentation(BLAZ-28104): Update Content security Policy Changes

---

blazor/diagram/getting-started.md
blazor/diagram/interaction.md
blazor/diagram/layout/organizational-chart.md
blazor/diagram/page-settings.md
blazor/diagram/ports/appearance.md
blazor/diagram/ports/ports.md
blazor/diagram/shapes.md
blazor/diagram/symbol-palette.md
blazor/diagram/tool-tip.md

Resolved spelling error. Can you please review this PR?
Regards,
Sumathi U.

BLAZ-25058-UG correction

---

blazor/document-editor/how-to/customize-tool-bar.md

documentation(EJ2-67888): Added customize toolbar in Blazor

documentation(EJ2-67888): Added customize toolbar in Blazor

---

blazor/dropdown-list/style.md

Resolved the blazor documentation issue in staging site.

Bug(BLAZ-28521): Resolved the blazor documentation issue in staging site.

---

blazor/dropdown-list/value-binding.md

Bug(BLAZ-28521): Resolved staging link failure

---

blazor/treegrid/editing/column-validation.md

Remove DataAnnotation topic from the column validation topic in editing.

doc(BLAZ-28850):Remove DataAnnotation topic from the column validation topic in editing.

---

blazor-toc.html
blazor/pdfviewer/how-to/load-office-files.md

I have added the content for loading office files in pdf viewer. Please review the changes.
Regards,
Ranjitha A.

BLAZ-28936 Added the content for load office files in pdf viewer.

---

blazor/listbox/drag-and-drop.md

Resolved the broken links in the list box documentation

documentation(BLAZ-28823): Resolved the broken links in the listbox documentation

---

blazor/treeview/check-box.md
blazor/treeview/expand-collaspe-actions.md
blazor/treeview/node-editing.md

Included the new UG topics for Blazor TreeView component.

documentation(BLAZ-27484): Include new UG topics for Blazor TreeView - phase 4.

---

blazor/listview/customizing-templates.md

I have removed the unwanted class enabled for the span element in Blazor ListView Group Template sample.

documentation(BLAZ-29443): Need to remove the unwanted class enabled for the span element.

---

blazor/mention/getting-started.md
blazor/mention/templates.md

documentation(BLAZ-29788): Mention component video links are attached.

documentation(BLAZ-29788): Mention component video links are attached.

---

blazor/appearance/size-modes.md

Description:
The selector to change the font-size and font-family for all the components has been changed.

documentation(BLAZ-29372): Need to change the selector to change the font-size and font-family for all the components

---

blazor/gantt-chart/globalization.md
blazor/pivot-table/tool-bar.md

Please review the Blazor Page with redirect links changes.
Regards,
Yvone.

SEO-3379 Blazor Page with redirect

---

blazor/drop-down-menu/getting-started.md

Hi @aish
Please review changes for Blazor dropdown menu.
Regards,
Sharly A.

SEO-3353 - Blazor Dropdown Menu redirect links

---

blazor/nuget-packages.md

Description:
The links have been provided to component's friendly names.

documentation(BLAZ-29928):Need to provide links for component friendly names 

---

blazor/in-place-editor/server-actions.md

Server action sample doesn't works properly.
The issue occurs since the Sample configuration is not defined properly
The use-case is not checked before adding the samples.
No
No
Resolved the reported issue, by changing the code blocks of the components.
NA
NA
NA
No
/label ~bug

bug(BLAZ-29139): Server action sample doesn't works properly.

---

blazor/diagram/layout/organizational-chart.md

Kindly review my changes and provide your feedback for the same.
Regards,
Akshaya

documentation(BLAZ-30037): Add video link in UG content

---

blazor/nuget-packages.md

Need to provide links for component friendly names.

documentation(BLAZ-29928): Need to provide links for component friendly names.

---

blazor-toc.html

BLAZ-100 - Update blazor-toc.html

BLAZ-100 - Update blazor-toc.html

---

blazor/diagram/layout/complex-hierarchical-layout.md

Please review my changes and provide your feedback for the same.
Regards,
Akshaya

BLAZ-30076-Modified code for complex-hierarchical-layout

---

blazor-toc.html
blazor/diagram/overview-component.md

Hi @Keerthivasan-Ramamoorthy , I've renamed overview md file.

BLAZ-30202 - UG Revamp

---

blazor/treegrid/rows/row-model.md

Documentation changes for the new method added called "GetRowModel()".

Bug(BLAZ-28613):documentation for public method

---

blazor/diagram/symbol-palette.md

Kindly review my changes and provide your feedback for the same.
Regards,
Akshaya

documentation(BLAZ-30340): Need to add video link in Symbol Palette UG

---

blazor-toc.html

Have updated RowModel md file path in toc file.

doc(BLAZ-30375):Updated RowModel md file path in toc file.

---

blazor/getting-started/license-key/how-to-register-in-an-application.md

Description:
The accurate details for Syncfusion Blazor license key in the client web app has been provided.

documentation(BLAZ-30263): Need to provide accurate details for Syncfusion Blazor license key in the client web app

---

blazor/gantt-chart/custom-binding.md

Changes made on custom adaptor sample in ug documentation

documentation(BLAZ-28729): Custom

---

blazor/pdfviewer/how-to/resolve-System-EntryPointNotFound-exception.md

Hi Kamesh,
I have updated the content review changes and committed. Can you please review and merge the changes?
Regards,
Ranjitha A.

BLAZ-30272 Updated the content review changes.

---

blazor-toc.html
blazor/document-editor/how-to/optimize-sfdt.md

documentation(EJ2-71156): Added UG for optimize sfdt file

documentation(EJ2-71156): Added UG for optimize sfdt file

---

blazor-toc.html
blazor/document-editor/how-to/optimize-sfdt.md

documentation(EJ2-71156): Added UG for optimize sfdt

documentation(EJ2-71156): Added UG for optimize sfdt

---

blazor/diagram/connectors/connectors.md
blazor/diagram/nodes/nodes.md

I have added the You Tube Video links for nodes and connectors. Kindly review it and provide your feedback for the same.
Regards,
Akshaya

documentation(BLAZ-30463):Need to update video link for Nodes and Connectors

---

blazor/diagram/commands.md
blazor/diagram/undo-redo.md

Hi sir, I have updated the UG documentation and API linked for stack limit and paste method with argument support.

BLAZ-30057-Updated the UG Doc for stack Limit and Paste Support

---

blazor-toc.html

Hi @Keerthivasan-Ramamoorthy, I've updated toc file.

BLAZ-30202 - Updated toc file

---

blazor/diagram/layout/mind-map.md

Please review my changes and provide your feedback.
Regards,
Akshaya

documentation(BLAZ-30463):Need to update video link for Mindmap

---

blazor/treegrid/selection.md

Resolved the sample Errors By Added the missing @using for JSon converted and dependency injection for IJsRuntime

BLAZ-25028: Resolved sample errors by adding missing using

---

blazor/file-manager/how-to/add-custom-tool-bar.md

https://blazor.syncfusion.com/documentation/file-manager/how-to/add-custom-tool-bar
I have added the missing event declaration in the Blazor File Manager component.

documentation(BLAZ-29094): Need to add missing event declaration in the Blazor File Manager.

---

blazor/diagram/overview.md

Hi @Keerthivasan-Ramamoorthy , I've updated diagram overview md file.

BLAZ-30202 - diagram overview updated

---

blazor/file-manager/getting-started.md

Documentation for Directory Upload in Blazor FileManager.

documentation(BLAZ-29273):Documentation for Directory Upload in Blazor FileManager.

---

blazor/media-query/getting-started.md
blazor/rating/getting-started.md

Need to add getting started reference video link for Rating and Media-Query component .
Added getting started reference video link for Rating and Media-Query component .
NA
NA
* Is there any API name change? No
* Did you record this case in the unit test or UI test? NA

documentation (BLAZ-30789): Added Reference video for Rating and Media Query Control.

---

blazor/menu-bar/data-source-binding-and-custom-menu-items.md
blazor/menu-bar/getting-started.md

BLAZ-30804 - Added the MenuItemModel type in UG documentation

BLAZ-30804 - Added the MenuItemModel type in UG documentation

---

blazor/diagram/annotations/labels.md

Added video link for annotation. Can you please review this PR?
Regards,
Sumathi U.

BLAZ-30772- Need to update video link for annotation

---

blazor/common/custom-resource-generator.md
blazor/media-query/getting-started.md
blazor/rating/getting-started.md

documentation(BLAZ-30121): Conflict resolved.

---

blazor/button/style-and-appearance.md

docs(BLAZ-30950): Button Styles and Appearances sample modified

docs(BLAZ-30950): Button Styles and Appearances sample modified

---

blazor/pdfviewer/events.md

added the events as per in this page
https://help.syncfusion.com/cr/blazor/Syncfusion.Blazor.PdfViewer.PdfViewerEvents.html#Syncfusion_Blazor_PdfViewer_PdfViewerEvents_FormFieldClick

BLAZ-31086  :Need to add the documentation for Blazor PDFViewer events

---

blazor/diagram/group.md

Hi @sarathkumarvenkatesan ,
Added video link for group in UG. Can you please review this PR?
Regards,
Sumathi U.

BLAZ-30772-Need to update video link for Group

---

blazor/diagram/ports/ports.md

Hi @sarathkumarvenkatesan ,
Added video link for port and can you please review this PR?
Regards,
Sumathi U.

BLAZ-30772-Need to update video link for Port

---

blazor/treegrid/filtering/filter-bar.md

Corrected FilterBarTemplate sample to be runnable. Made sample changes

documentation(BLAZ-25033):Fixed

---

blazor/range-slider/how-to/reversible-slider.md

Hotfix branch Correction UG document for rendering reversible Slider in Blazor

documentation(BLAZ-30808):Hotfix branch Correction UG document for rendering reversible Slider in Blazor

---

blazor/listbox/how-to/add-items.md
blazor/listbox/how-to/select-items.md

825481 - Modified the deprecated method name listbox component

825481 - Modified the deprecated method name listbox component

---

blazor-toc.html

ES-826500: Removed unwanted Double Quote- Hotfix

---

blazor-toc.html

ES-826500: Removed unwanted Double Quote

---

blazor/button/style-and-appearance.md

docs(825481): UG correction for button component

docs(825481): UG correction for button component

---

blazor/gantt-chart/custom-binding.md

Removed the random data for custom binding, inject-service-into-custom-adaptor, curd operation samples.

documentation(820113): Need to correct UG samples

---

blazor/diagram/export.md
blazor/diagram/shapes.md

Hi sir @Keerthivasan-Ramamoorthy 
I've made the corrections in the Export and shapes documentation about Export to BMP format and committed the changes,
Regards,
Balavignesh

Bug(BLAZ-827254):Correction in Export documentation

---

blazor/chart/working-with-data.md
blazor/check-box/getting-started.md
blazor/circular-gauge/getting-started.md
blazor/circular-gauge/globalization.md
blazor/combobox/cascading.md
blazor/combobox/getting-started.md
blazor/context-menu/getting-started.md
blazor/dashboard-layout/getting-started.md
blazor/data/getting-started.md
blazor/datetime-picker/getting-started.md
blazor/diagram/print.md
blazor/toast/getting-started.md
blazor/toolbar/getting-started.md
blazor/treemap/getting-started.md
blazor/treeview/node-selection.md

Have changed title, description, h1, image alt and redirect links, please review.
Regards,
Yvone.

SEO-171351 Blazor Controls Site Audit

---

blazor/scheduler/data-binding.md

Updated contents and added samples in the data binding topic in Blazor scheduler
NA
NA

Documentation(ES-104982): Need to improve the Data Binding topic

---

blazor/scheduler/data-binding.md

Updated contents and added samples in the data binding topic in Blazor scheduler
NA
NA

Documentation(ES-104982):Updated contents for databinding topic in scheduler.

---

blazor/datagrid/data-binding.md

Hi @gowthamanthavasiyappan,
Please review the below PRs.
Regards,
Scholar.

SEO-171708 Blazor Page with redirect link

---

blazor/stock-chart/getting-started.md
blazor/timepicker/getting-started.md

Have worked on changing page with redirect links.
Regards,
Yvone.

SEO-171761 Blazor Controls Page with redirect

---

blazor/scheduler/data-binding.md

Updated contents and added samples in the Data-binding topic in Blazor scheduler
NA
NA

Documentation(SC-1049820):Updated contents in the Scheduler Data-binding topic in recent version.

---

blazor/appearance/theme-studio.md
blazor/document-editor/getting-started/client-side-application.md
blazor/pivot-table/data-binding.md
blazor/scheduler/header-bar.md
blazor/scheduler/localization.md
blazor/toolbar/item-configuration.md

Kindly review the changes for blazor page with redirect controls.
Regards,
Sharly A.

SEO-171912 - Blazor-Help-Page-With-Redirect

---

blazor/chart/chart-types/scatter.md

Hello, 
I have worked on the links with redirects.
Kind regards,
Beryl.

SEO-171719-Links-With-Redirects

---

blazor/getting-started/blazor-server-side-mac.md

Kindly review the changes for Blazor controls.
Regards,
Sharly A.

SEO-172146 - Blazor Controls

---

blazor/common/globalization.md
blazor/datagrid/context-menu.md
blazor/datagrid/webassembly-performance.md
blazor/in-place-editor/getting-started.md
blazor/toast/timeout.md

Hi @Girija-Rajendran,
Please review the blazor redirect link changes.
Regards,
Sharly .

SEO-172146 - Blazor Redirect Links

---

blazor/circular-gauge/annotations.md
blazor/circular-gauge/axes.md
blazor/datagrid/editing.md
blazor/getting-started/blazor-webassembly-visual-studio-mac.md
blazor/scheduler/resources.md

Have made changes for redirect links for react controls, please review.
Thanks.
Regards,
Edith.

SEO-172121-Blazor-Redirect-links

---

blazor/pivot-table/tool-bar.md

UG document to save and load report using database.

documentation(EJ2-67661): UG document to save and load report using database.

---

blazor/autocomplete/data-source.md
blazor/circular-gauge/user-interaction.md
blazor/input-mask/mask-configuration.md

Have made changes for redirect links for react controls, please review.
Thanks.
Regards,
Edith.

SEO-172121-Blazor-Redirect-link

---

blazor/combobox/data-source.md
blazor/dialog/accessibility.md
blazor/multiselect-dropdown/getting-started.md
blazor/pivot-table/number-formatting.md

Kindly review changes for Blazor redirect links.
Regards,
Selline Rita.

SEO-172142 - Blazor Redirect Links

---

blazor/treegrid/columns/columns.md
blazor/treegrid/data-binding.md
blazor/treegrid/editing/cell-edit-types.md

Added sample for dateonly and timeonly.

documentation(BLAZ-826548): Added sample for dateonly and timeonly

---

blazor/gantt-chart/data-binding.md

Web api URL changed in sample.

documentation(830341) : url changed

---

blazor/gantt-chart/events.md
blazor/gantt-chart/templates.md

Taskbar editing event added and updated.

830840 event

---

blazor/datagrid/getting-started.md
blazor/getting-started/blazor-server-side-visual-studio.md

https://github.com/syncfusion-content/blazor-docs/pull/2454

Commit for resolve '"' issue - playground integration

---

blazor/datagrid/getting-started.md
blazor/getting-started/blazor-server-side-visual-studio.md

- To Integrate blazor playground with blazor samples.

config(BLAZ-0000):  To Integrate blazor playground

---

blazor-toc.html
blazor/pdfviewer-2/download.md
blazor/pdfviewer-2/getting-started/web-assembly-application.md
blazor/pdfviewer-2/navigation.md
blazor/pdfviewer-2/print.md
blazor/pdfviewer-2/text-search.md

download, text search, navigation, print are added for SfPdfviewer

832158  :  download, text search, navigation, print are added for SfPdfviewer

---

blazor-toc.html
blazor/pdfviewer-2/events.md
blazor/pdfviewer-2/form-filling.md
blazor/pdfviewer-2/hand-written-signature.md
blazor/pdfviewer-2/interaction.md
blazor/pdfviewer-2/keyboard-accessibility.md
blazor/pdfviewer-2/magnification.md
blazor/pdfviewer-2/toolbar-customization.md

SfPdfViewer changes are handled in this PR

832158  :  SfPdfViewer changes are handled in this PR 

---

blazor-toc.html
blazor/pdfviewer-2/globalization.md

Globalization and RTL handles in this PR

832158 :  Globalization and RTL handles in this PR

---

blazor-toc.html
blazor/pdfviewer-2/getting-started/wsl-application.md

Added the documentation for Getting Started with Blazor PDF Viewer Component in WSL mode.

story(ES-832883): Wsl-documentation

---

blazor-toc.html
blazor/pdfviewer-2/saving-pdf-file.md

I have added the documentation for save-pdf-file.

story(ES-832883): save-pdf-file

---

blazor/appearance/icons.md
blazor/appearance/themes.md

Description:
The User Guide has been updated by adding the Fluent theme to the Icon list and then LibMan UG has been corrected for Blazor.

documentation(833288): Need to update the User Guide by adding the Fluent theme to the Icon list and correct LibMan UG for Blazor.

---

blazor/datagrid/virtualization.md

UG content location:https://blazor.syncfusion.com/documentation/datagrid/virtualization#column-virtualization
Column virtualization documentation changes modified.

Documentation: Column Virtualization Documentation Changes modified.

---

blazor/pdfviewer-2/download.md
blazor/pdfviewer-2/events.md
blazor/pdfviewer-2/getting-started/server-side-application.md
blazor/pdfviewer-2/getting-started/web-assembly-application.md
blazor/pdfviewer-2/opening-pdf-file.md

I have updated the GIthub sample links in Documentation.

UC_Documentation(ES-833426): Updated Github links.

---

blazor/treemap/getting-started.md
blazor/treemap/legend.md

Blaz-831582- Treemap sample code changes.

---

blazor/dashboard-layout/getting-started.md

The missing codes have been added to the Dashboard sample.
https://blazor.syncfusion.com/documentation/dashboard-layout/getting-started#panels-with-components

833959-Dashboard : Missing codes were added in the Dashboard sample.

---

blazor-toc.html
blazor/pdfviewer-2/how to/move-scrollbar.md
blazor/pdfviewer-2/how to/view-docx-file-in-blazor-application.md

I have added following how to topics in SfPdfViewer component. Can you please review the content?
1.View DOCX file in Blazor application.
2.Move the scrollbar to the exact location of annotations.
Regards,
Ranjitha A.

BLAZ-834242 Added how to topics in SfPdfviewer component.

---

blazor/pdfviewer-2/how to/import-annotations-as-objects.md
blazor/pdfviewer-2/how to/load-pdf-document-dynamically.md

Code changes for Load PDF documents dynamically in Blazor PDF Viewer and Import annotations as objects in SfPdfViewer

ES-832063 updated how to section

---

blazor/pdfviewer-2/how to/load-office-files.md
blazor/pdfviewer-2/how to/suppress-error-message.md

Added how-to sections
load office files
suppress-error-message

UG_Documentation(ES-834513-How-To): Added howto sections-load office files and suppress-error-message

---

blazor-toc.html
blazor/pdfviewer-2/how to/check-status-of-annotations-or-comments.md

Hi Kamesh,
I have added the how to check the status of comments topic and committed the changes.
Regards,
Ranjitha A.

BLAZ-834242 How to topics

---

blazor/pdfviewer-2/how to/change-the-highlighted-color-of-the-text.md
blazor/pdfviewer-2/how to/check-whether-the-loaded-PDF-document-is-edited-or-not.md
blazor/pdfviewer-2/how to/increase-connection-buffer-size.md
blazor/pdfviewer-2/how to/print-the-PDFViewer-inside-the-Dialog-component.md

Code changes for adding how to section in sfpdfviewer

ES-832063 updated the how to section in sfpdfviewer

---

blazor/pdfviewer-2/how to/create-pdf-viewer.md
blazor/pdfviewer-2/how to/customize-arrow-annotation-heads.md
blazor/pdfviewer-2/how to/suppress-error-message.md

I have added the contents for howto-Section.

UG_Documentation(ES-834513): Added the contents for howto-Section.

---

blazor-toc.html
blazor/pdfviewer-2/how to/create-pdfviewer-in-a-splitter-component.md
blazor/pdfviewer-2/how to/get-data-from-pdf-viewer.md
blazor/pdfviewer-2/how to/load-desired-pdf-for-initial-loading-in-hosted-sample.md
blazor/pdfviewer-2/how to/stretch-the-pdf-viewer-size-to-its-container.md

Update the Documentation for the new component SfPdfViewer
Kameshwaran Rajendran

ES-833867-UGforSfPdfViewer

---

blazor/common/how-to/add-blazor-component-on-existing-aspnet-core-mvc-app.md

Description:
"Add Blazor Component into Existing ASP.NET Core MVC Application" UG have been corrected.

documentation(834761): Need to correct "Add Blazor Component into Existing ASP.NET Core MVC Application" UG.

---

blazor/gantt-chart/columns.md

Added the documentation for DateOnly and TimeOnly Support in Gantt Chart

documentation(834262):DateOnlyTimeOnly

---

blazor/diagram/commands.md
blazor/diagram/connectors/segments.md
blazor/diagram/group.md
blazor/diagram/tools.md

Hi @Keerthivasan-Ramamoorthy sir, I have added API link to the new properties. Kindly review it.

BLAZ-834737-Added API Link

---

blazor/pivot-table/pivot-chart.md
blazor/pivot-table/tool-bar.md

Video links added for Toolbar and Pivot chart UG for Pivot table

doc(BLAZ-832244):  Video links added for Toolbar and Pivot chart UG for Pivot table

---

blazor/autocomplete/accessibility.md
blazor/context-menu/getting-started.md
blazor/in-place-editor/validation.md
blazor/stock-chart/getting-started.md
blazor/toolbar/getting-started.md

Have changed the redirect links, Kindly review.
Thanks.
Regards,
Edith.

SEO-172815-Blazor-Redirect-Links

---

blazor-toc.html

feature(834671): Blazor Image Editor Component API Link issue resolved.

feature(834671): Blazor Image Editor Component API Link issue resolved.

---

blazor/gantt-chart/rows.md

API link changed in GetRowTaskModel

documentation(BLAZ-000): API link changed in GetRowTaskModel

---

blazor/carousel/animations-and-transitions.md

Documentation content for the swipeMode, api has been drafted.

documentation(ES-378253): content drafted for the swipe mode ug doc

---

blazor/card/getting-started.md

bug(BUG-212139): Resolved UG failure

bug(BUG-212139): Resolved UG failure

---

blazor/carousel/animations-and-transitions.md

bug(ES-831685): typo errors  addressed.

---

blazor/datepicker/style-appearance.md
blazor/daterangepicker/style-appearance.md
blazor/datetime-picker/style-appearance.md
blazor/timepicker/style-appearance.md

We have included the full-screen popup feature documentation
The documentation added for explaining the new feature of full-screen popup
NA
NA
NA

feature(834525): Full screen feature documentation added

---

blazor/image-editor/annotation.md
blazor/image-editor/end-user-capabilities.md
blazor/image-editor/filter.md
blazor/image-editor/finetune.md
blazor/image-editor/localization.md
blazor/image-editor/open-save.md
blazor/image-editor/quick-access.md
blazor/image-editor/selection-cropping.md
blazor/image-editor/toolbar.md
blazor/image-editor/transform.md
blazor/image-editor/undo-redo.md

feature(836413): Image Editor UG changes committed.

feature(836413): Image Editor UG changes committed.

---

blazor/gantt-chart/events.md

Data bound and Row drag starting events added and updated.

documentation(832215): events added

---

blazor/scheduler/recurrence-editor.md

Description:
Mapping the api links in the recurrence editor topic for Blazor Scheduler documentation.
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA

documentation(ES-835216-RecurrenceEditor):mapping api link in recurrence-editor topic in blazor scheduler

---

blazor/carousel/animations-and-transitions.md

Description:
Resolve the Conflict.
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA

documentation(ES-838283-blazorDocumentation): Resolve conflict

---

blazor/pdfviewer-2/getting-started/deploy-maui-android.md

Hi Kamesh,
I have added the see also section and committed the changes.
Regards,
Ranjitha A.

BLAZ-838164 Added the see also section and committed.

---

blazor-toc.html
blazor/calendar/date-range.md

Resolved Documentation error in Calendar documentation

bug(BUG-838038): Resolved Documentation error in Calendar.

---

blazor/appearance/icons.md
blazor/appearance/theme-studio.md
blazor/appearance/themes.md

**Root:**
Need to update Blazor UG with material 3 theme details in the applicable places.
**Solution:**
Material 3 theme details are updated in the applicable places of Blazor UG by referring to the EJ2 TypeScript documentation.

documentation(838841): Need to update Blazor UG with material 3 theme details

---

blazor/appearance/themes.md

**Root:**
Need to correct the importing theme path of NPM package reference section.
**Solution:**
The importing theme paths of NPM package reference section have been corrected.

documentation(840014): Need to correct the importing theme path

---

blazor/accordion/accessibility.md
blazor/accumulation-chart/title-and-sub-title.md
blazor/appearance/theme-studio.md
blazor/calendar/accessibility.md
blazor/chart/axis-customization.md
blazor/chart/category-axis.md
blazor/chart/chart-annotations.md
blazor/chart/chart-dimensions.md

Worked on page with redirect for Blazor docs. Kindly review.
Regards,
Amy Kingstone.

SEO-173713-Blazor Page with redirect.1

---

blazor/getting-started/blazor-server-side-mac.md
blazor/getting-started/blazor-webassembly-visual-studio-mac.md

**Root:**
Need to add relevant details about macOS(ARM) in the Blazor UG.
**Solution:**
The relevant details about macOS(ARM) in the Blazor UG have been added.

documentation(838589): Need to add relevant details about macOS(ARM) in the Blazor UG

---

blazor/gantt-chart/data-binding.md

Odata adaptor sample added and updated.

documentation(837041): Odata sample added

---

blazor/document-editor/bookmark.md
blazor/document-editor/clipboard.md
blazor/document-editor/comments.md
blazor/document-editor/fields.md
blazor/document-editor/find-and-replace.md
blazor/document-editor/form-fields.md
blazor/document-editor/header-footer.md
blazor/document-editor/history.md
blazor/document-editor/how-to/get-current-word.md
blazor/document-editor/how-to/insert-page-number-and-navigate-to-page.md
blazor/document-editor/how-to/insert-text-in-current-position.md
blazor/document-editor/how-to/retrieve-the-bookmark-content-as-text.md
blazor/document-editor/how-to/show-hide-spinner.md
blazor/document-editor/image.md
blazor/document-editor/link.md
blazor/document-editor/list-format.md
blazor/document-editor/opening-a-document.md
blazor/document-editor/paragraph-format.md
blazor/document-editor/print.md
blazor/document-editor/section-format.md
blazor/document-editor/styles.md
blazor/document-editor/table-format.md
blazor/document-editor/table-of-contents.md
blazor/document-editor/table.md
blazor/document-editor/text-format.md

Resolved the incorrect code snippets

839770 - Resolved the incorrect code snippets

---

blazor/range-slider/ticks.md

I have added the ValueChanged property topic in the Blazor Slider component.

documentation(ES-841114): Need to add the ValueChanged property topic in the Blazor Slider component.

---

blazor/getting-started/blazor-server-side-dotnet-cli.md
blazor/introduction.md
blazor/scheduler/getting-started.md
blazor/skeleton/getting-started.md
blazor/spinner/getting-started.md
blazor/treegrid/rows/rows.md

Hi @MallikaRK 
Worked on blazor page with redirect.
Regards,
Sharly A.

SEO-174676 - Blazor page with redirect

---

blazor/floating-action-button/styles.md

FAB styles customization modified.

docs(BLAZ-841642): FAB styles customization modified  

---

blazor/floating-action-button/styles.md

FAB styles customization modified.

docs(BLAZ-841642): FAB styles customization modified - hotfix

---

blazor/gantt-chart/baseline.md

Baseline sample project start and end date changed

documentation(842188): Baseline sample project start and end date changed

---

blazor/gantt-chart/templates.md

Taskbar template taskbar editing issue solved

bug(839616): Taskbar template taskbar editing issue solved

---

blazor/introduction.md

| Title | Description |
| -------- | -------- |
|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/174643|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**||
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …

174643-Tablealignmentissue-dev

---

blazor/accumulation-chart/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Accumulation Chart Component_.

Remove the unwanted content from Getting Started with Blazor Accumulation Chart Component

---

blazor/accordion/getting-started.md

Remove the unwanted content from Getting Started with Blazor Accordion Component

Remove the unwanted content from Getting Started with Blazor Accordion Component

---

blazor/barcode/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Barcode Component_.

Remove the unwanted content from Getting Started with Blazor Barcode Component

---

blazor/datagrid/column-chooser.md
blazor/datagrid/column-menu.md
blazor/datagrid/column-reorder.md
blazor/datagrid/column-resizing.md
blazor/datagrid/column-template.md
blazor/datagrid/column-validation.md
blazor/datagrid/columns.md
blazor/datagrid/command-column-editing.md
blazor/datagrid/context-menu.md
blazor/datagrid/custom-binding.md
blazor/datagrid/data-annotation.md
blazor/datagrid/data-binding.md
blazor/datagrid/detail-template.md
blazor/datagrid/dialog-editing.md
blazor/datagrid/editing.md
blazor/datagrid/excel-exporting.md
blazor/datagrid/excel-like-filter.md
blazor/datagrid/filter-bar.md
blazor/datagrid/filter-menu.md
blazor/datagrid/filtering.md
blazor/datagrid/getting-started.md
blazor/datagrid/global-local.md
blazor/datagrid/grouping.md

842012-playground-Removing preview samples for Blazor components

---

blazor/bullet-chart/getting-started.md
blazor/card/getting-started.md
blazor/circular-gauge/getting-started.md
blazor/media-query/getting-started.md
blazor/progress-button/getting-started.md
blazor/treegrid/editing/edit.md
blazor/treemap/getting-started.md
blazor/visual-studio-code-integration/download-and-installation.md

Hi @MallikaRK,
Have updated the redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-174763-Blazor-page-with-redirect

---

blazor/badge/getting-started.md
blazor/bullet-chart/getting-started.md
blazor/datagrid/how-to/display-custom-tool-tip-in-grid-cell.md
blazor/introduction.md
blazor/maps/getting-started.md
blazor/speeddial/getting-started.md

Hi @MallikaRK,
Have updated the redirect links. Please review.
Thanks.
Regards,
Edith.

SEO-174763-Blazor-redirect-link

---

blazor/breadcrumb/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Breadcrumb Component_.

Remove the unwanted content from Getting Started with Blazor Breadcrumb Component

---

blazor/appbar/getting-started.md

Update title from AppBar Getting Started Catecory.

Update title from AppBar Getting Started Catecory

---

blazor/introduction.md

| Title | Description |
| -------- | -------- |
|**Task Link**|https://dev.azure.com/Syncfusion-Infrastructure/Install/_workitems/edit/175165|
|**Analysis and design**|1. Analyzed the details in the task.<br/>2. No design changes are required.|
|**Solution description**|1.Changed the col width in the introduction.md file|
|**Output screenshots**|-|
|**Areas affected and ensured**|<ul><li>Changes in the introduction.md file. Previous code didn't affected and ensured in end.</li></ul>|
|**Test cases**|Check the site locally.|
|**Testbed sample location**|-|
|**Additional CheckList**|<ul><li>Did you run the automation against your fix? No</li><li>Is there any API name change?No</li><li>Is there any existing behavior change of other features due to this code change? No.</li><li>Does your new …

175165-Changecolumnwidth-hotfix

---

blazor/bullet-chart/getting-started.md

Update Title from Getting Started with Blazor Bullet Chart Component.

Update Title from Getting Started with Blazor Bullet Chart Component

---

blazor/autocomplete/getting-started.md

Remove the unwanted content from Getting Started with Blazor AutoComplete Component.

Remove the unwanted content from Getting Started with Blazor AutoComplete Component

---

blazor/button/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Button Component_.

Remove the unwanted content from Getting Started with Blazor Button Component

---

blazor/gantt-chart/custom-binding.md

Custom adaptor sample modified and updated.
- Open and close bracket modified.
- Already updated the data source duration double value, but the class was defined as a string type, so it was changed to double.

documentation(835141) : custom adaptor sample modified

---

blazor/carousel/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Carousel Component._

Remove the unwanted content from Getting Started with Blazor Carousel Component

---

blazor/chip/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Chip Component_.

Remove the unwanted content from Getting Started with Blazor Chip Component

---

blazor/circular-gauge/getting-started.md

Remove the unwanted content from _Getting Started with Blazor CircularGauge Component_.

Remove the unwanted content from Getting Started with Blazor CircularGauge Component

---

blazor/calendar/getting-started.md

Minimize the content of UG documentation of Calendar getting started category.

Minimize the content of UG documentation of Calendar getting started category

---

blazor/combobox/getting-started.md

Remove the unwanted content from Getting Started with Blazor ComboBox Component.

Remove the unwanted content from Getting Started with Blazor ComboBox Component

---

blazor/color-picker/getting-started.md

Remove the unwanted content from _Getting Started with Blazor ColorPicker Component._

Remove the unwanted content from Getting Started with Blazor ColorPicker Component

---

blazor/bullet-chart/getting-started.md

Remove the unwanted content from Getting Started with Blazor Bullet Chart Component.

Remove the unwanted content from Getting Started with Blazor Bullet Chart Component

---

blazor/scheduler/data-binding.md

description:
clear the failures in  ug.
Areas affected and ensured:
Test cases:
NA
Test bed sample location:
NA

documentation(ES-835252-correction): Review correction addressed.

---

blazor/datagrid/getting-started.md

Remove the unwanted content from _Getting Started with Blazor DataGrid Component._

Remove the unwanted content from Getting Started with Blazor DataGrid Component

---

blazor/card/getting-started.md

Remove the unwanted content from Getting Started with Blazor Card Component.

Remove the unwanted content from Getting Started with Blazor Card Component

---

blazor/carousel/getting-started.md

Remove the unwanted content from Getting Started with Blazor Carousel Component .

Remove the unwanted content from Getting Started with Blazor Carousel Component 

---

blazor/treeview/styles.md

I have corrected the HtmlAttributes topic in the Blazor TreeView documentation.

documentation(ES-842909): Need to correct the HtmlAttributes topic in the Blazor TreeView documentation.

---

blazor/appbar/size-and-color.md

Resolved image not displayed issue in Prominent AppBar blazor preview sample documentation
NA
NA

Documentation(ES-819678): Resolved image not displayed issue in Prominent AppBar blazor preview sample

---

blazor/check-box/getting-started.md

Remove the unwanted content from Getting Started with Blazor CheckBox Component .

Remove the unwanted content from Getting Started with Blazor CheckBox Component 

---

blazor/dropdown-list/getting-started.md

Remove the unwanted content from Getting Started with Dropdown List.

Remove the unwanted content from Getting Started with Dropdown List

---

blazor/document-editor/getting-started/client-side-application.md
blazor/document-editor/getting-started/server-side-application.md

Remove the unwanted content from _Getting Started with Blazor DocumentEditor Component in Blazor._

Remove the unwanted content from Getting Started with Blazor DocumentEditor Component in Blazor

---

blazor/datetime-picker/getting-started.md

Remove the unwanted content from _Getting Started with Blazor DateTimePicker Component._

Remove the unwanted content from Getting Started with Blazor DateTimePicker Component

---

blazor/dashboard-layout/seo.md

I have removed the unwanted styles.

documentation(ES-842910): Need to remove the unwanted styles.

---

blazor/maps/getting-started.md

Remove the unwanted content from _Getting Started with Blazor Maps Component._

Remove the unwanted content from Getting Started with Blazor Maps Component

---

blazor/badge/getting-started.md

Remove the unwanted content from Getting Started with Blazor Badge Component.

Remove the unwanted content from Getting Started with Blazor Badge Component

---

blazor/avatar/getting-started.md

Remove the unwanted content from Getting Started with Blazor Avatar Component.

Remove the unwanted content from Getting Started with Blazor Avatar Component

---

blazor/file-manager/getting-started.md

Remove the unwanted content from Getting Started with Blazor FileManager Component.

Remove the unwanted content from Getting Started with Blazor FileManager Component

---

blazor/drop-down-menu/getting-started.md

Remove the unwanted content from Getting Started with Blazor Dropdown Menu Component.

Remove the unwanted content from Getting Started with Blazor Dropdown Menu Component

---

blazor/document-editor/getting-started/client-side-application.md
blazor/document-editor/getting-started/server-side-application.md

Remove the unwanted content from Getting Started with Blazor DocumentEditor Component in Blazor .

Remove the unwanted content from Getting Started with Blazor DocumentEditor Component in Blazor 

---

blazor/dialog/getting-started.md

Remove the unwanted content from Getting Started with Blazor Dialog Component.

Remove the unwanted content from Getting Started with Blazor Dialog Component

---

blazor/diagram/getting-started.md

Remove the unwanted content from Getting Started in Blazor Diagram Component.

Remove the unwanted content from Getting Started in Blazor Diagram Component

---

blazor/daterangepicker/getting-started.md

Remove the unwanted content from Getting Started with Blazor DateRangePicker Component.

Remove the unwanted content from Getting Started with Blazor DateRangePicker Component

---

blazor/gantt-chart/taskbar-editing.md

Modified taskbar editing UG documentation for the latest virtual taskbar edit element

documentation(843624): Virtual taskbar editing

---

blazor-toc.html
blazor/gantt-chart/resource-multi-taskbar.md
blazor/gantt-chart/resource-view.md

Added UG documentation for resource multi taskbar

documentation(843624): Resource multi taskbar

---

blazor/listview/getting-started.md

Remove the unwanted content from Getting Started with Blazor ListView Component.

Remove the unwanted content from Getting Started with Blazor ListView Component

---

blazor/kanban/getting-started.md

Remove the unwanted content from Getting Started with Blazor Kanban Component.

Remove the unwanted content from Getting Started with Blazor Kanban Component

---

blazor/in-place-editor/getting-started.md

Remove the unwanted content from Getting Started with Blazor In-place Editor Component.

Remove the unwanted content from Getting Started with Blazor In-place Editor Component

---

blazor/heatmap-chart/getting-started.md

Remove the unwanted content from Getting Started with Blazor HeatMap Chart Component.

Remove the unwanted content from Getting Started with Blazor HeatMap Chart Component

---

blazor/predefined-dialogs/getting-started.md

Remove the unwanted content from Getting Started with Predefined Dialogs in Blazor.

Remove the unwanted content from Getting Started with Predefined Dialogs in Blazor

---

blazor/floating-action-button/getting-started.md

Remove the unwanted content from Getting Started with Blazor Floating Action Button Component.

Remove the unwanted content from Getting Started with Blazor Floating Action Button Component

---

blazor/rich-text-editor/getting-started.md

Remove the unwanted content from _Getting Started with RichTextEditor in Blazor._

Remove the unwanted content from Getting Started with RichTextEditor in Blazor

---

blazor/input-mask/getting-started.md

Remove the unwanted content from Getting Started with Blazor Input Mask Component .

Remove the unwanted content from Getting Started with Blazor Input Mask Component 

---

blazor/listbox/getting-started.md

Remove the unwanted content from Getting Started with Blazor ListBox Component.

Remove the unwanted content from Getting Started with Blazor ListBox Component

---

blazor/gantt-chart/getting-started.md

Remove the unwanted content from Getting Started with Blazor Gantt Chart Component.

Remove the unwanted content from Getting Started with Blazor Gantt Chart Component

---

blazor/dashboard-layout/getting-started.md

Remove the unwanted content from Getting Started with Blazor Dashboard Layout Component.

Remove the unwanted content from Getting Started with Blazor Dashboard Layout Component

---

blazor/linear-gauge/getting-started.md

Remove the unwanted content from Getting Started with Blazor LinearGauge Component .

Remove the unwanted content from Getting Started with Blazor LinearGauge Component 

---

blazor/query-builder/getting-started.md

Remove the unwanted content from Getting Started with Blazor QueryBuilder Component

Remove the unwanted content from Getting Started with Blazor QueryBuilder Component 

---

blazor/progress-button/getting-started.md

Remove the unwanted content from Getting Started with Blazor ProgressButton Component .

Remove the unwanted content from Getting Started with Blazor ProgressButton Component 

---

blazor/progress-bar/getting-started.md

Remove the unwanted content from Getting Started with Blazor ProgressBar Component .

Remove the unwanted content from Getting Started with Blazor ProgressBar Component 

---

blazor/pivot-table/getting-started.md

Remove the unwanted content from Getting Started with Blazor Pivot Table Component.

Remove the unwanted content from Getting Started with Blazor Pivot Table Component

---

blazor/pager/getting-started.md

Remove the unwanted content from Getting Started with Blazor Pager Component .

Remove the unwanted content from Getting Started with Blazor Pager Component 

---

blazor/numeric-textbox/getting-started.md

Remove the unwanted content from Getting Started with Blazor NumericTextBox Component .

Remove the unwanted content from Getting Started with Blazor NumericTextBox Component 

---

blazor/multiselect-dropdown/getting-started.md

Remove the unwanted content from Getting Started with Blazor MultiSelect DropDown Component.

Remove the unwanted content from Getting Started with Blazor MultiSelect DropDown Component

---

blazor/menu-bar/getting-started.md

Remove the unwanted content from Getting Started with Blazor Menu Bar Component .

Remove the unwanted content from Getting Started with Blazor Menu Bar Component 

---

blazor/mention/getting-started.md

Remove the unwanted content from Getting Started with Blazor Mention Component.

Remove the unwanted content from Getting Started with Blazor Mention Component

---

blazor/avatar/getting-started.md

Included the style code snippet in the Blazor - Avatar Getting started page.

documentation(ES-840453): Need to include style code snippets in Blazor Avatar getting started page

---

blazor-toc.html

I have updated the order as we discussed and committed.
Regards,
Ranjitha A.

BLAZ-838173 Updated the PDF Viewer component below diagram classic.

---

blazor/toast/getting-started.md

Remove the unwanted content from Getting Started with Blazor Toast Component.

Remove the unwanted content from Getting Started with Blazor Toast Component

---

blazor/tabs/getting-started.md

Remove the unwanted content from Getting Started with Blazor Tabs Component.

Remove the unwanted content from Getting Started with Blazor Tabs Component

---

blazor/data/getting-started.md

Remove the unwanted content from Getting Started with Blazor DataManager Component.

Remove the unwanted content from Getting Started with Blazor DataManager Component

---

blazor/range-slider/getting-started.md

Remove the unwanted content from Getting Started with Blazor Range Slider Component.

Remove the unwanted content from Getting Started with Blazor Range Slider Component

---

blazor/media-query/getting-started.md

Remove the unwanted content from Getting Started with Blazor Media Query Component

Remove the unwanted content from Getting Started with Blazor Media Query Component 

---

blazor/range-selector/getting-started.md

Remove the unwanted content from Getting Started with Blazor Range Selector Component.

Remove the unwanted content from Getting Started with Blazor Range Selector Component

---

blazor/file-upload/getting-started.md

Remove the unwanted content from Getting Started with Blazor File Upload Component.

Remove the unwanted content from Getting Started with Blazor File Upload Component

---

blazor/multiselect-dropdown/data-binding.md

Documentation(483091) : Enum data binding support

Documentation(483091) : Enum data binding support

---

blazor/speeddial/getting-started.md

Remove the unwanted content from Getting Started with Blazor SpeedDial Component.

Remove the unwanted content from Getting Started with Blazor SpeedDial Component

---

blazor/spinner/getting-started.md

Remove the unwanted content from Getting Started with Blazor Spinner Component.

Remove the unwanted content from Getting Started with Blazor Spinner Component

---

blazor/split-button/getting-started.md

Remove the unwanted content from Getting Started with Blazor Split Button Component.

Remove the unwanted content from Getting Started with Blazor Split Button Component

---

blazor/timepicker/getting-started.md

Remove the unwanted content from Getting Started with Blazor TimePicker Component.

Remove the unwanted content from Getting Started with Blazor TimePicker Component

---

blazor/toggle-switch-button/getting-started.md

Remove the unwanted content from Getting Started with Blazor Toggle Switch Button Component.

Remove the unwanted content from Getting Started with Blazor Toggle Switch Button Component

---

blazor/toolbar/getting-started.md

Remove the unwanted content from Getting Started with Blazor Toolbar Component.

Remove the unwanted content from Getting Started with Blazor Toolbar Component

---

blazor/scheduler/getting-started.md

Remove the unwanted content from Getting Started with Blazor Scheduler Component.

Remove the unwanted content from Getting Started with Blazor Scheduler Component

---

blazor/sparkline/getting-started.md

Remove the unwanted content from Getting Started with Blazor Sparkline Component.

Remove the unwanted content from Getting Started with Blazor Sparkline Component

---

blazor-toc.html
blazor/sidebar/how-to/set-razor-page-as-main-content-of-sidebar.md

I have added the  "How to set razor pages as main content of the Sidebar" section in the documentation.

documentation(ES-844284): Need to add "How to set razor pages as main content of the Sidebar" section.

---

blazor/stock-chart/getting-started.md

Remove the unwanted content from Getting Started with Blazor Stock Chart Component.

Remove the unwanted content from Getting Started with Blazor Stock Chart Component

---

blazor/splitter/getting-started.md

Remove the unwanted content from Getting Started with Blazor Splitter Component.

Remove the unwanted content from Getting Started with Blazor Splitter Component

---

blazor/rating/getting-started.md

Adding script source in the Getting Started with Blazor Rating Component.

Adding script source in the Getting Started with Blazor Rating Component

---

blazor/treeview/getting-started.md

Remove the unwanted content from Getting Started with Blazor TreeView Component

Remove the unwanted content from Getting Started with Blazor TreeView Component

---

blazor/tooltip/getting-started.md

Remove the unwanted content from Getting Started with Blazor Tooltip Component.

Remove the unwanted content from Getting Started with Blazor Tooltip  Component

---

blazor-toc.html
blazor/pdfviewer/annotation/comments.md
blazor/pdfviewer/annotation/free-text-annotation.md
blazor/pdfviewer/annotation/import-export-annotation.md
blazor/pdfviewer/annotation/ink-annotation.md
blazor/pdfviewer/annotation/measurement-annotation.md
blazor/pdfviewer/annotation/shape-annotation.md
blazor/pdfviewer/annotation/stamp-annotation.md
blazor/pdfviewer/annotation/sticky-notes-annotation.md
blazor/pdfviewer/annotation/text-markup-annotation.md
blazor/pdfviewer/download.md
blazor/pdfviewer/events.md
blazor/pdfviewer/form-filling.md
blazor/pdfviewer/getting-started/features.md
blazor/pdfviewer/getting-started/server-side-application.md
blazor/pdfviewer/getting-started/web-assembly-application.md
blazor/pdfviewer/getting-started/wsl-application.md
blazor/pdfviewer/globalization.md
blazor/pdfviewer/hand-written-signature.md
blazor/pdfviewer/interaction.md
blazor/pdfviewer/keyboard-accessibility.md
blazor/pdfviewer/magnification.md
blazor/pdfviewer/navigation.md
blazor/pdfviewer/opening-pdf-file.md
blazor/pdfviewer/print.md
blazor/pdfviewer/saving-pdf-file.md
blazor/pdfviewer/text-search.md
blazor/pdfviewer/toolbar-customization.md

Changes for changing the order of the pdfviewer in toc file.

documentation(ES-845744): changed the order of the Pdfviewer in toc file

---

blazor/treemap/getting-started.md

Remove the unwanted content from Getting Started with Blazor TreeMap Component.

Remove the unwanted content from Getting Started with Blazor TreeMap Component

---

blazor/treegrid/getting-started.md

Remove the unwanted content from Getting Started with Blazor TreeGrid Component.

Remove the unwanted content from Getting Started with Blazor TreeGrid Component

---

blazor/tooltip/getting-started.md

Remove the unwanted content from Getting Started with Blazor Tooltip Component.

Remove the unwanted content from Getting Started with Blazor Tooltip Component

---

blazor/gantt-chart/context-menu.md

Handled the exception that can occur if context menu is opened on chart side.

846263-SampleHandling

---

blazor/treemap/getting-started.md

Remove the unwanted content from Getting Started with Blazor TreeMap Component .

Remove the unwanted content from Getting Started with Blazor TreeMap Component 

---

blazor/gantt-chart/state-management.md

bug(847176): Persist UG sample modified

---

blazor/getting-started/microsoft-teams-app.md

Remove the unwanted content from _Getting Started with Microsoft Teams Application_.

Remove the unwanted content from Getting Started with Microsoft Teams Application

---

blazor/getting-started/blazor-electron-app.md

Remove the unwanted content from Creating Desktop Application using Blazor and Electron

Remove the unwanted content from Creating Desktop Application using Blazor and Electron

---

blazor-toc.html
blazor/browser-support.md
blazor/getting-started/blazor-single-nuget.md
blazor/nuget-packages.md

Improvements in the following categories: Browser Compatibility, Newly Added Getting Started with Syncfusion Blazor Single NuGet, and NuGet Packages from Syncfusion Blazor Components UG documentation.

Improvement the Syncfusion Blazor Components UG documentation

---

blazor/file-manager/how-to/customize-http-handler.md

Need to add UG on File Manager Authentication.

(ES-842243):HTTP docs

---

blazor/document-editor/table-format.md

I have added UG documentation for title and description

feature(EJ2-846201): added UG for AltTab

---

blazor/gantt-chart/row-selection.md
blazor/gantt-chart/selection.md

Issue 1:Added valid Date
Issue 2:Changed double to int
Issue 3:Added looping for selectedRowIndexes and Records
Issue 4:Changed double to int

config(843950): Issue on selection UG samples

---

blazor/gantt-chart/context-menu.md

Issue 1 : Added EditSettings for " context menu's sub-items" and "disable-context-menu-items-dynamically" sample.
Issue 2 : Added "@using Syncfusion.Blazor.Gantt" namespace for  "disable the contextmenu for specific columns sample".

config(844077): Sample error in context menu UG samples

---

blazor-toc.html

Hi all,
- With this PR, we have modified the DocIO & Presentation controls direct links in Blazor platform UG.
- Removed pages other than Overview and Getting Started.
Regards,
Dharanitharan A

ES-846833-Modified DocIO & Presentation controls direct links in Blazor platform UG-hotfix

---

blazor/datagrid/events.md

Added OnColumMenuOpen event in blazor grid events section
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/835224

documentation(835224): Added OnColumnMenuOpen event in events section

---

blazor/datagrid/webassembly-performance.md

Corrected the page not found links in this help page. Please check and merge.
Thanks,
Yvone.

SEO-175659 Blazor Page Not Found

---

blazor/datagrid/events.md

Added OnColumMenuOpen event in blazor grid events section
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/835224

documentation(835224): Added OnColumnMenuOpen event in events section 

---

blazor/datagrid/events.md

Events added in data grid events section
Task Link: https://dev.azure.com/EssentialStudio/Ej2-Web/_workitems/edit/847863

documentation(847863): Need to prepare documentation for Action event split up new events

---

blazor/scheduler/virtual-scrolling.md

UG included for lazy loading feature

docs(ES-378260): UG included for lazy loading feature

---

blazor/pivot-table/virtual-scrolling.md

To Include documentation for single page mode

Documentation(Blaz-847974) :  To Include documentation for single page mode

---

blazor/datagrid/getting-started.md

Added preview sample link to Blazor DataGrid getting started UG documentation.

849461-Added preview sample link

---

blazor/gantt-chart/column-reordering.md

Added Changes for above mentioned issue

config(843946): Sample error in Reorder Columns UG sample

---

blazor/getting-started/microsoft-teams-app.md

Updated the Getting Started with Microsoft Teams Application.

Updated the Getting Started with Microsoft Teams Application

---

blazor/getting-started/blazor-server-side-visual-studio.md

Updated the Getting Started with Blazor Server Side App in Visual Studio.

Updated the Getting Started with Blazor Server Side App in Visual Studio

---

blazor/getting-started/blazor-single-nuget.md

Updated the blazor-single-nuget.md.

Updated the blazor-single-nuget.md

---

blazor/pivot-table/data-binding.md

Made corrections for frequently asked requirements for Blazor platforms in Data binding topic.

bug(848541): Made corrections for frequently asked requirements for Blazor platforms in Data binding topic.

---

blazor-toc.html

Reorder the Blazor pivot table topics in UG documentation.

bug(848541): Reorder the Blazor pivot table topics in UG documentation.

---

blazor/image-editor/annotation.md
blazor/image-editor/frame.md
blazor/image-editor/resize.md

ej2(847785) - New UG samples for image editor new features in blazor platform.

ej2(847785) - New UG samples for image editor new features in blazor platform.

---

blazor-toc.html

Hi All,
Modify the TOC file for DocIo and Presentation Product.
Task Link: https://dev.azure.com/EssentialStudio/Document%20Processing%20Libraries/_workitems/edit/851567
Regards
venkatesh

ES-851567 Modify TOC File

---

blazor/document-editor/getting-started/client-side-application.md

Resolved the documentation issue steps for wasam.

Resolved the documentation issue steps for wasam.

---

blazor/document-editor/how-to/optimize-sfdt.md

Updated the code style issue.

---

blazor/datagrid/how-to/customize-icon-column-menu.md

BLAZ-851530-Need to remove the dot.

---

blazor/file-manager/getting-started.md
blazor/range-selector/getting-started.md
blazor/splitter/getting-started.md

Updated the Code snippet from Syncfusion Blazor Getting Started Category.

Updated the Code snippet from Syncfusion Blazor Getting Started Category.

---

blazor/toast/getting-started.md
blazor/toast/timeout.md
blazor/treegrid/rows/detail-template.md
blazor/treegrid/rows/row-drag-and-drop.md
blazor/treegrid/rows/row-height.md
blazor/treegrid/rows/row-template.md
blazor/treegrid/rows/rows.md

Worked on blazor page with redirect .
Regards,
Sharly A.

SEO-176126 - Blazor page with redirect

---

blazor/button-group/getting-started.md
blazor/button/getting-started.md
blazor/common/localization.md
blazor/data/getting-started.md
blazor/file-upload/async.md
blazor/scheduler/resources.md
blazor/treegrid/filtering/filtering.md

Hi @MallikaRK,
Made changes for blazor controls.
Regards,
Sharly A.

SEO-176126 - Blazor Page With Redirect changes

---

blazor/calendar/multi-select.md
blazor/datepicker/accessibility.md
blazor/diagram-classic/howTo/blazor-web-assembly-diagram.md
blazor/maps/internationalization.md
blazor/rich-text-editor/link.md
blazor/stock-chart/range-selector.md

Worked on page with redirect for blazor.
Regards,
Sharly A.

SEO-175665 - Blazor page with redirect changes

---

blazor/chart/chart-types/spline.md
blazor/common/how-to/create-blazor-webassembly-prerendering.md
blazor/common/localization.md
blazor/getting-started/blazor-server-side-visual-studio.md

Conflict Issue resolved .

---

blazor-toc.html

I have added XlsIO control UG redirect links.

854120-XlsIOChanges

---

blazor-toc.html
blazor/datagrid/custom-toolbar.md
blazor/datagrid/tool-bar.md
blazor/datagrid/toolbar-items.md

BLAZ-850514-Toolbar topic revamp

---

blazor-toc.html
blazor/datagrid/aggregates.md
blazor/datagrid/custom-aggregate.md
blazor/datagrid/footer-aggregate.md
blazor/datagrid/group-and-caption-aggregate.md
blazor/datagrid/reactive-aggregate.md

Blazor datagrid documentation Aggregates topics revamp.

BLAZ-839255-Blazor datagrid documentation Aggregates topics revamp.

---

blazor/datagrid/searching.md

Blaz 839540 searchinghotfix
